.circleci/config.yml

Modeled after https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/commit/01df2a81214a5a890f20b41822468cd0d892fedb#diff-78a8a19706dbd2a4425dd72bdab0502ed7a2cef16365ab7030a5a0588927bf47
But simplified following the pattern in #2

Add the prod storybook deploy workflow

---

.storybook/preview-head.html
.storybook/preview.js
src/components/HelpMenu/HelpMenu.jsx
src/components/Telephone/Telephone.mdx
stories/back-to-top.stories.mdx

Copy the most recent changes over from `formation-react`.
After this is merged, we will close the following open PRs in the tools repo which make changes to `formation-react`, so that we don't have to keep doing this manual migration.
- https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/334
- https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/551

Final migration from formation-react

---

package.json
yarn.lock

This updates the version of `formation` we are using. Makes a difference in Storybook.
Verified that BTT worked as expected in Storybook

Update formation dependency

---

package.json
src/components/Select/Select.jsx
src/components/Select/Select.mdx
src/components/Select/Select.stories.jsx
src/components/Select/Select.unit.spec.jsx

Closes [19157](https://github.com/department-of-veterans-affairs/va.gov-team/issues/19157);
OG ticket: [19117](https://github.com/department-of-veterans-affairs/va.gov-team/issues/19117#issuecomment-768406699)
Added unit test, ran unit tests, ran axe chrome extensions locally, manual testing with voice over screen reader active.

Select 508 enchancement

---

.storybook/main.js
.storybook/preview.js
package.json
src/components/my-component/my-component.stories.tsx
tsconfig.json

Part of https://github.com/department-of-veterans-affairs/va.gov-team/issues/19484
This adds configuration to get a local Storybook running with the built Stencil components. The configuration is based off of prior work discussed here: https://github.com/storybookjs/storybook/issues/4600#issuecomment-757062096
Storybook

Add a storybook+stencil setup

---

.prettierrc
src/components/MonthYear/MonthYear.stories.jsx

Add year value to fix storybook error

---

.github/workflows/node.js.yml

Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/20051
This adds a GitHub action that will run `yarn test` in each of our PRs to `master`.
Once this is merged, I will open a similar PR to add this workflow to the `web-components` branch.
- Checked that GH actions run & pass
A screenshot of this very PR :scream: 
Additionally, `build_and_test` is set up to be a required check:

Add testing to CI processes

---

src/components/va-accordion/va-accordion.stories.tsx

No ticket, just fixing a typo in Storybook

fix typo in va-accordion

---

stories/va-accordion.stories.jsx

Fixing typo in accordion section for live site
Visual

fix typo in accordion story

---

.circleci/config.yml
package.json
stories/va-on-this-page.stories.jsx
yarn.lock

Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/20784
Related to https://github.com/department-of-veterans-affairs/component-library/pull/59
Add a story for `<va-on-this-page>`

Add on-this-page component to Storybook

---

package.json
src/components/Breadcrumbs/Breadcrumbs.jsx
src/components/Breadcrumbs/Breadcrumbs.unit.spec.jsx

For https://github.com/department-of-veterans-affairs/va.gov-team/issues/14490
"Standardize data layer events and variables to track breadcrumbs across va.gov"
~### TODO: write tests~

Add analytics to Breadcrumbs component

---

package.json
stories/action-link.stories.mdx
yarn.lock

Updating action link class names
https://app.zenhub.com/workspaces/vsp-design-system-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/426
Visual check in storybook

update action link classes

---

package.json
yarn.lock

Update Formation to 6.16.1

---

package.json
src/components.d.ts
src/components/va-accordion/va-accordion.e2e.ts
src/components/va-accordion/va-accordion.stories.tsx
src/components/va-accordion/va-accordion.tsx

For:  https://github.com/department-of-veterans-affairs/va.gov-team/issues/14487

Added analytics to accordion web component

---

src/components.d.ts
src/components/va-text-input/test/va-text-input.e2e.ts
src/components/va-text-input/va-text-input.css
src/components/va-text-input/va-text-input.tsx
src/global/variables.css
src/index.html

Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/25142
**Normal**
**Required**
**Error**
**Error with `<body>` highlighted**
Because the red bar on the left extends outside of the parent node.
See the test cases written for a list of AC.

Va text input cv

---

package.json
stories/va-checkbox.stories.jsx
yarn.lock

Adds the stories for `va-checkbox`.

va-checkbox stories

---

src/components.d.ts
src/components/va-checkbox/test/va-checkbox.e2e.ts
src/components/va-checkbox/va-checkbox.tsx
src/components/va-text-input/test/va-text-input.e2e.ts
src/components/va-text-input/va-text-input.tsx

Adds the `vaBlur` and `vaChange` events to `va-checkbox` and `va-text-input`.
Unit tests written.

Event emitters text input checkbox cv

---

package.json
src/components.d.ts
src/components/va-accordion/va-accordion.e2e.ts
src/components/va-accordion/va-accordion.tsx

Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/27198
Storybook testing & stencil dev server
Also, E2E tests

Allow multiple accordion items open by default

---

src/components/AdditionalInfo/AdditionalInfo.jsx
src/components/CheckboxGroup/CheckboxGroup.jsx
src/components/CollapsiblePanel/CollapsiblePanel.jsx
src/components/Date/Date.jsx
src/components/FileInput/FileInput.jsx
src/components/MonthYear/MonthYear.jsx
src/components/NumberInput/NumberInput.jsx
src/components/Pagination/Pagination.jsx
src/components/ProgressButton/ProgressButton.jsx
src/components/RadioButtons/RadioButtons.jsx
src/components/SegmentedProgressBar/SegmentedProgressBar.jsx
src/components/Select/Select.jsx
src/components/TextArea/TextArea.jsx
src/components/TextInput/TextInput.jsx
src/helpers/fields.js
src/helpers/validations.js

Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/219

Clean up lodash imports

---

src/components/Breadcrumbs/Breadcrumbs.jsx

Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/240
Tested with VoiceOver in Storybook.

Add list role to Breadcrumbs for screen readers

---

package.json
src/components/Date/Date.jsx
src/components/Date/Date.unit.spec.jsx
src/components/Date/SimpleDate.jsx
src/components/Date/SimpleDate.unit.spec.jsx
src/components/NumberInput/NumberInput.jsx
src/components/NumberInput/NumberInput.unit.spec.jsx
src/components/Select/Select.jsx
yarn.lock

`SimpleDate` pulls out the visual elements of the `Date` into its own component. The `Date` field then uses it and layers the validation on top.
The change was so Formulate can control the validation.
Along the way, I also added `onBlur` to `Date`, `NumberInput`, and `Select` so we can call the validation functions we want when the field is blurred.

SimpleDate

---

.github/workflows/add-release-files.yml
src/components/va-alert/va-alert.tsx

Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/242

Add aria hidden to alert box to prevent screen reader tab stop

---

src/components/Modal/Modal.jsx
src/components/OMBInfo/OMBInfo.jsx
src/components/OMBInfo/OMBInfo.unit.spec.jsx
src/helpers/test-helpers.js

Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/224

Add aXe test to OMBInfo component with modal open

---

src/components/va-on-this-page/test/va-on-this-page.e2e.ts
src/components/va-on-this-page/va-on-this-page.css
src/components/va-on-this-page/va-on-this-page.tsx

Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/252
Manual testing

Accessibility changes for On This Page component

---

src/components/Modal/Modal.jsx

Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/233

Update Modal accessibility tags

---

.gitignore
src/components/Pagination/Pagination.jsx
src/components/Pagination/Pagination.unit.spec.jsx

Closes <https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/232>
All tests pass.

Improve pagination accessibility

---

src/components/AdditionalInfo/AdditionalInfo.jsx
src/components/AdditionalInfo/AdditionalInfo.unit.spec.jsx

Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/246
I was a little unclear here on exactly what was the goal of this ticket, so please let me know if more or something entirely different needs to be done here.
Tested in storybook and when focused, the spacebar collapsed the info box as expected.

Add event listener and role to additional info component

---

.github/workflows/chromatic.yml
.github/workflows/node.js.yml

This is to keep the commit history from getting cluttered in the main PR #199 
CI :eyes:

Create new branch to test all the CI changes

---

packages/react-components/.eslintrc.js
packages/react-components/package.json
packages/react-components/src/components/MaintenanceBanner/MaintenanceBanner.jsx
packages/react-components/src/components/MaintenanceBanner/MaintenanceBanner.mdx
packages/react-components/src/components/MaintenanceBanner/MaintenanceBanner.unit.spec.jsx
packages/react-components/src/helpers/format-date.js
packages/react-components/src/helpers/format-date.unit.spec.js
yarn.lock

Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/23523
Unit tests
N/A

Update MaintenanceBanner to use native date functions

---

packages/core/package.json
packages/core/webpack.config.js
packages/storybook/.storybook/main.js
packages/storybook/package.json
packages/web-components/package.json
yarn.lock

Fix web components/storybook in IE11

---

packages/core/package.json
packages/core/webpack.config.js
packages/storybook/.storybook/main.js
packages/storybook/package.json
packages/web-components/package.json
yarn.lock

Reverts parts of department-of-veterans-affairs/component-library#247

Revert storybook changes

---

packages/core/package.json
packages/react-components/package.json
yarn.lock

Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/34418
Chrome
Firefox
Safari
Edge
- PENDING for IE 11 Tested and confirmed working in all supported browsers: https://depo-platform-documentation.scrollhelp.site/developer-docs/Browser-Support-Policy.1847951366.html
- Note will need to test IE11 support once PR is merged and release is deployed

34418 Removing core-js dependency in react components

---

packages/react-components/src/components/OMBInfo/OMBInfo.jsx
packages/react-components/src/components/OMBInfo/OMBInfo.mdx
packages/react-components/src/components/OMBInfo/OMBInfo.unit.spec.jsx
packages/storybook/stories/OMBInfo.stories.jsx

Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/34524
N/A

Update OMBInfo property description

---

packages/react-components/package.json
packages/storybook/package.json
packages/web-components/package.json
yarn.lock

Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/35373

35373 Radio and Checkbox Styles Bump Version of New Formation Package

---

packages/storybook/stories/events.js
packages/storybook/stories/va-accordion.stories.jsx
packages/storybook/stories/va-alert.stories.jsx
packages/storybook/stories/va-checkbox-group.stories.jsx
packages/storybook/stories/va-checkbox.stories.jsx
packages/storybook/stories/va-radio.stories.jsx
packages/storybook/stories/va-select.stories.jsx
packages/storybook/stories/va-text-input.stories.jsx
packages/storybook/stories/wc-helpers.jsx
packages/web-components/src/components.d.ts
packages/web-components/src/components/va-accordion/va-accordion.tsx
packages/web-components/src/components/va-additional-info/va-additional-info.tsx
packages/web-components/src/components/va-alert/va-alert.tsx
packages/web-components/src/components/va-breadcrumbs/va-breadcrumbs.tsx
packages/web-components/src/components/va-checkbox-group/va-checkbox-group.tsx
packages/web-components/src/components/va-progress-bar/va-progress-bar.tsx
packages/web-components/src/components/va-radio-option/va-radio-option.tsx
packages/web-components/src/components/va-radio/va-radio.tsx
packages/web-components/src/components/va-segmented-progress-bar/va-segmented-progress-bar.tsx
packages/web-components/src/components/va-select/va-select.tsx
packages/web-components/src/components/va-telephone/va-telephone.tsx

Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/34746
N/A

Add web component events documentation on Storybook

---

packages/web-components/src/components/va-additional-info/test/va-additional-info.e2e.ts
packages/web-components/src/components/va-additional-info/va-additional-info.css
packages/web-components/src/components/va-additional-info/va-additional-info.tsx

Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/34991
Storybook
https://user-images.githubusercontent.com/36863582/153097460-a7a4647b-494c-4cd8-afb5-d6bd9f991108.mov

Fix va-additional-info content overflow

---

packages/core/package.json
packages/storybook/stories/va-pagination.stories.jsx
packages/web-components/package.json
packages/web-components/src/components.d.ts
packages/web-components/src/components/va-pagination/test/va-pagination.e2e.ts
packages/web-components/src/components/va-pagination/va-pagination.css
packages/web-components/src/components/va-pagination/va-pagination.tsx

Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/35098
E2E

Add va-pagination component

---

packages/react-components/src/components/Table/Table.jsx

Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/36910
Original issue

Fix Table axe check aria-label

---

packages/storybook/stories/va-banner.stories.jsx

Hotfix Va-Banner Storybook Type Dropdown adds all types available

Hotfix Va-Banner Storybook Type Dropdown

---

packages/react-components/package.json
packages/web-components/package.json
yarn.lock

Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/36911

Update axe-core and axe-core/puppeteer dependencies to latest

---

package.json
packages/react-components/package.json
packages/react-components/testing/karma.conf.js
packages/storybook/.storybook/main.js
packages/storybook/package.json
packages/storybook/stories/RadioButtons.stories.jsx
yarn.lock

Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/36950
Guidance provided by https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#webpack-5
Resolution of build issue: https://github.com/storybookjs/storybook/issues/15336
Tested Storybook locally and running properly

36950 Storybook Upgrade Webpack 5

---

packages/core/package.json
packages/web-components/package.json
packages/web-components/src/components/va-accordion/va-accordion.css
packages/web-components/src/components/va-accordion/va-accordion.e2e.ts
packages/web-components/src/components/va-accordion/va-accordion.tsx

Reverts department-of-veterans-affairs/component-library#317

Revert "20488 Accordions Expand Collapse All"

---

README.md

https://update-branch-naming--60f9b557105290003b387cd5.chromatic.com

Update branch naming documentation

---

package.json
yarn.lock

https://39117-minimist-resolution--60f9b557105290003b387cd5.chromatic.com
Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/39117
Ran Storybook and yarn test and yarn build on Web Component and React Component packages and everything worked as expected

39117 Update Minimist Resolution

---

packages/react-components/package.json
packages/storybook/package.json
packages/web-components/package.json
yarn.lock

https://github.com/department-of-veterans-affairs/va.gov-team/issues/39750
Tested locally and all yarn install, yarn build, yarn test and yarn storybook commands work properly and storybook looks and works correctly

Bump Formation v7.0.1

---

packages/storybook/stories/va-pagination.stories.jsx

https://39969-pagination-documentation--60f9b557105290003b387cd5.chromatic.com
Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/39969
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/714

39969 Storybook Pagination Link Documentation

---

packages/storybook/stories/va-additional-info.stories.jsx

https://39862-additional-info--60f9b557105290003b387cd5.chromatic.com
Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/39862
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/715

39862 Additional Info SB Documentation

---

packages/storybook/stories/va-accordion.stories.jsx

https://39860-accordions-documentation--60f9b557105290003b387cd5.chromatic.com
Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/39860
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/718

39860 Accordion Documentation Update SB

---

packages/core/package.json
packages/web-components/package.json

Bump version patch to fix issue with text in docs repo

Bump version Patch 2.12.1

---

README.md

This PR adds bindings step in build process and adds a short description of the CLI that is now part of this monorepo.

Update README with bindings build step and cli description

---

packages/storybook/stories/va-process-list.stories.jsx
packages/storybook/stories/wc-helpers.jsx

https://40111-pl--60f9b557105290003b387cd5.chromatic.com
Part of https://github.com/department-of-veterans-affairs/va.gov-team/issues/40111
N/A

Add subtitle and link to DS for va-process-list

---

packages/storybook/stories/va-segmented-progress-bar.stories.jsx

https://update-segmented-href--60f9b557105290003b387cd5.chromatic.com
This updates the link to the new `Progress bar - Segmented` DS page

Fix va-segmented-progress-bar link to DS

---

packages/storybook/stories/ProgressButton.stories.jsx
packages/storybook/stories/buttons.stories.mdx
packages/storybook/stories/buttons.style.scss

https://39874-buttons--60f9b557105290003b387cd5.chromatic.com
Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/39874

Update stories for Button

---

packages/storybook/stories/va-alert.stories.jsx
packages/web-components/src/components/va-alert/va-alert.css

https://658-va-alert--60f9b557105290003b387cd5.chromatic.com
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/658 and partly closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/810

Update padding and border width for va-alert

---

packages/storybook/stories/events.js
packages/storybook/stories/va-checkbox.stories.jsx
packages/storybook/stories/va-number-input.stories.jsx
packages/storybook/stories/va-select.stories.jsx
packages/storybook/stories/va-text-input.stories.jsx
packages/storybook/stories/va-textarea.stories.jsx

https://38913-native-events-form--60f9b557105290003b387cd5.chromatic.com
Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/38913

38913 Storybook Native Events in Docs

---

packages/storybook/stories/additional-docs.js

https://884-segmented-progress--60f9b557105290003b387cd5.chromatic.com
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/884

Update segmented progress bar guidance link

---

packages/storybook/.storybook/style.scss
packages/storybook/stories/introduction.stories.mdx

https://41424-sb-intro-page--60f9b557105290003b387cd5.chromatic.com
Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/41425

41424 Storybook Introduction Page Links

---

packages/css-library/.gitignore
packages/css-library/config.json

https://1019-styledict-css--60f9b557105290003b387cd5.chromatic.com
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1019

Token library outputs CSS variables

---

packages/core/package.json
packages/storybook/stories/additional-docs.js
packages/storybook/stories/va-modal.stories.jsx
packages/storybook/stories/va-omb-info.stories.jsx
packages/web-components/package.json
packages/web-components/src/components.d.ts
packages/web-components/src/components/va-modal/test/va-modal.e2e.ts
packages/web-components/src/components/va-modal/va-modal.css
packages/web-components/src/components/va-modal/va-modal.tsx
packages/web-components/src/components/va-omb-info/test/va-omb-info.e2e.ts
packages/web-components/src/components/va-omb-info/va-omb-info.css
packages/web-components/src/components/va-omb-info/va-omb-info.tsx

https://983-omb-info--60f9b557105290003b387cd5.chromatic.com
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/983
E2E

Add va-omb-info web component

---

packages/core/package.json
packages/web-components/package.json
packages/web-components/src/components/va-modal/test/va-modal.e2e.ts
packages/web-components/src/components/va-modal/va-modal.css
packages/web-components/src/components/va-modal/va-modal.tsx

https://1113-modal-cypress--60f9b557105290003b387cd5.chromatic.com
Part of https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1113

Fix va-modal for Cypress

---

.github/PULL_REQUEST_TEMPLATE.md

https://jamigibbs-patch-1--60f9b557105290003b387cd5.chromatic.com
This will add a checklist for DST Engineers to follow when creating a pull request for the component-library.
Previewed markdown on github

Add PR configuration checklist to PULL_REQUEST_TEMPLATE.md

---

.github/PULL_REQUEST_TEMPLATE.md

https://pull-request-checklist-update--60f9b557105290003b387cd5.chromatic.com
This updates the component-library pull request template to include clarification about the Testing Done section as well reminding to link to related issues. Also grammar fixes.
Reviewed markdown locally

Adding additional checklist items to pull request template

---

packages/storybook/.storybook/preview.js
packages/storybook/.storybook/style.scss

https://1569-remove-storybook-preview-script--60f9b557105290003b387cd5.chromatic.com
---
Closes #[1569](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1569)
Storybook via desktop browser.

Removing Formation overrides from storybook

---

packages/core/package.json
packages/storybook/stories/va-need-help.stories.jsx
packages/web-components/package.json
packages/web-components/src/components/va-need-help/va-need-help.tsx

https://fix-need-help-1467--60f9b557105290003b387cd5.chromatic.com
---
Verified in storybook locally.

Fixes code example for need help component. [Amends #1467]

---

packages/core/package.json

https://Core-bump-to-15.1--60f9b557105290003b387cd5.chromatic.com
---

Bumping core for release

---

packages/design-system-dashboard-cli/src/codeowners.json

https://asteele-update-component-usage-codeowners--60f9b557105290003b387cd5.chromatic.com
---
Quick reassignment of a few apps to the facilities team.

Reassigning a few apps to facilities

---

packages/core/package.json

https://core-bump-to-16-2--60f9b557105290003b387cd5.chromatic.com
---
Core version bump for release

Core version bump to 16.2.0

---

packages/react-components/package.json
packages/storybook/package.json
packages/web-components/package.json
yarn.lock

https://1798-upgrade-formation--60f9b557105290003b387cd5.chromatic.com
- Upgrade formation version to ^7.0.8 in package.json
- Fixes a bug where buttons would sometimes overflow from their containers on mobile
- Github Issue: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1798
- Related fix in veteran-facing-service-tools: https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/936
- Manual testing
Before:
After:

Upgrade @department-of-veterans-affairs/formation version to ^7.0.8

---

packages/core/package.json

https://asteele-core-bump-to-16-4--60f9b557105290003b387cd5.chromatic.com
---
Core version bump while readying new release.

Core version bump to 16.4

---

packages/core/package.json

https://core-version-v17.0.1--60f9b557105290003b387cd5.chromatic.com
Making this a patch release because all of the merged PR's are patches:

Update core to v17.0.1 for release

---

packages/core/package.json

https://v20.0.0--60f9b557105290003b387cd5.chromatic.com
Bump core to 20.0.0

bump core version to 20.0.0

---

packages/core/package.json

Core version bump to 21.0.0 for release

Core version bump to 21.0.0

---

.github/CODEOWNERS

https://remove-mobile-team-workflows--60f9b557105290003b387cd5.chromatic.com
Until these workflows are ready, we'd like to remove them from this repository because every time a PR is opened, we are sent emails about them failing.
N/A
N/A

Remove empty mobile github workflows

---

packages/core/package.json

Bumps core to 21.0.2 for out of band release.

Bump core version to 21.0.2

---

packages/core/package.json

bump core version to 22.0.0

---

packages/core/package.json

https://mc-23.0.0-release--60f9b557105290003b387cd5.chromatic.com
bump core to 23

update to 23

---

packages/web-components/package.json
packages/web-components/src/components/va-date/va-date.tsx
packages/web-components/src/components/va-memorable-date/va-memorable-date.tsx
packages/web-components/src/utils/date-utils.spec.ts
packages/web-components/src/utils/date-utils.ts

https://rollback-memorable-date--60f9b557105290003b387cd5.chromatic.com
Rollback changes made in 2123-memorable-date-validation for conflicting with another memorable date change
Manual testing

Rollback memorable date

---

packages/core/package.json

https://core-version-v24.0.1--60f9b557105290003b387cd5.chromatic.com

Update core version to v24.0.1 for release

---

packages/core/package.json

https://core-version-v30.0.1--60f9b557105290003b387cd5.chromatic.com
---
Core version bump for release
N/A
N/A

core version bump for the release

---

packages/core/package.json

https://core-version-v31.0.0--60f9b557105290003b387cd5.chromatic.com
---
Core version bump for the release
N/A
N/A

update core version bump to v31.0.0

---

.github/workflows/publish-storybook.yml
packages/storybook/.storybook/main.js

https://1977-icon-changes-roll-back--60f9b557105290003b387cd5.chromatic.com
---
This PR reverts the changes made in an attempt to fix the `sprite.svg` path issue in the production environment.
Closes [<ticket>](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1977)
Initial PR: https://github.com/department-of-veterans-affairs/component-library/pull/919
N/A
N/A

Revert icon related changes

---

packages/core/package.json

https://mc-release-31.0.1--60f9b557105290003b387cd5.chromatic.com
---
update to core version

update core to 31.0.1

---

packages/core/package.json

https://core-version-v32.1.1--60f9b557105290003b387cd5.chromatic.com

update core version for release

---

packages/core/package.json

https://mc-release-33.0.0--60f9b557105290003b387cd5.chromatic.com
---
Updates core to v33.0.0 for release.

Update core version to v33.0.0 for release

---

.github/workflows/release.yml
.release-please-manifest.json
release-please-config.json

Configures  a test  of `release-please`
should track  changes in `rm-relese-please-exp`

alternate release please install --test branch only

---

.github/workflows/release.yml

Updating the target branch in the release-please experiment.

Update target branch of release-please

---

.github/workflows/release.yml

Fixes token name/ resolves CI failure

fix token name

---

packages/web-components/src/components/va-alert/va-alert.scss

https://2339-alert-info-color-fix--60f9b557105290003b387cd5.chromatic.com
---
This PR fixes the colors for Alert component for both mobile and desktop views.
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2339
N/A
N/A
N/A
N/A
N/A

Alert V3 backround and boder color fix

---

packages/core/package.json

https://core-version-v34.2.0--60f9b557105290003b387cd5.chromatic.com
Update core package version for release 
N/A

update core version to v34.2.0 for release

---

packages/core/package.json

https://2469-bump-core--60f9b557105290003b387cd5.chromatic.com
This PR bumps core as part of a release to support [this bug fix](https://github.com/department-of-veterans-affairs/component-library/pull/1049)
n/a - just a core bump

bump core for release

---

packages/core/package.json

Bumping core version for release

Bump core version for release

---

packages/core/package.json

https://version-bump-to-37-1--65a6e2ed2314f7b8f98609d8.chromatic.com
---
Version bump to 37.1.0 for this week's release.

Version bump to 37.1.0

---

packages/css-library/dist/tokens/css/variables.css
packages/css-library/dist/tokens/scss/variables.scss
packages/css-library/package.json
packages/web-components/package.json
packages/web-components/src/components/va-memorable-date/va-memorable-date.scss
packages/web-components/src/components/va-pagination/va-pagination.scss
yarn.lock

https://2512-upgrade-uswds--65a6e2ed2314f7b8f98609d8.chromatic.com
- Upgrade USWDS package from 3.5.0 to 3.7.1
- Clean up code in va-pagination.scss that is no longer needed due to the upgrade
- Added override in va-memorable-date.scss to disable wrapping
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2512
- va-button: disabled font color is darker
- va-checkbox/va-radio: disabled label font color is darker
- va-memorable-date: .usa-memorable-date added css property `flex-wrap: wrap` which caused the component to always wrap when the month field was a select field. An override was added to prevent this.
- [ x] Component …

Upgrade USWDS@3.7.1

---

packages/core/package.json

https://core-release-v37.2.0--65a6e2ed2314f7b8f98609d8.chromatic.com

Update core for release v37.2.0

---

packages/storybook/stories/va-header-minimal.stories.jsx
packages/web-components/src/components.d.ts
packages/web-components/src/components/va-header-minimal/test/va-header-minimal.spec.tsx
packages/web-components/src/components/va-header-minimal/va-header-minimal.scss
packages/web-components/src/components/va-header-minimal/va-header-minimal.tsx

https://minimal-header-optional-headings--65a6e2ed2314f7b8f98609d8.chromatic.com
---
Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/70359
- N/A - no visual change. 
**Before:**
**After:**

Minimal header optional headings

---

packages/core/package.json

https://bump-core-38.0.2--65a6e2ed2314f7b8f98609d8.chromatic.com
---
This PR bumps core to facilitate publishing component-library.

Bump core to 38.0.2

---

.github/workflows/chromatic-link.yml
.github/workflows/chromatic.yml

Skips publishing to chromatic if the user is Dependabot

skip chromatic if user is depdendabot

---

.github/workflows/chromatic.yml
component-apps-and-owners-2024-02-05.csv

Skip chromatic build on dependabot branches instead of on user

skip chromatic on dependabot branches

---

packages/core/package.json

https://v39.0.1-release--65a6e2ed2314f7b8f98609d8.chromatic.com
Bump core for new release

Bump core to 39.0.1

---

packages/core/package.json

https://9999-v40-version-bump--65a6e2ed2314f7b8f98609d8.chromatic.com
---
Version bump in core

Major version bump to v40

---

packages/core/package.json

update core to 41.1.0 for minor release

update core to 41.1.0

---

packages/core/package.json

https://bump-core-42.1.0--65a6e2ed2314f7b8f98609d8.chromatic.com
---
This PR bumps core to 42.1.0 in preparation for a release.

bump core to 42.1.0

---

.github/workflows/publish-storybook.yml

https://publish-storybook-workflow-tweak--65a6e2ed2314f7b8f98609d8.chromatic.com
Update build command in publish storybook action so that build uses folder that can be uploaded to S3.

update build command

---

packages/web-components/package.json

update web component to 10.0.1

---

packages/design-system-dashboard-cli/src/create-spreadsheets.js

https://2932-update-usage-with-icons--65a6e2ed2314f7b8f98609d8.chromatic.com
---
Closes [#2932](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2932)

Updating usage script to start counting instances of Font Awesome icons

---

packages/web-components/src/components/va-file-input/va-file-input.tsx

https://db-update-modal-title--65a6e2ed2314f7b8f98609d8.chromatic.com
---
Updates the delete confirmation modal's title based on CAIA feedback.

va-file-input: Update modal title

---

packages/core/package.json

Updates core package.json for major release

update core to 43.0.0

---

packages/web-components/package.json
packages/web-components/src/components/va-file-input-multiple/va-file-input-multiple.tsx
packages/web-components/src/components/va-file-input/va-file-input.scss
packages/web-components/src/components/va-file-input/va-file-input.tsx
packages/web-components/src/components/va-modal/test/va-modal.e2e.ts
packages/web-components/src/components/va-modal/va-modal.tsx

https://mult-file-accessibility--65a6e2ed2314f7b8f98609d8.chromatic.com
---
Closes [va-file-input-multiple Accessibility fixes #2988](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2988)

va-file-input-multiple accessibility fixes

---

packages/core/package.json
packages/web-components/package.json

https://version-bump-7-30-24--65a6e2ed2314f7b8f98609d8.chromatic.com
---
Version bumps in preparation for next release.
N/A

Version bumps for next release

---

packages/core/package.json
packages/web-components/package.json

Description
Version bump for core and web-component for release.

version bump for release

---

packages/core/package.json
packages/css-library/package.json
packages/web-components/package.json

https://mc-46--65a6e2ed2314f7b8f98609d8.chromatic.com
---
Bumps version numbers for release

bump version numbers

---

packages/storybook/stories/va-checkbox-group-uswds.stories.jsx
packages/storybook/stories/va-radio-uswds.stories.jsx

https://db-remove-disabled-examples-3191--65a6e2ed2314f7b8f98609d8.chromatic.com
---
Closes [#3191](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3191)

Remove props from disabled checkbox/radio stories

---

packages/web-components/src/components/va-checkbox/va-checkbox.scss
packages/web-components/src/components/va-radio-option/va-radio-option.scss
packages/web-components/src/components/va-radio/va-radio.scss

https://2508-max-width-checks-radios--65a6e2ed2314f7b8f98609d8.chromatic.com
---
Closes [#2508](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2508)
N/A

va-checkbox and va-radio-option: Increasing the max-width to 68ex

---

packages/core/package.json
packages/css-library/package.json
packages/web-components/package.json
yarn.lock

https://mc-comp-lib-47.0.0--65a6e2ed2314f7b8f98609d8.chromatic.com
---
Bumps package versions for release.

update version numbers

---

.github/workflows/chromatic.yml
packages/storybook/stories/va-link.stories.jsx
packages/web-components/package.json

https://3096-va-link-router-example--65a6e2ed2314f7b8f98609d8.chromatic.com/?path=/docs/components-va-link--docs#with-router-link-support
Originally we were going to add a custom event to emit when a link needed to be a "router" link similar to [how it was done for va-breadcrumbs](https://github.com/department-of-veterans-affairs/component-library/blob/a3ab7acfd96848ac3f03d477d9a7479bd39f7efd/packages/web-components/src/components/va-breadcrumbs/va-breadcrumbs.tsx#L88-L97). This makes sense to do for the breadcrumbs component because we are managing an unknown number of different links with potentially different types of behavior.
But the `va-link` component is simpler. We have access to the native `click` event for the single link so adding router functionality can be done using that …

va-link: add router link Storybook example

---

packages/web-components/package.json
packages/web-components/src/components/va-process-list/test/va-process-list-item.e2e.ts
packages/web-components/src/components/va-process-list/va-process-list-item.scss
packages/web-components/src/components/va-process-list/va-process-list-item.tsx
packages/web-components/stencil.config.ts
yarn.lock

https://3274-process-list-accessibility--65a6e2ed2314f7b8f98609d8.chromatic.com
The status variant of the process list has an accessibility violation because it uses color to convey meaning (Completed, Active, Pending). This PR adds eyebrow text to fix this issue.
Closes [3274](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3274)
- [ x] New components are covered by e2e tests; updates to existing components are …

va-process-list-item: Add text to describe status

---

packages/core/package.json
packages/css-library/package.json
packages/web-components/package.json
yarn.lock

https://kp-48.0.2--65a6e2ed2314f7b8f98609d8.chromatic.com
- css-library@0.15.0 (major)
- web-components@16.0.2 (minor)
- core@48.0.2 (minor)

Update version numbers for release and publish

---

packages/core/package.json
packages/css-library/package.json
packages/web-components/package.json
yarn.lock

Update versions for release 48.2.0

Update versions for release 48.2.0

---

packages/core/package.json
packages/web-components/package.json

https://12-19-24-release-version-bumps--65a6e2ed2314f7b8f98609d8.chromatic.com
---
Version bumps for next release.

12-19-24 Core and Web-C Version Bumps

---

packages/core/package.json
packages/css-library/package.json
packages/web-components/package.json
yarn.lock

https://mc-release-48.4.0--65a6e2ed2314f7b8f98609d8.chromatic.com
---
update versions for release

update versions for release

---

packages/core/package.json
packages/web-components/package.json

https://mc-49.1.1--65a6e2ed2314f7b8f98609d8.chromatic.com
---

bump versions

---

.github/PULL_REQUEST_TEMPLATE.md

Remove reference to Zenhub in PR template

PR Template: Remove zenhub reference

---

packages/core/package.json
packages/css-library/package.json
packages/web-components/package.json
yarn.lock

https://core-release-v49.2.0--65a6e2ed2314f7b8f98609d8.chromatic.com

update package versions for release

---

packages/web-components/src/components/va-table/va-table-inner/va-table-inner.scss

https://9999-patch-to-table-inner--65a6e2ed2314f7b8f98609d8.chromatic.com
---
Quick patch to media-query in va-table-inner to max use of --mobile-lg token
N/A

va-table-inner: patch to media query

---

packages/core/package.json
packages/css-library/package.json
packages/web-components/package.json
yarn.lock

https://version-bump-2-26-25--65a6e2ed2314f7b8f98609d8.chromatic.com
---
Version bumps in preparation for next release.

Version Bumps for 2-26-25

---

packages/storybook/.storybook/main.js
packages/storybook/.storybook/preview.js
packages/storybook/.storybook/style.scss
packages/storybook/package.json
yarn.lock

https://3717-storybook-dark-mode--65a6e2ed2314f7b8f98609d8.chromatic.com
---
Closes [#3717](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3717)

Storybook: Dark mode support

---

packages/web-components/src/components/va-combo-box/test/va-combo-box.e2e.ts
packages/web-components/src/components/va-combo-box/va-combo-box-library.js
packages/web-components/src/components/va-combo-box/va-combo-box.scss

https://mhv-64592-accurately-typed-text--65a6e2ed2314f7b8f98609d8.chromatic.com
---
> Design specs:  Typed text is accurate
> 
> Note:  This was documented in the Design Specs figma file:  https://www.figma.com/design/uddjxccqvUyz5FSg1aD5wi/Z---Triage-Group-Flows?node-id=2095-166192&t=3fpB8MT3hSIxqmO7-4 
> 
> Desired functionality:
> Given: a user types in exactly the text of a dropdown item
> When: they click outside of the component
> Then: that dropdown item is selected
> 
> **UCD Summary of Design …

va-combo-box: user typed matches auto-select

---

packages/storybook/stories/va-process-list-uswds.stories.tsx

https://3902-process-list-story-fixes--65a6e2ed2314f7b8f98609d8.chromatic.com
---
Closes [#3902](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3902)

Storybook: default va-process-list-item now "controllable"

---

packages/core/package.json
packages/css-library/package.json
packages/web-components/package.json
yarn.lock

https://mc-v50--65a6e2ed2314f7b8f98609d8.chromatic.com
---
bumps versions of packages

update package versions

---

packages/storybook/stories/va-language-toggle.stories.tsx

https://db-add-2-language-variations-3952--65a6e2ed2314f7b8f98609d8.chromatic.com
Closes [#3952](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3952)

va-language-toggle: Adds two language variation story

---

packages/storybook/stories/va-file-input-uswds.stories.tsx

https://db-update-hint-text-staging-review-3079--65a6e2ed2314f7b8f98609d8.chromatic.com
Closes [#3079](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3079)

va-file-input: Updates hint text within stories

---

packages/core/package.json
packages/web-components/package.json

https://vrelease-v5022--65a6e2ed2314f7b8f98609d8.chromatic.com

Updating versions for release with patch bump v50.2.2

---

.github/workflows/node.js.yml
README.md
setup.sh

contribution by @amyleadem
- https://github.com/department-of-veterans-affairs/component-library/pull/1606
---------
https://community-branch--65a6e2ed2314f7b8f98609d8.chromatic.com
When running `npm run dev` (or `yarn install && yarn dev`) on a fresh clone of the repo, I ran into a missing module failure, which prevented Storybook from running successfully:
```
ERROR in ./stories/va-link.stories.tsx 207:0-95
Module not found: Error: Can't resolve '@department-of-veterans-affairs/component-library/dist/react-bindings' in '/Users/amyleadem/VA/forked-component-library/component-library/packages/storybook/stories'
@ ././ lazy ^\.\/.*$ include: (?:(src%7Cstories)(?:\/(?%21\.)(?:(?:(?%21(?:^%7C\/)\.).)*?)\/%7C\/%7C$)(?%21\.)(?=.)[^/]*?\.stories\.(js%7Cjsx%7Cts%7Ctsx%7Cmdx))$ chunkName: …
```

Setup script - Add react-component build to setup.sh (#1606)

---

packages/web-components/src/components/va-input-telephone/va-input-telephone.tsx

https://4222-input-telephone-error-a11y--65a6e2ed2314f7b8f98609d8.chromatic.com
**Delayed the phone number input validation until focus is moved out of the element.** This allows the user to only enter the error state until after they enter content.
This PR removes the `validateContact()` call from `validateCountry()` to make them distinct validation processes. 
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/4222
**Approval Groups**
- Accessibility: …

va-input-telephone: Delay phone number validation until blur

---

packages/core/package.json
packages/css-library/package.json
packages/web-components/package.json

https://ver-51.0.0--65a6e2ed2314f7b8f98609d8.chromatic.com
This PR bumps the semver to 51.0.0 in preparation for release
- Design: [platform-design-system-designer](https://github.com/orgs/department-of-veterans-affairs/teams/platform-design-system-designers)
Use the QA checklists below as guides, not …

bump version to 51.0.0

---

packages/web-components/src/components/va-file-input/va-file-input.tsx

https://fix-file-input-delete-modal-text-3087--65a6e2ed2314f7b8f98609d8.chromatic.com
- Fix va-file-input delete modal text to use 'delete' and 'file' instead of 'remove' and 'document'
Closes [#3087](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3087)
- Design: …

va-file-input: Updates modal text

---

README.md

https://readme-update-install-docs--65a6e2ed2314f7b8f98609d8.chromatic.com
We received some feedback that it wasn't entirely clear that the instructions in the README are for contributors to the component-library and not necessarily for consumers of it.
This will add a section at the top that directs consumers to our install guide on the documentation site.
- Accessibility: [platform-design-system-a11y](https://github.com/orgs/department …

Add a link to consumer install instructions in the component-library README

---

packages/web-components/src/components.d.ts
packages/web-components/src/components/va-file-input/va-file-input.tsx

https://4472-file-encryption-docs--65a6e2ed2314f7b8f98609d8.chromatic.com
This PR adds additional documentation to the encrypted prop explaining that the component does not perform encryption checking. It also adds a link to a step-by-step guide on how to implement encryption checking in vets-website.
Related PR to add similar documentation on design.va.gov: 
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/4505
Closes [4472](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/4472)
additional documentation shows up in storybook
Add approval …

va-file-input: add more docs to encrypted prop

---

packages/core/README.md
packages/core/package.json
packages/integration-examples/vite-react-typescript/yarn.lock
packages/storybook/package.json
packages/web-components/package.json
packages/web-components/src/components.d.ts
packages/web-components/src/components/va-file-input-multiple/va-file-input-multiple.tsx
packages/web-components/src/components/va-file-input/va-file-input.tsx
packages/web-components/src/index.html
yarn.lock

https://4500-formation-peerDependencies--65a6e2ed2314f7b8f98609d8.chromatic.com
web-components and core both listed formation as a peer dependency. Neither of these packages use formation anymore. This PR removes those peer dependencies and updates any documentation for use of formation.
Storybook also had a reference to node-sass which is deprecated and no longer used. Due to build errors, this package had to be removed also.
Closes [4500](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/4500)
- Ensure that storybook still loads and components do not have any regressions
**Approval …

Web-Components, Core: Remove formation peer dependencies, update docs

---

.github/workflows/weekly-reports.yml

https://humancompanion-usds-patch-1--65a6e2ed2314f7b8f98609d8.chromatic.com
Caching a yarn.lock file that doesn't exist did not work.
- Design: [platform-design-system-designer](https://github.com/orgs/department-of-veterans-affairs/teams/platform-design-system-designers)
Use the QA checklists below as guides, not …

[Metrics dashboard] Update weekly-reports.yml

---

packages/core/package.json
packages/storybook/package.json
packages/web-components/package.json
yarn.lock

https://4499-react-19--65a6e2ed2314f7b8f98609d8.chromatic.com
Update peer dependency in Core and dependency in storybook to use react v19. 
Update react-dom to use v19 in web-components
Ignore react version in storybook, this reflects what is on vets-website
Closes [4499](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/4499)
- Storybook and web-components render without regression
- …

core, web-components: upgrade react to v19

---

packages/storybook/stories/va-telephone-input.stories.tsx

https://storybook-va-telephone-input--65a6e2ed2314f7b8f98609d8.chromatic.com
The display name for the `va-telephone-input` component was displaying as `VaLanguageToggle` in a Storybook example using the React binding so this PR will update that to `VaTelephoneInput`.
N/A
- Design: …

Display the correct React binding name for va-telephone-input in Storybook

---

packages/web-components/src/components/va-sidenav/va-sidenav.tsx

https://va-sidenav-mobile-breakpoint--65a6e2ed2314f7b8f98609d8.chromatic.com
VA.gov Profile implements a collapsed side navigation starting at 767px. This change updates VaSidenav to display the non-desktop render starting at 767px instead of 640px.
VaSidenav at 767px (before PR changes):
This is what's currently on VA.gov at 767px:
- Accessibility: [platform-design-system-a11y](https://github.com/orgs/department-of-veterans-affairs/team …

va-sidenav: use medium-screen breakpoint for mobile view

---

packages/core/package.json
packages/css-library/package.json
packages/web-components/package.json

https://v52.1.0--65a6e2ed2314f7b8f98609d8.chromatic.com
This PR prepares the repo for next release.
- Design: [platform-design-system-designer](https://github.com/orgs/department-of-veterans-affairs/teams/platform-design-system-designers)
Use the QA checklists below as guides, not rules. Not all …

bump versions for 52.1.0 release

---

packages/storybook/stories/va-checkbox-group-uswds.stories.tsx

https://checkbox-storybook-example-spelling--65a6e2ed2314f7b8f98609d8.chromatic.com
There are a couple of places that `Sojourner` is spelled incorrectly. 
Thank you @amyleadem for spotting this!
- Design: [platform-design-system-designer](https://github.com/orgs/department-of-veterans-affairs/teams/plat …

Fix spelling of Sojourner in Storybook

---

packages/web-components/src/components/va-button-segmented/va-button-segmented.tsx

https://4805-segmented-button-analytics--65a6e2ed2314f7b8f98609d8.chromatic.com
This PR updates the `details` object that is passed to the analytics event in `<va-button-segmented>`. The updates were made at [the request](https://dsva.slack.com/archives/CBU0KDSB1/p1758031158431369) of Jamie Stutt of the Platform/Analytics & Insights team.
Does not close the ticket, but is part of work required for https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/4805.
Additional link to conversation with Jamie Stutt regarding this change: https://dsva.slack.com/archives/CBU0KDSB1/p1758031158431369 …

va-button-segmented: Update details payload for analytics event
