testing/tests.js

This fixes the `chokidar` watcher error as well as the failing tests we were seeing.
Just don't ask me _why._ I find this `karma` setup positively baffling. :see_no_evil:

Only find tests in src/

---

.github/PULL_REQUEST_TEMPLATE.md

Remove items from PR template that aren't particularly useful for `component-library`. This template was originally copied from `vets-website`.

Remove non-helpful done criteria

---

README.md

Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/19062
Adds a link to the README which will open an issue in the `vets-design-system-documentation` repo, since issue tracking has been disabled in `component-library`.

Link to issue template & fix storybook section

---

package.json
src/components/Date/Date.jsx
src/components/Date/Date.unit.spec.jsx
src/components/MonthYear/MonthYear.jsx
src/components/MonthYear/MonthYear.unit.spec.jsx
src/helpers/validations.js

In the `Date` and `MonthYear` components do not show a validation error when an out-of-range year is input. This is a launchblocker accessibility issue (see related issue). This PR shows a year-specific error message when an out-of-range year is input - see the screenshot for an example.
Related: https://github.com/department-of-veterans-affairs/va.gov-team/issues/18578
Updated unit tests

Show out of range year error messages

---

package.json
src/components/Date/Date.jsx
src/components/Date/Date.unit.spec.jsx
src/components/MonthYear/MonthYear.jsx
src/components/MonthYear/MonthYear.unit.spec.jsx

To improve accessibility, the `Date` component should be wrapped in a `<fieldset>` and include a `<legend>`.
Related: https://github.com/department-of-veterans-affairs/va.gov-team/issues/15364
Unit tests updated
N/A - appearance is the same, but did require some classes to make it the same

Wrap Date in a fieldset

---

package.json
src/components/LoadingIndicator/LoadingIndicator.jsx
src/components/ProgressBar/ProgressBar.jsx
src/components/SegmentedProgressBar/SegmentedProgressBar.jsx

This PR adds default `aria-label` values to the `ProgressBar`, `SegmentedProgressBar`, and `LoadingIndicator`. This fixes axe failures caused by an `aria-label` value not being set for these components.
This is the simplest solution to the axe failures, but I'm not sure if a default, generic name is sufficient for accessibility standards. @1Copenut
Closes two tickets: [`ProgressBar` axe failure](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/357) and [`LoadingIndicator` axe failure](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/366).
- No failures observed when running the axe browser plugin on pages that use these components.
- Ran the entire Cypress test suite locally using these changes and the …

ProgressBar and LoadingIndicator axe fixes

---

src/components/Date/Date.jsx

When the date widget has an error, the left-sided red border doesn't extend up into the `legend`
Including the `usa-input-error` class in the `fieldset`
Design spec: https://design.va.gov/patterns/form-feedback
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/394
Visual
Source page: https://staging.va.gov/disability/file-disability-claim-form-21-526ez/introduction
\* Note: I'm not sure how to get that last bit of border to be above the text.

Add error class to Date fieldset

---

package.json
src/components/Telephone/Telephone.jsx
src/components/Telephone/Telephone.mdx
src/components/Telephone/Telephone.unit.spec.jsx

Three-digit phone numbers, e.g. `911` and `711` do not need specific labels added by the Telephone component, nor should they be preceeded by a `+1` as they are with other numbers.
In this PR:
- The `TTY` within the `711` aria-label is repetitive and has been removed.
- For all 3-digit numbers, the `+1` in the number causes the phone call to not complete as dialed
This PR combines the work of the two tickets because removing the TTY label and adding a new unit test would include a `+1` in the number, and it was just as easy to combine the work.
Closes tickets
- https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/338 (remove `+1`)
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/18274 (remove `tty`)
Unit tests updated
N/A

Update to 3-digit telephone numbers

---

package.json
src/components/MaintenanceBanner/MaintenanceBanner.jsx
src/components/MaintenanceBanner/MaintenanceBanner.mdx
src/components/MaintenanceBanner/MaintenanceBanner.stories.jsx
src/components/MaintenanceBanner/MaintenanceBanner.unit.spec.jsx
yarn.lock

Related to https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/198
This updates the `MaintenanceBanner` stories with some new content, and also puts a comma after the formatted day. It also replaces `moment` with `date-fns` _only in `MaintenanceBanner`_. This allows us to properly format the `a.m.`/`p.m.` according to [our own guidelines](https://design.va.gov/content-style-guide/dates-and-numbers#times-and-time-zones).
I also found a bug that _might_ be related to daylight savings time. The displayed time was an hour off from the time that was passed in as a prop. This has been fixed.
- Local Storybook
- Unit testing

Update date display & storybook args for banner

---

.eslintrc.json
package.json
yarn.lock

From:
https://dsva.slack.com/archives/C01DBGX4P45/p1613414971056900
We need to add mocha to eslint to allow the global vars it uses in tests.
I'm not super familiar with this so please have at it...

Add mocha to eslint

---

tsconfig.json

This is related to #43 and #48, but wasn't caught since they were never tested together. #43 added a file in a new `src/testing` directory meant for holding helpers for testing. #48 changed how the dependencies were organized so that a `npm install --only=prod` would lead to a successful build by consumers.
By adding the `test-helpers.jsx` file which imports from `axe-core`, we ended up in a situation where we were trying to include that file as part of the build but it would fail, since `axe-core` wasn't installed. This will prevent that.
The problem was noticed locally when trying to upgrade the `web-components` dependency.
Testing on the PR for `storybook-wc`: https://github.com/department-of-veterans-affairs/component-library/pull/31/commits/faa5c3cae5d4c5c6dbf50ed694c4ce0eca08546b

Exclude files in testing folder from build

---

package.json
src/components.d.ts
src/components/va-accordion/va-accordion-item.css
src/components/va-accordion/va-accordion-item.e2e.ts
src/components/va-accordion/va-accordion-item.tsx
src/components/va-accordion/va-accordion.e2e.ts
src/components/va-accordion/va-accordion.tsx

Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/20479
Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/20485
The staging review for the accordion web component found 2 a11y issues. This addresses them by:
- Setting the `<button>` to `display: block`
- Wrapping the button in a header that defaults to an `<h2>`
- A `level` prop can be used to adjust the header level from 1 to 6
- Local e2e tests
- Storybook validation
This is from [another PR](https://github.com/department-of-veterans-affairs/component-library/pull/31/commits/51bad68f30cf09c981ea46bc835b915639d57f03):

Fix accordion after staging review

---

src/helpers/options-for-select.js

Use full month names inside the Date & MonthYear components to remove inconsistent screenreader interpretation of the abbreviations.
Related:
- https://github.com/department-of-veterans-affairs/component-library/pull/16#discussion_r568320847
- https://github.com/department-of-veterans-affairs/vets-website/pull/15935 (Form system date widget update)
Checked results in storybook instance
<details><summary>Date</summary>
<details><summary>Month/Year</summary>

Add full month names to date select

---

package.json
src/components/va-accordion/va-accordion-item.css

Related to #53. This PR is [this CSS](https://github.com/department-of-veterans-affairs/component-library/commit/400c2541ed8dc5e1e433ceecc07ccaf9c6135a3a#diff-f7e0ba5886671b1b6e4a8e1e9c98a76a3f2aac69b66b4c3f5fe4f827fcf60d23R38-R40) applied when the button has the `:hover` pseudoselector as well.
Local testing in IE11
Before, with the visual bug:
After, with the hover bug fixed:

Apply same CSS fix to :hover state

---

package.json
src/components/Modal/Modal.jsx
src/components/Modal/Modal.stories.jsx
src/components/Modal/Modal.unit.spec.jsx
yarn.lock

Closes [18727](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/18727)
Refactored the modal component to use react-focus-on in order to solve memory leak issue in Storybook.
Added buttons to open modals on the Storybook default page so that the user can scroll on the page (open modals disable page scrolling).
Increased size of iframe windows for modals on the Storybook default page so that the user can use the close button to close the modals.
All tests are passing.
All scenarios in Storybook are working and the memory leak issue is no longer present
**Need to find a way to test with existing modals in vets-website**
From Storybook
From http://localhost:3001/gi-bill-comparison-tool/profile/149A1405
(linked vets-website to …

refactor: use react-focus-on to manage focus trap for modals

---

package.json
src/components/PromoBanner/PromoBanner.jsx

Sorry - forgot to add the standard disable bool to [this PR](https://github.com/department-of-veterans-affairs/component-library/pull/60). :roll_eyes:

Add disableAnalytics flag to PromoBanner analytics

---

package.json
stories/action-link.stories.mdx
yarn.lock

Along with this PR in veteran-facing-services-tools, closes https://app.zenhub.com/workspaces/vsp-design-system-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/va.gov-team/22151
Visual testing using the `feat/22151--white-action-link` branch on [veteran-facing-services-tools](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/602)

Add white action link to storybook

---

package.json
stories/va-accordion.stories.jsx
yarn.lock

Closes https://app.zenhub.com/workspaces/vsp-design-system-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/412
Visual in storybook

add optional accordion subheader to storybook

---

package.json
src/components/AlertBox/AlertBox.unit.spec.jsx
src/components/Breadcrumbs/Breadcrumbs.unit.spec.jsx
src/components/LoadingIndicator/LoadingIndicator.unit.spec.jsx
src/components/Modal/Modal.unit.spec.jsx
src/components/ProgressBar/ProgressBar.unit.spec.jsx
src/components/PromoBanner/PromoBanner.unit.spec.jsx
src/components/SegmentedProgressBar/SegmentedProgressBar.unit.spec.jsx
src/helpers/analytics.js

For: https://github.com/department-of-veterans-affairs/va.gov-team/issues/22168
Analytics and Insights would like the component-library version to be included in the analytics event.
I also fixed the modal tests to match the new flavor.

Add package version number to analytics

---

package.json
src/components/va-accordion/va-accordion-item.css

@rtwell pointed out some spacing weirdness with the `<va-accordion>` component with a subheader, so this aims to fix it.
Related to https://github.com/department-of-veterans-affairs/component-library/pull/73

Fix the spacing around the subheader

---

package.json
yarn.lock

Storybook update for the changes in #82 
The Subheaders story for `<va-accordion>` now has improved spacing

Update web-components dependency

---

stories/address-block.stories.mdx

Adds a `<Story>` to the address block so design.va.gov/components/address-block can point to it in the iframe. Doing so will remove the unsightly canvas box on that page.
Storybook :eyes: 
**Storybook**
**design.va.gov: Before**
**design.va.gov: After**

Make the address block a story

---

package.json
src/components/RadioButtons/RadioButtons.jsx

@cvalarida - Some issues with the new RadioButton analytics snuck by me.  I published and panic unpublished (sorry).
The issue is with test like this:
https://github.com/department-of-veterans-affairs/vets-website/blob/0c29a0b4dac10e7b2876d7314c19aedf25c2830c/src/applications/edu-benefits/tests/components/EducationWizard.unit.spec.jsx
```js
function answerQuestion(tree, name, value) {
getQuestion(tree, name).simulate('change', { target: { value } });
}
```
When `target` is set like this, our `target.parentElement` value is undefined...
```
domEvent.target:                { value: 'yes' }
domEvent.target.parentElement:  undefined
```
...and the label querySelector fails.
Any ideas on how to address this?  Should we...
1. Optional Chain the selector …

Issue with RadioButtons tests on vets-website

---

stories/action-link.stories.mdx

Like it says on the tin, it uses `<Story>` to provide multiple stories. This is so the iframes on design.va.gov/components/action-links can link to one story at a time.

Split the action links up into stories

---

stories/process-list.stories.mdx
stories/sidenav.stories.mdx

This is for a PR for the design site which will use a Storybook iframe for the sidenav and process list interactive "components": https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/458
Wrap the following components in a `<Story>` tag:
- Process list
- Sidenav 

Wrap sidenav in a story so we can use the iframe

---

src/components/CheckboxGroup/CheckboxGroup.stories.jsx
stories/featured-content.stories.mdx
stories/horizontal-rules.stories.mdx
stories/labels.stories.mdx

Add some more `<Story>` wrappers so we can get iframes.
This should be merged before: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/464
This PR:
- simplifies the default story for `CheckboxGroup>` for documentation purposes
- breaks the all-in-one appproach up into multiple stories
- wraps featured-content in a `<Story>` so we get an iframe
- wraps horizontal-rule in a `<Story>` so we get an iframe
- wraps labels in a `<Story>` so we get an iframe

Add more storybook iframes

---

stories/buttons.stories.mdx

Like it says on the tin, I
- Removed the designer-facing documentation
- Moved the stories under the `Components` sub-section
- Added `<Story>`s for use in iframes on design.va.gov

Remove designer documentation & add stories

---

package.json
src/components/va-accordion/va-accordion-item.css
src/components/va-accordion/va-accordion.css
src/global/variables.css

Addresses the issue mentioned by @rtwell: https://dsva.slack.com/archives/G01BJ3ESXL4/p1620912808066400

Accordion color fix

---

package.json
yarn.lock

Do not merge until https://github.com/department-of-veterans-affairs/component-library/pull/94 is merged and there is a release.
This updates storybook to show the accordion web component with the correct color.

Use branch with color fix

---

package.json
src/components/LoadingIndicator/LoadingIndicator.jsx
src/components/LoadingIndicator/LoadingIndicator.unit.spec.jsx
src/components/ProgressBar/ProgressBar.jsx
src/components/ProgressBar/ProgressBar.unit.spec.jsx
src/components/SegmentedProgressBar/SegmentedProgressBar.jsx
src/components/SegmentedProgressBar/SegmentedProgressBar.unit.spec.jsx

For: https://github.com/department-of-veterans-affairs/va.gov-team/issues/24499
Our event counts on ProgressBar, SegmentedProgressBar, and LoadingIndicator are waaaaay higher than expected.  We will need to make these opt-in to avoid hitting our monthly GA quota.

Change ProgressBar, SegmentedProgressBar, and LoadingIndicator analytics to opt-in

---

src/components/DropDownPanel/DropDownPanel.stories.jsx

The `Show code` button on the story for `<DropDownPanel>` is a bit misleading. It doesn't show the actual function for `clickHandler`, and the `isOpen` prop is ommited entirely (see screenshots). This PR removes the template/bind pattern that was apparently causing this. Solution is based on [this storybook issue comment](https://github.com/storybookjs/storybook/issues/11542#issuecomment-665193303)
Additional context in [a slack thread](https://dsva.slack.com/archives/CBU0KDSB1/p1621271386492300?thread_ts=1621268979.486700&cid=CBU0KDSB1).

Remove the Template pattern

---

package.json
src/components/TextInput/TextInput.jsx
src/components/TextInput/TextInput.unit.spec.jsx
yarn.lock

Addresses the need for aria-describedby for TextInput.
[Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/23616)
[Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/23222)
Manual Storybook With axe
Unit Test added
Only ariaDescribedBy:
Both error and ariaDescribedBy:
No error or ariaDescribedBy:
[Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/23616)
[Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/23222)

feat(TextInput): Add new ariaDescribedBy prop

---

package.json
src/components/Checkbox/Checkbox.unit.spec.jsx
src/components/CheckboxGroup/CheckboxGroup.unit.spec.jsx
src/components/RadioButtons/RadioButtons.unit.spec.jsx
src/components/Select/Select.unit.spec.jsx
src/components/TextArea/TextArea.unit.spec.jsx

Correct me if I'm wrong, but I should be unmounting these components even if they are shallow render.

Unmount components in analytics tests

---

src/components/RadioButtons/RadioButtons.jsx
src/components/RadioButtons/RadioButtons.mdx
src/components/RadioButtons/RadioButtons.stories.jsx
src/components/RadioButtons/RadioButtons.unit.spec.jsx

This PR adds an `aria-describedby` attribute to selected radio buttons to allow screenreaders to target content related to the selected choice. Only the selected option will include an `aria-describedby` label (see screenshot).
Related:
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/22569
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/22612
Updated unit tests
<details><summary><code>aria-describedby</code> with ID not in DOM</summary>

Add aria-describedby to RadioButtons

---

package.json
src/components/Date/Date.jsx
src/components/Date/Date.mdx
src/components/Date/Date.stories.jsx
src/components/Date/Date.unit.spec.jsx
src/components/NumberInput/NumberInput.jsx
src/components/NumberInput/NumberInput.mdx
src/components/NumberInput/NumberInput.stories.jsx
src/components/NumberInput/NumberInput.unit.spec.jsx
src/components/Select/Select.jsx
src/components/Select/Select.mdx
src/components/Select/Select.stories.jsx
src/components/Select/Select.unit.spec.jsx

This PR adds an `aria-describedby` attribute to `Date`, `Select` and `NumberInput` components to allow screenreaders to target content related to form element.
This value should only be added when the target ID exists within the DOM.
Related:
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/22569
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/22612
Updated unit tests
N/A

Add aria-describedby to Date, Select & NumberInput

---

package.json
yarn.lock

Like it says on the tin, there was a vulnerability with the version of `trim-newlines` we were using, so this pins it to `^4.0.2`, which is not vulnerable to the RegExp DOS attack that `1.0.0` is.
`trim-newlines` is a dependency of `meow` which is a dependency of `node-sass`. I looked into updating `node-sass`, but it uses the same version of `meow` as the version we're on now, so that was a dead end.
None :see_no_evil:
If this doesn't work as expected, I'm not sure how we'd figure it out unless it breaks spectacularly. :shrug:

Resolve trim-newlines vulnerability

---

src/components.d.ts
src/components/va-text-input/test/va-text-input.e2e.ts
src/components/va-text-input/va-text-input.tsx

Changes the disableAnalytics prop to enableAnalytics so it doesn't fire the events by default. This matches the current behavior of `TextInput`.
Automated tests.
N/A

disableAnalytics -> enableAnalytics on va-text-input

---

package.json
src/components/TextInput/TextInput.jsx
src/components/TextInput/TextInput.stories.jsx
stories/va-text-input.stories.jsx
yarn.lock

Adds the stories for `va-text-input`.
After much struggling with getting the funky default value to work like I wanted to, I gave up and settled on adding every bloody prop to the `defaultArgs`. :roll_eyes: It's still a bit funky, but it's not _awful._
:eyes: 
And more! But they're basically all like that. Very exciting.

va-text-input stories

---

README.md

Linking to the Web Component loading instructions based on a slack thread: https://dsva.slack.com/archives/C5HP4GN3F/p1625177758330000?thread_ts=1625156837.322300&cid=C5HP4GN3F

Add Web Component loading link

---

src/components/AlertBox/AlertBox.jsx
src/components/AlertBox/AlertBox.stories.jsx

This is a follow-up to https://github.com/department-of-veterans-affairs/component-library/pull/74
Now that we have `<va-alert>` we should guide teams towards that and away from `<AlertBox>`.

Mark AlertBox as deprecated in storybook

---

package.json

Because whatever uses these web components currently needs formation too
for the styling. This isn't the goal, but that's where we're at right now.

Add formation to peer dependencies

---

src/components.d.ts
src/components/va-checkbox/test/va-checkbox.e2e.ts
src/components/va-checkbox/va-checkbox.tsx
src/components/va-text-input/test/va-text-input.e2e.ts
src/components/va-text-input/va-text-input.tsx
src/utils/utils.ts

Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/27033
I also removed the `required` from the `input` on the `va-text-input` test. We may add it back in there, but it doesn't technically do that in the React version. I don't know whether or not it should, but I've asked our a11y specialists and will write up an issue to add it back in if we need it.
Unit tests pass.

Remove unknown attributes spread cv

---

package.json

This builds the library when it's [installed via a git URL](https://docs.npmjs.com/cli/v7/using-npm/scripts#life-cycle-scripts). With this addition, we won't have to require the downstream project to have that awful `postinstall` hook. 
Tested this on a local project installing this branch as a dependency via a [git URL](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#git-urls-as-dependencies).

Build during the prepare script

---

package.json

Gets v0.7.1 ready for release. [Changes](https://github.com/department-of-veterans-affairs/component-library/compare/wc-v0.7.0...bump-wc-0.7.1-cv) include:
- `<va-alert>` style updates
- Added `formation` to peer dependencies
- This was just implicit before
- Removed "unknown" attribute spread to the underlying `input` element in `va-text-input` and `va-checkbox`
- Added a `prepare` script to install the dependencies in the downstream project when using a git URL

Bump version to 0.7.1

---

src/components.d.ts
src/components/va-select/test/va-select.e2e.ts
src/components/va-select/va-select.tsx

Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/27163
Previously the build would give warnings due to the custom event names being the same as some native events:
Changing the names removes those warnings.
E2e tests

Rename events in va-select

---

package.json
yarn.lock

Closes department-of-veterans-affairs/va.gov-team/issues/26810
This should move `react` to be a peer dependency so we can avoid problems with conflicting versions of React.

Make react a peerDependency

---

.github/workflows/chromatic.yml

Based on findings from https://github.com/department-of-veterans-affairs/component-library/pull/125, we have moved the chromatic action into its own PR for easier review & discussion.

Move chromatic action to separate branch

---

package.json
src/components/Breadcrumbs/Breadcrumbs.jsx
src/components/Breadcrumbs/Breadcrumbs.unit.spec.jsx

Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/241
Tested that removing aria-polite stopped screen readers from announcing breadcrumbs when re-rendering
N/A

Removed aria-live from breakcrumbs

---

package.json
stories/va-radio.stories.jsx
yarn.lock

Related to #120 
Add storybook story for the new `<va-radio>` Web Component.
Note: This should not be merged until the component has a tagged release.

Add radio web component to storybook

---

.gitignore
package.json
react-bindings.js
stencil.config.ts
tsconfig.bindings.json

This is a followup for #131. We needed the bindings to be includes in the `files` property in `package.json` so that they remain after installation.
The directory structure has also been reworked slightly so that inside of the `react-bindings` directory we have an `index.js` file and an `index.d.ts` file after building the bindings. This allows typescript _and_ javascript projects to import from `component-library/react-bindings`
Local using https://github.com/department-of-veterans-affairs/formulate/pull/16

Change how React bindings are built

---

.github/workflows/add-release-files.yml

Closes #142.
This supercedes #143. In order for the action to run when a Release is tagged based on the `web-components` branch, this action will also need to be on that branch. Trying to change the base in the former PR messed things up, presumably due to no shared history.
We are doing this because using a `.git` url and building the package locally on different machines results in different checksums in the lockfile for yarn 2. Building the package remotely and attaching it to the release will solve this problem until we are able to actually unify `master` and `web-components`.
I monitored the `Actions` tab and made releases to trigger the action

Automatically build package and attatch to release

---

package.json

I mistakenly removed a script before committing my previous PR.

Fix incorrect removal of pre publish script

---

package.json
src/components/Banner/Banner.jsx

**Slack:** https://dsva.slack.com/archives/C52CL1PKQ/p1630607288190200
This PR changes the type for `vads-u-border-color--warning-message` to be `warning` instead of `error`.
Locally

Kelsonic 29069 banner refactor

---

.gitignore
package.json
src/components/Telephone/Telephone.jsx

Closes <https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/538>
See https://github.com/department-of-veterans-affairs/va.gov-team/issues/27451
Run vets-website locally using `yarn link`
- [ x] aria-describedby attribute is added to the phone number link when provided

Add support for aria-describedby attribute to Telephone component

---

package.json
src/components/Table/Table.jsx
src/components/Table/Table.unit.spec.jsx

Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/489
Manual testing.

Add <th> with scope='row' to Table component for screen readers

---

yarn.lock

An updated `yarn.lock` file is being generated when running `yarn install` locally and on CI. This PR refreshes the file so that it does not have to be updated.
Tests pass locally.

Refresh `yarn.lock` file

---

package.json
src/components/PromoBanner/PromoBanner.jsx
src/components/PromoBanner/PromoBanner.unit.spec.jsx

https://github.com/department-of-veterans-affairs/va.gov-team/issues/29824
Currently clicking a link in a Promo Banner dismisses the banner when only clicking the x should do that.
local, unit

Do not call onClose when link clicked

---

src/components/PromoBanner/PromoBanner.jsx

Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/250
Adds `aria-hidden="true"` and `role="presentation"` properties to icon elements for improved accessibility with JAWS. 
Passes all karma & linting tests.

Hide icons from screen readers

---

stories/va-accordion.stories.jsx

Addresses @GnatalieH 's comment on https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/314 about having a third accordion item.
Item text taken from: https://constitution.congress.gov/constitution/amendment-3/

Add third accordion item to Storybook

---

.github/workflows/chromatic.yml

This PR adds dependency caching to the Chromatic workflow on GitHub Actions, which will reduce CI times.

Add dependency caching to Chromatic workflow on GitHub Actions

---

package.json
src/components.d.ts
src/components/va-alert/va-alert.css
src/components/va-alert/va-alert.stories.tsx
src/components/va-alert/va-alert.tsx

This is to be used in https://github.com/department-of-veterans-affairs/component-library/pull/180
Implements a fullwidth variant for `<va-alert>` as found on https://design.va.gov/components/alertboxes#full-width-alerts

Add full-width variant for `<va-alert>`

---

package.json
src/components/Banner/Banner.jsx
stories/va-alert.stories.jsx
yarn.lock

This is meant to address an a11y issue with the `<AlertBox>` component @timwright12 mentioned in https://github.com/department-of-veterans-affairs/component-library/pull/179. In an effort to further the migration away from React components and towards Web Components, the `<Banner>` will use `<va-alert>` instead of its deprecated React counterpart.
If this gets merged, we should be able to delete [this file](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/a50f7304cfbb9824b75fd8af215769f1cf595c67/packages/formation/sass/modules/_m-emergency-banner.scss#L1).

Use fullwidth alert component in Banner

---

tsconfig.bindings.json

This is based off of a support request: https://dsva.slack.com/archives/CBU0KDSB1/p1632262136454800?thread_ts=1632163115.337400&cid=CBU0KDSB1
The mocha/babel setup in `vets-website` has problems importing a file from `node_modules` with ES6 imports. This should make the generated React bindings files use CommonJS so that the unit tests can run.
Tested putting a React binding on a page in `vets-website` on a branch that used this one for the `web-components` dependency.

Don't use ES6 imports for generated bindings

---

package.json
src/components/va-alert/test/va-alert.e2e.ts
src/components/va-alert/va-alert.css
src/components/va-alert/va-alert.tsx

It was noticed that some recent changes (#180, #181) resulted in the homepage banner being too wide in `vets-website`. This PR should fix that by limiting the body content to a maximum width of 1000px, while allowing the alert itself to extend across the entire page.
[Slack thread with additional context](https://dsva.slack.com/archives/C52CL1PKQ/p1632926162017600)
Looking at storybook and comparing it to va.gov

Limit the body width to 1000px on full-width

---

src/components/IconBase/IconBase.jsx
src/components/IconBase/IconBase.stories.jsx
src/components/IconHelp/IconHelp.jsx
src/components/IconHelp/IconHelp.stories.jsx
src/components/IconHelp/IconHelp.unit.spec.jsx
src/components/IconSearch/IconSearch.jsx
src/components/IconSearch/IconSearch.stories.jsx
src/components/IconSearch/IconSearch.unit.spec.jsx
src/components/IconUser/IconUser.jsx
src/components/IconUser/IconUser.stories.jsx
src/components/IconUser/IconUser.unit.spec.jsx

Closes <https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/221>
New unit tests to run aXe checks against `IconHelp`, `IconSearch`, and `IconUser` components.
* Icon being used alone
* Icon being used with supporting text
* Icon being used alone inside an `<a>` tag
* icon being used with supporting text inside an `<a>` tag

Update icon accessibility documentation

---

package.json
src/components/ProgressButton/ProgressButton.jsx
src/components/ProgressButton/ProgressButton.mdx
src/components/ProgressButton/ProgressButton.stories.jsx
src/components/ProgressButton/ProgressButton.unit.spec.jsx

Update `ProgressButton` component to match the component in `vets-website` `platform/forms-system/src/js/components/ProgressButton.jsx`.
I just merged in work to hide `button-icon` elements from a screenreader, but realized, that the majority of apps use the component-library ProgressButton component.
Additions:
- `aria-hidden="true"` to `button-icon` element (recent PR)
- `aria-label` prop & test (already in the platform ProgressButton from https://github.com/department-of-veterans-affairs/vets-website/pull/16114)
- `aria-describedby` prop & test - new addition. Needed for work on https://github.com/department-of-veterans-affairs/va.gov-team/issues/16182
- Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/30724
- Related to …

ProgressButton a11y updates

---

package.json
src/components.d.ts
src/components/va-back-to-top/test/va-back-to-top.e2e.ts
src/components/va-back-to-top/va-back-to-top.css
src/components/va-back-to-top/va-back-to-top.tsx
src/global/variables.css
src/mixins/buttons.css
src/utils/utils.ts
yarn.lock

Part of https://github.com/department-of-veterans-affairs/va.gov-team/issues/29785
This adds a `<va-back-to-top>` Web Component. This will replace our current "Back to top" button. It solves some problems with the old version:
- The button doesn't need to pay attention to the footer, and it will stop once it reaches its "dock"
- The dock ensures that space is reserved for the button
- The button will no longer appear on the same "line" as pagination buttons, etc.
- When the button is visible & undocked, its width is dynamically set to be that of its parent
Local dev server, storybook, and E2E tests
See #171

Add Back to top Web Component

---

package.json
yarn.lock

Updates the formation version so the sorting icon looks right in `<Table>` stories.
Related to https://github.com/department-of-veterans-affairs/component-library/pull/160 and https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/697

Update formation version for table styles

---

packages/core/package.json
packages/react-components/package.json
packages/react-components/src/components/Modal/Modal.jsx
packages/react-components/src/components/OMBInfo/OMBInfo.jsx

Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/31444
Specifically addresses these two issues:
1. Upon opening, the id "va-modal-title" is announced and not the heading itself as aria-label is used instead of aria-labelledby
2. The close button has an aria-label "close the warning modal," which can be simplified to just "close"
I'm not sure if this should be a patch or a minor version bump so I went with minor.

Modal a11y updates

---

.github/workflows/publish.yml
packages/web-components/package.json

The `prepare` script is [no longer part of `yarn`'s lifecycle scripts](https://yarnpkg.com/advanced/lifecycle-scripts), so it wasn't being run in the automation. This will ensure that the `react-bindings` directory is created and included in the published package.
I ran the following commands in order:
- `cd packages/react-components && yarn install`
- `cd -`
- `yarn workspace @department-of-veterans-affairs/react-components run build`
- `yarn workspace @department-of-veterans-affairs/web-components run build`
- `yarn workspace @department-of-veterans-affairs/web-components run build-bindings`
- `yarn workspace @department-of-veterans-affairs/component-library run build`
This is to mimic the setup that the CI would do. I then did a `pack` and checked to see if `react-bindings` was …

Build bindings for autopublish

---

packages/core/package.json
packages/web-components/package.json
packages/web-components/src/components/va-alert/va-alert.css

Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/32091
Visual (Storybook)

Fix padding for background-only alert web component

---

packages/core/package.json
packages/core/src/main.js
packages/web-components/package.json
yarn.lock

Related to a [support request](https://dsva.slack.com/archives/C01DBGX4P45/p1636569081014100).
A duplicate named export is causing errors in webpack 5, so this PR removes one of the duplicates. The reason we have both is because the `loader` export provides `applyPolyfills`, which we use for IE11 support. Once `vets-website` and the Design System no longer support IE11, we can remove the `loader` export entirely.
Checked that web components were working in storybook after the export was changed.
The `defineCustomElements` function exists in `web-components/loader` as well as `web-components/dist`:
Build warning removed in `packages/core`:

Only export applyPolyfills from the loader

---

packages/storybook/stories/va-featured-content.stories.jsx

Adds space between words in the va-featured-content storybook example
Visual testing

add space to featured content text

---

.github/release.yml

Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/32736
At the moment when we auto generate release notes, all PRs go into the same category:
We want to specifically call out which PRs belong to which semver category, and which PRs don't fit into those categories, like pure CI work or storybook updates.
For this template to generate the kinds of release notes we want, we need to make sure that the @department-of-veterans-affairs/vsp-design-system-fe is applying appropriate labels to PRs.
- Not see anything for the "Breaking Changes" category
- Not see anything for the "New Features & Components" category
- See at least one change in the "Fixes" category
- Maybe see changes in the "Other" category
- Not see anything for the "Breaking Changes" category
- See at …

Add initial release notes config file

---

packages/core/package.json
packages/storybook/stories/va-back-to-top.stories.jsx
packages/web-components/package.json
packages/web-components/src/components/va-back-to-top/test/va-back-to-top.e2e.ts
packages/web-components/src/components/va-back-to-top/va-back-to-top.css
packages/web-components/src/components/va-back-to-top/va-back-to-top.tsx

Related to https://github.com/department-of-veterans-affairs/va.gov-team/issues/31200
`<va-back-to-top>` is designed to be the last element in the main content area. Sometimes the main content area is styled with `usa-width-three-fourths` - a `uswds` class, and part of that styling is to [remove the margin from the last child](https://github.com/uswds/uswds/blob/c4c9410d54b537c6112037a36ed289d8b7e8940a/src/stylesheets/elements/_typography.scss#L227-L231). This PR adds "insulation" to `<va-back-top>` by adding an internal element that we can style as if it were the host. The `uswds` styles aren't able to have an effect this way with `:last-child` or `:first-child`.
This will unblock https://github.com/department-of-veterans-affairs/content-build/pull/759

Isolate host styling in "Back to top"

---

packages/storybook/stories/va-radio.stories.jsx

Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/33072 (including changes from https://github.com/department-of-veterans-affairs/component-library/pull/214)
This PR addresses:
> The radio inputs need to have the same name to group them together in the same radio group
https://github.com/department-of-veterans-affairs/component-library/pull/214 addressed:
> The id's for each input need to be unique. Current they're both just "input". The label for each input needs to have its' "for" attribute value updated to the unique id of its' related radio input. The radio inputs need their focus styling applied when focused
The id and label `for` attributes for each radio option were updated to use `<va-radio-option>`'s label attribute value. The ids will not conflict …

fix: update radio option name values

---

packages/core/package.json
packages/storybook/stories/va-accordion.stories.jsx
packages/web-components/package.json
packages/web-components/src/components/va-accordion/va-accordion-item.e2e.ts
packages/web-components/src/components/va-accordion/va-accordion-item.tsx
packages/web-components/src/components/va-accordion/va-accordion.tsx

When linking to a specific accordion, the ID of the accordion and the window location hash must exactly match for it to scroll that anchor into view. This PR makes the targeted accordion auto-expand.
- See https://github.com/department-of-veterans-affairs/content-build/pull/764 - this adds the content ID to the accordion
- Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/32966
Pending... I added one, but I can't get the `window.location.hash` to change in puppeteer.

Auto-expand va-accordion-item with matching hash

---

packages/core/.gitignore
packages/react-components/.gitignore
packages/storybook/.storybook/style.scss
packages/web-components/.gitignore

Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/32763
Fix:
Issue:

32763 storybook height issues gitignore update

---

packages/core/package.json
packages/storybook/stories/va-alert.stories.jsx
packages/web-components/package.json
packages/web-components/src/components.d.ts
packages/web-components/src/components/va-alert/test/va-alert.e2e.ts
packages/web-components/src/components/va-alert/va-alert.css
packages/web-components/src/components/va-alert/va-alert.tsx

Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/586
Storybook

Add option to show icon in background-only alert for <va-alert>

---

packages/core/package.json
packages/web-components/package.json
packages/web-components/src/components/va-on-this-page/test/va-on-this-page.e2e.ts
packages/web-components/src/components/va-on-this-page/va-on-this-page.tsx

Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/33214
Storybook & E2E

Add aria-labelledby to on-this-page web component

---

packages/core/package.json
packages/web-components/package.json

Preparing to publish `v3.8.0`
Here are the generated release notes if I try to draft a release right now:
The last published version was `3.7.2`. Since these staged changes include an enhancement, I'm increasing the minor version.
N/A

Increase minor version of core & web-components to 3.8

---

packages/web-components/src/components/va-accordion/va-accordion-item.e2e.ts

Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/33479
Included failing test to show that it's working properly when set to: `expect(await accordionItemToggled).toHaveReceivedEventTimes(1);`
See above
- Upon page load if a hash is present with the accordion the componentDidLoad Lifecycle event will fire a custom click event on the accordion item with the matching ID to the hash
- Issue was that we needed to await for the event to be present in the expect before firing and the event should only fire once since only one ID would match the hash
- componentDidLoad will fire immediately so we sometimes get inconsistent results due to the asynchronous timing of the testing suite

33479 Location hash matches the accordion id test fix

---

packages/web-components/src/components/va-accordion/va-accordion-item.e2e.ts

Fix will need to be done in https://github.com/department-of-veterans-affairs/va.gov-team/issues/33479
Test is being skipped due to inconsistencies on results causing other PRs to fail

Skip Flaky Test in va-accordion-item

---

packages/storybook/stories/va-alert.stories.jsx
packages/storybook/stories/va-checkbox.stories.jsx
packages/storybook/stories/va-loading-indicator.stories.jsx
packages/storybook/stories/va-select.stories.jsx
packages/storybook/stories/va-text-input.stories.jsx

Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/588
Storybook
va-alert:
va-text-input:
va-select:

Update stories to use kebab case for props

---

packages/core/package.json
packages/web-components/package.json
packages/web-components/src/components/va-segmented-progress-bar/va-segmented-progress-bar.tsx

Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/34239

34239 Segmented Progress Bar WC Aria Label displays incorrect default text

---

packages/core/package.json
packages/storybook/stories/va-telephone.stories.jsx
packages/web-components/package.json
packages/web-components/src/components.d.ts
packages/web-components/src/components/va-telephone/test/va-telephone.e2e.ts
packages/web-components/src/components/va-telephone/test/va-telephone.spec.tsx
packages/web-components/src/components/va-telephone/va-telephone.css
packages/web-components/src/components/va-telephone/va-telephone.tsx

Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/30137
The React `<Telephone>` implementation is a bit different than what I'm doing here, so I'll talk about what I've changed/left out.
The React component allowed a `pattern` prop to be passed so that a developer could choose how to format the number:
1. default
2. N11-style
3. a number for international use (+1 at the beginning)
4. any other way you want
We can cover the first two cases by seeing if the length of the `contact` prop is 3 or 10, and a boolean prop can be used for the third case. I've only found one example of `pattern` being used in a custom way:
https://github.com/department-of-veterans-affairs/vets-website/blob/f3ee0b52ddbaf311f64740fa3ab1d6803845793c/src/applications/claims-status/components/ap …

Add telephone Web Component

---

packages/core/package.json
packages/core/webpack.config.js
packages/web-components/package.json

Following the guidance:
https://webpack.js.org/migrate/5/#need-to-support-an-older-browser-like-ie-11

Build our main bundle for IE11

---

packages/storybook/stories/va-accordion.stories.jsx

Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/34126

34126 Update Accordion Story Default Args

---

packages/web-components/src/components/va-accordion/va-accordion-item.css

Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/602
Storybook

Fix children overflowing parent container in va-accordion-item

---

packages/core/package.json
packages/react-components/package.json
packages/react-components/src/components/NumberInput/NumberInput.jsx
packages/react-components/src/components/NumberInput/NumberInput.unit.spec.jsx

Our app is using the `SimpleDate` React component, which sets the `errorMessage` to an empty string. The `NumberInput` will bold the label (add `usa-input-error-label`) if the `errorMessage` is not undefined. So this PR fixes the `NumberInput` to use a falsy value instead of only `undefined`
Related: https://github.com/department-of-veterans-affairs/va.gov-team/issues/34827
Added unit test

Fix NumberInput styling

---

packages/react-components/src/components/Modal/Modal.jsx
packages/react-components/src/components/Modal/Modal.unit.spec.jsx
packages/storybook/stories/Modal.stories.jsx

Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/29215
This is an a11y fix to the `<Modal>` React component. It replaces the `<h3>` with an `<h1>` in order to improve the semantics for assistive tech.
- Unit testing
I also did an axe test on a modified story that had an `<h1>` already on the page in addition to the `<h1>` that would be in the modal.
<details>
<summary>H1 on page and in modal</summary>
</details>
As [this axe rule page notes](https://dequeuniversity.com/rules/axe/4.3/page-has-heading-one):
> Generally, it is a best practice to ensure that the beginning of a page's main content starts with a h1 element, **and also to ensure that the page contains only one h1 element.**
However, that page also says:
> This rule finds all elements which match the …

Change modal header to h1

---

packages/react-components/src/components/OMBInfo/OMBInfo.jsx
packages/react-components/src/components/OMBInfo/OMBInfo.unit.spec.jsx
packages/storybook/stories/OMBInfo.stories.jsx

Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/34523

Add prop for res burden feature name

---

packages/storybook/stories/va-breadcrumbs.stories.jsx

Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/35508
N/A

Update story breadcrumb segments to sentence casing

---

packages/core/package.json
packages/web-components/package.json
packages/web-components/src/components/va-accordion/va-accordion-item.css

Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/35553

Update va-accordion-item paragraphs to wrap

---

packages/core/package.json
packages/web-components/package.json
packages/web-components/src/components/va-accordion/va-accordion-item.css

The previous CSS changes made to va-accordion-item in #252 and #267 have introduced defects and are reverted in this PR.  The fix for the original issue is included.
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/602
Here you can see a child container with width 100% that contains children containers of different widths (400px, 100%). Each container has a string long enough to require a horizontal scrollbar to view unless wrapped. There is no horizontal bar.

Prevent text overflowing container in va-accordion-item

---

packages/core/package.json
packages/react-components/src/components/Banner/Banner.jsx
packages/storybook/stories/va-alert.stories.jsx
packages/web-components/package.json
packages/web-components/src/components.d.ts
packages/web-components/src/components/va-alert/test/va-alert.e2e.ts
packages/web-components/src/components/va-alert/va-alert.tsx

Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/35822
Edge 13, Safari 10, Chrome 45, Firefox 52
Note: Storybook doesn't finish loading in Safari 9 and Chrome 44.

Fix va-alert close event dispatch

---

.github/workflows/require-label.yml

Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/35707
Use [this GitHub action](https://github.com/marketplace/actions/require-labels) to configure required labels on our PRs. For now this is to help ensure consistent release notes, but later the labels may be used to trigger other things.
I've also updated the `master` branch protection rule to make this status check be required to pass before merging a PR.
This PR - adding labels, :eyes: on status checks
Failing on no labels:
<details>
</details>
Passing when an expected label is applied:
<details>
</details>
Adding additional labels that aren't in the exclusive list doesn't cause problems:
<details>
</details>
Failing when the right label isn't applied:
<details>
</details>
Failing when two mutually exclusive …

Require label on PRs

---

packages/web-components/src/components/va-text-input/va-text-input.tsx

Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/27940
MacOs Voiceover Recording
https://user-images.githubusercontent.com/11822533/151055354-7d24d0ba-32d8-40bd-8418-3466593ac486.mov

27940 va-text-input WC Max Char Aria Accessibility

---

packages/core/package.json
packages/storybook/package.json
packages/storybook/stories/MaintenanceBanner.stories.jsx
yarn.lock

Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/34439
N/A
Chrome:
Safari:
Firefox:
Edge:

34439 Remove date-fns dependency from component library

---

packages/core/package.json
packages/storybook/stories/va-text-input.stories.jsx
packages/web-components/package.json
packages/web-components/src/components.d.ts
packages/web-components/src/components/va-text-input/test/va-text-input.e2e.ts
packages/web-components/src/components/va-text-input/va-text-input.tsx

Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/27936
This removes the `placeholder` prop from `<va-text-input>` in accordance with the DSC's decision.
- Unit tests passing

Remove placeholder prop from va-text-input

---

.github/release.yml

In https://github.com/department-of-veterans-affairs/component-library/pull/274 we added a GitHub action to require labels on PRs. This update matches the labels required in that PR to the appropriate release note categories.

Match release note labels to required labels

---

packages/storybook/.storybook/preview.js
packages/web-components/src/components/va-alert/test/va-alert.e2e.ts
packages/web-components/src/components/va-alert/va-alert.tsx

Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/34161
Tested with NVDA
N/A

Fix va-alert heading to not announce as clickable when using NVDA

---

packages/storybook/stories/wc-helpers.jsx

Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/36546
This was affecting `va-accordion` because it is the first web component story. If you remove the `va-accordion` story, the same problem appears for the next story that follows it: `va-additional-info`.
Storybook

Fix Storybook stories render

---

packages/storybook/stories/RadioButtons.stories.jsx

Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/533

533 Storybook React RadioButtons Error Message Display

---

packages/web-components/src/index.html

While using Stencil's dev server to test and view web components in IE11, I noticed that our web components were missing styles. Loading the CSS files before the components fixes this issue in IE11.
Note: This issue exists only in IE11. This did not occur for Chrome, Firefox, Edge and Safari.
N/A
Before (IE11)
After (IE11)

Fix CSS in Stencil dev server for IE11

---

packages/core/package.json
packages/react-components/index.js
packages/react-components/package.json
packages/react-components/src/index.js
packages/storybook/stories/Telephone.stories.jsx
packages/storybook/stories/va-telephone.stories.jsx

Related to https://github.com/department-of-veterans-affairs/vets-website/pull/20262
From a slack convo with @Mottie and @k80bowman :
> [Brooks Johnson]: Do you think the `PHONE_CONTACTS` export is fine or should it be renamed to `CONTACTS`? I think I did that since it wouldn't be imported from `/Telephone` anymore, but I still wanted to indicate that it was for the telephone component to avoid confusion that it might be for email contacts or something like that.
>
> [Robin Garrison]: I think if it's documented `CONTACTS` should be fine... it's what the devs are already familiar with
I'm undoing the aliasing for `CONTACTS` and `contactsMap` since they're related. `contactsMap` should only be used in documentation anyway. I'm leaving the `PATTERNS` aliasing as it is because hopefully we …

Move CONTACTS table to telephone web component story

---

packages/core/package.json
packages/react-components/package.json
packages/web-components/package.json
yarn.lock

This is in response to comment: https://github.com/department-of-veterans-affairs/va.gov-team/issues/33798#issuecomment-1048959308
`vets-website` is updating to yarn 3 and is receiving some warnings/errors related to peer dependencies on a `yarn install`:
```
➤ YN0002: │ @department-of-veterans-affairs/component-library@npm:6.2.1 doesn't provide @department-of-veterans-affairs/formation (pc959a), requested by @department-of-veterans-affairs/web-components
➤ YN0002: │ @department-of-veterans-affairs/component-library@npm:6.2.1 doesn't provide react (p40b9e), requested by react-focus-on
➤ YN0002: │ @department-of-veterans-affairs/component-library@npm:6.2.1 doesn't provide react (pacd1e), requested by react-scroll
➤ YN0002: │ @department-of-veterans-affairs/component-library@npm:6.2.1 …
```

Adjust peer dependencies to remove warnings

---

packages/core/package.json
packages/web-components/package.json
packages/web-components/src/components/va-accordion/va-accordion.e2e.ts
packages/web-components/src/components/va-accordion/va-accordion.tsx
packages/web-components/src/components/va-alert/test/va-alert.e2e.ts
packages/web-components/src/components/va-alert/va-alert.tsx

Closes part of https://github.com/department-of-veterans-affairs/va.gov-team/issues/35769

35769 Fix Analytics Component Name

---

package.json
yarn.lock

Adds resolution for prismjs to hopefully resolve [security warning](https://github.com/department-of-veterans-affairs/component-library/security/dependabot/46).
There are a lot of `yarn.lock` updates here, too. I deleted my yarn.lock file and re-installed to make sure Prism was updated and the result was a lot of other packages were updated, too. Probably worth being a little careful with this one. 
- Ran Storybook and Stencil locally.

add upgrade resolution for prismjs

---

packages/core/package.json
packages/web-components/package.json
packages/web-components/src/components/va-checkbox-group/test/va-checkbox-group.e2e.ts

Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/36385

36385 Checkbox Group axe check test in error state

---

packages/core/package.json
packages/web-components/package.json
packages/web-components/src/components/va-promo-banner/va-promo-banner.css
packages/web-components/src/components/va-promo-banner/va-promo-banner.tsx

Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/35157
We need this body class toggled whenever the promo banner is present. Without it we have a padding issue in the footer with the banner covering content and the only way to view is to dismiss the banner. This would revert https://github.com/department-of-veterans-affairs/vets-website/pull/20435 with this removed.
https://user-images.githubusercontent.com/11822533/157355906-8f748157-dd05-4975-a1e6-51b094029fcf.mov

35157 Promo Banner Padding Class on Body for Footer Spacing

---

packages/core/package.json
packages/web-components/package.json

https://hotfix-revert-increment-patch--60f9b557105290003b387cd5.chromatic.com
Cleanup work that should have been part of https://github.com/department-of-veterans-affairs/component-library/pull/323

chore: increment patch version

---

packages/web-components/src/components/va-table/va-table.tsx

https://sortColumn-ie11-doc--60f9b557105290003b387cd5.chromatic.com
(I broke the branch naming rule and used a capital letter :see_no_evil: . Here you go: https://60f9b557105290003b387cd5-qplzanilil.chromatic.com/?path=/docs/components-va-table--default)
[Relevant slack thread](https://dsva.slack.com/archives/G01BJ3ESXL4/p1649162602102219?thread_ts=1649109622.789609&cid=G01BJ3ESXL4)
This is a storybook update to go out ahead of the `<va-table>` announcement.

Add comment to prop doc about IE11 support

---

packages/storybook/stories/va-modal.stories.jsx

https://39968-modal--60f9b557105290003b387cd5.chromatic.com
Part of https://github.com/department-of-veterans-affairs/va.gov-team/issues/39968

Add subtitle and action link for Modal in Storybook

---

packages/storybook/stories/va-alert.stories.jsx
packages/web-components/src/components/va-alert/va-alert.css

https://39872-alert-documentation--60f9b557105290003b387cd5.chromatic.com
Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/39872
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/704

39872 Alert Documentation SB

---

packages/core/src/i18n/translations/en.js
packages/core/src/i18n/translations/es.js

https://add-placeholder-translations--60f9b557105290003b387cd5.chromatic.com
This is to initialize the translation files with all the keys we need so that PRs for each component have something to work with. No code in `master` is making use of the `i18next` dependency at the moment so this will go unused for now.
Tests should be able to use the `cimode` language if they need to test for specific values.
N/A

Add placeholder translations for a few components

---

packages/storybook/stories/va-loading-indicator.stories.jsx

https://39967-loading-indicator--60f9b557105290003b387cd5.chromatic.com
Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/39967
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/709

39967 Loading Indicator Storybook Documentation

---

packages/storybook/stories/events.js
packages/storybook/stories/va-loading-indicator.stories.jsx

A couple of links give 403/404 when followed.
Update `event.js` to link to https://design.va.gov/about/developers#using-web-components

Fix links to design system docs

---

packages/storybook/stories/va-text-input.stories.jsx
packages/web-components/src/components.d.ts
packages/web-components/src/components/va-text-input/va-text-input.css
packages/web-components/src/components/va-text-input/va-text-input.tsx

https://39929-text-input--60f9b557105290003b387cd5.chromatic.com
Part of https://github.com/department-of-veterans-affairs/va.gov-team/issues/39929
N/A

Add subtitle, link and success state example for va-text-input

---

packages/storybook/stories/va-select.stories.jsx

https://39957-select--60f9b557105290003b387cd5.chromatic.com
Part of https://github.com/department-of-veterans-affairs/va.gov-team/issues/39957
N/A

Add subtitle and link for Select Box

---

packages/core/package.json
packages/storybook/stories/va-number-input.stories.jsx
packages/web-components/package.json
packages/web-components/src/components.d.ts
packages/web-components/src/components/va-number-input/va-number-input.tsx

https://39738-number-input-docs--60f9b557105290003b387cd5.chromatic.com
Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/39738
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/742

39738 Number Input Docs Link Fix and Input El fix

---

packages/core/package.json
packages/web-components/package.json
packages/web-components/src/components.d.ts
packages/web-components/src/components/va-accordion/va-accordion-item.css
packages/web-components/src/components/va-accordion/va-accordion-item.tsx
packages/web-components/src/components/va-checkbox/va-checkbox.tsx
packages/web-components/src/components/va-text-input/va-text-input.tsx

https://jsdoc-input-element-fix--60f9b557105290003b387cd5.chromatic.com
When using `<input>` in JSDoc it converts from a code block to a HTML Element. Changing our comments for the docs to type out input element instead of putting the comment in as a `<input>`.

Fix for JSDoc usage of <input> in docs

---

packages/web-components/src/components/va-additional-info/va-additional-info.css
packages/web-components/src/global/variables.css

success criteria for contrast. Issue #650 in vets-design-system-documentation.
https://va-additional-info-color-650--60f9b557105290003b387cd5.chromatic.com
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/650
Verified in Storybook via Inspect.

Updates va-additional-info to use primary alt darkest to pass WCAG 

---

packages/storybook/stories/va-back-to-top.stories.jsx

https://40110-btp--60f9b557105290003b387cd5.chromatic.com
Part of https://github.com/department-of-veterans-affairs/va.gov-team/issues/40110
N/A

Add subtitle and link to DS for va-back-to-top

---

packages/core/package.json
packages/storybook/stories/va-checkbox.stories.jsx
packages/web-components/package.json
packages/web-components/src/components.d.ts
packages/web-components/src/components/va-checkbox/test/va-checkbox.e2e.ts
packages/web-components/src/components/va-checkbox/va-checkbox.tsx

https://39739-checkbox-blur--60f9b557105290003b387cd5.chromatic.com/
Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/39739
E2E, Storybook

Replace vaBlur with native blur event for va-checkbox

---

packages/storybook/stories/va-search-input.stories.jsx
packages/web-components/src/components/va-search-input/test/va-search-input.e2e.ts
packages/web-components/src/components/va-search-input/va-search-input.tsx

https://typeahead-value--60f9b557105290003b387cd5.chromatic.com
These changes allow consumers to retrieve the updated value on `input` and `submit` events from `event.target.value`.
https://user-images.githubusercontent.com/36863582/165602408-81424ce7-fbe6-4fd3-8d94-371b070f6cde.mov

Update va-search-input to emit the correct target value

---

packages/storybook/stories/va-checkbox-group.stories.jsx
packages/storybook/stories/va-checkbox.stories.jsx
packages/storybook/stories/va-date.stories.jsx
packages/storybook/stories/va-radio.stories.jsx
packages/storybook/stories/va-select.stories.jsx
packages/storybook/stories/va-text-input.stories.jsx

https://773-text-input-storybook-link--60f9b557105290003b387cd5.chromatic.com
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/773

773 Fix Form Control links from Storybook to design.va

---

packages/react-components/src/components/TextInput/TextInput.jsx
packages/react-components/src/components/TextInput/TextInput.unit.spec.jsx
packages/storybook/stories/TextInput.stories.jsx
packages/storybook/stories/va-text-input.stories.jsx
packages/web-components/src/components/va-text-input/test/va-text-input.e2e.ts
packages/web-components/src/components/va-text-input/va-text-input.tsx

https://translate-text-input--60f9b557105290003b387cd5.chromatic.com
Closes [va.gov-team/39885](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/39885)
Updated existing text input tests.

Translate text input

---

packages/core/package.json
packages/web-components/package.json

https://translation-version-bump--60f9b557105290003b387cd5.chromatic.com
We've got a handful of translation-related changes in master ready to be published. This just bumps the version.
N/A

Bump version publishing translation changes

---

packages/core/package.json
packages/react-components/package.json

https://react-component-translation-bump--60f9b557105290003b387cd5.chromatic.com
In #421 I forgot to include a bump for the `react-components` version :upside_down_face: . This means we didn't get the `<Date>` react component changes published. [GitHub action log](https://github.com/department-of-veterans-affairs/component-library/runs/6396508654?check_suite_focus=true#step:12:130).

Bump react-components version

---

packages/core/package.json
packages/core/src/i18n/translations/es.js
packages/core/webpack.config.js
packages/react-components/package.json
packages/web-components/package.json

https://fix-react-build-publicPath--60f9b557105290003b387cd5.chromatic.com
In order for dynamic translation in the `<Date>` react component to work, the import needs to be made in the root of the `component-library` package. Doing this causes `vets-website` tests to fail, saying:
```
Error: Automatic publicPath is not supported in this browser
```
Setting `publicPath: ''` is a workaround that I've seen mentioned in a few places:
- [SO answer](https://stackoverflow.com/a/64715069)
- This seems to be about fonts, which isn't our use case
- [GH issue on `cypress` repo](https://github.com/cypress-io/cypress/issues/18435#issue-1022498688)
- This is testing/JS related, so maybe it will work
Tested using a [pre-release](https://github.com/department-of-veterans-affairs/component-library/releases/ …

Fix react build public path

---

packages/web-components/src/components/va-segmented-progress-bar/test/va-segmented-progress-bar.e2e.ts
packages/web-components/src/components/va-segmented-progress-bar/va-segmented-progress-bar.tsx

https://fix&#x2F;249-tabindex-progress-bar--60f9b557105290003b387cd5.chromatic.com
This a simple change to update the tabIndex to -1 on the va-segmented-progress-bar component to remove the ability to navigate using the keyboard. 
Closes [VAFSC Ticket with original ticket link](https://app.zenhub.com/workspaces/forms-library---platform-spike-team-61b0ae1f2cd3c30014e8a5b0/issues/department-of-veterans-affairs/va-forms-system-core/249)

fix: updating tabindex to -1 to stop keyboard nav

---

packages/web-components/src/components/va-radio-option/va-radio-option.css

https://40279-radio-option--60f9b557105290003b387cd5.chromatic.com
Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/40279
Storybook

Focus only radio button for va-radio 

---

packages/storybook/stories/va-alert.stories.jsx

https://791-storybook-dismissable-background--60f9b557105290003b387cd5.chromatic.com
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/889
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/791

791 Storybook Dismissable Background

---

packages/storybook/stories/va-featured-content.stories.jsx

https://40188-featured-content--60f9b557105290003b387cd5.chromatic.com
Part of https://github.com/department-of-veterans-affairs/va.gov-team/issues/40188

Add subtitle and link to DS for va-featured-content

---

packages/design-system-dashboard-cli/src/find-ds-components.js

https://bindings-import-scan--60f9b557105290003b387cd5.chromatic.com
As of https://github.com/department-of-veterans-affairs/vets-website/pull/21127 `vets-website` code is importing the bindings directly from `component-library` instead of through the alias. This updates the regex to match the import path.
Ran the report and got results showing bindings.

Update usage report regex for bindings import

---

packages/storybook/stories/va-alert.stories.jsx

https://sign-in-button-color--60f9b557105290003b387cd5.chromatic.com
Updates button color on the sign in alert to green to match [guidance](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/653#issuecomment-1147863128).

change sign in alert button color to green

---

packages/storybook/stories/va-button.stories.jsx
packages/web-components/src/components/va-button/test/va-button.e2e.ts
packages/web-components/src/components/va-button/va-button.css
packages/web-components/src/components/va-button/va-button.tsx

https://va-button-disabled--60f9b557105290003b387cd5.chromatic.com
This PR adds the missing `disabled` styling and story for `va-button`.
Tasks from https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/751#issuecomment-1149190166
Storybook

Add disabled styling and story for va-button

---

packages/storybook/stories/wc-helpers.jsx

https://900-native-events--60f9b557105290003b387cd5.chromatic.com
Partly closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/900

Add web component native events docs link

---

packages/storybook/stories/va-button.stories.jsx
packages/web-components/src/components.d.ts
packages/web-components/src/components/va-button/test/va-button.e2e.ts
packages/web-components/src/components/va-button/va-button.tsx

https://818-button-disabled--60f9b557105290003b387cd5.chromatic.com
Part of https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/818
This PR updates va-button to be focusable when `disabled` is true to improve its accessibility while providing the same functionality and styling of a disabled button. The button is no longer being disabled. If `disabled` is true, the click event will not bubble.
E2E, Storybook

Update va-button to be focusable when disabled

---

packages/core/package.json
packages/web-components/package.json
packages/web-components/src/components/va-date/va-date.css
packages/web-components/src/components/va-select/va-select.css
packages/web-components/src/components/va-text-input/test/va-text-input.e2e.ts
packages/web-components/src/components/va-text-input/va-text-input.css
packages/web-components/src/components/va-textarea/va-textarea.css

https://956-inputs--60f9b557105290003b387cd5.chromatic.com
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/956
- Updated input border from 2px to 4px for `va-date`, `va-date-text-input`, `va-text-input`
- Updated input border from 3px to 4px for `va-select`
- Fixed `va-select` styles when error is an empty string
- Fixed `va-text-input` styles for success state
- Added 4px border when `error` is true to `va-text-area` - We weren't showing a border previously
I've verified that this is not affecting our other web component inputs: va-checkbox, va-checkbox-group, va-date, va-date-text-input, va-radio and va-text-area.
Storybook
There were the affected components:

Fix styling for va-select and va-text-input when required is true

---

packages/core/package.json
packages/web-components/package.json
packages/web-components/src/components/va-alert-expandable/va-alert-expandable.css

https://longmd-clear-expandable-alert-default-margin--60f9b557105290003b387cd5.chromatic.com
This PR removes the default margin from the `va-alert-expandable` component. This margin creates unnecessary indents of the component and the need to wrap in a div with negative margin to align with surrounding components.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/43338

Remove unnecessary margin on va-alert-expandable

---

packages/core/package.json
packages/web-components/package.json
packages/web-components/src/components/va-breadcrumbs/va-breadcrumbs-slot.css

https://469-breadcrumbs--60f9b557105290003b387cd5.chromatic.com
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/469
Storybook

Prevent breadcrumb line break on mobile

---

packages/web-components/src/components.d.ts
packages/web-components/src/components/va-text-input/test/va-text-input.e2e.ts
packages/web-components/src/components/va-text-input/va-text-input.tsx
packages/web-components/src/components/va-textarea/test/va-textarea.e2e.ts
packages/web-components/src/components/va-textarea/va-textarea.tsx

https://textarea-review--60f9b557105290003b387cd5.chromatic.com
- Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/42520
- Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/42812
- Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/42811
- Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/872
This PR:
- Removes the redundant `aria-labelledby` attribute (redundant due to the `htmlFor` attribute on the label)
- Ensures that only positive `maxlength` values will be used when displaying the validation message
- This feedback is only a "consider", so it's up to us whether we want to implement it or not. See review comments below
- E2E tests

Remove redundant textarea attribute & validate maxlength

---

packages/web-components/src/components/va-text-input/va-text-input.tsx
packages/web-components/src/components/va-textarea/va-textarea.tsx

https://remove-aria-live--60f9b557105290003b387cd5.chromatic.com
Part of https://github.com/department-of-veterans-affairs/va.gov-team/issues/39727
This removes the `aria-live` attribute from the "Min chars" and "Max chars" message in the form components:
- `va-text-input`
- `va-textarea`
From @davidakennedy 's comment on the issue:
> We should remove this additional `aria-live` region because multiple ARIA live regions on a page can get complex, and not all of them will be announced if they occur at the same time.
E2E
There are some remaining `aria-live` attributes, but they are not related to error messaging:

Remove unneeded aria-live when errors occur

---

packages/web-components/src/components/va-checkbox/va-checkbox.tsx
packages/web-components/src/components/va-number-input/test/va-number-input.e2e.ts
packages/web-components/src/components/va-number-input/va-number-input.tsx
packages/web-components/src/components/va-select/test/va-select.e2e.ts
packages/web-components/src/components/va-select/va-select.tsx

https://remove-aria-labelledby--60f9b557105290003b387cd5.chromatic.com
Part of https://github.com/department-of-veterans-affairs/va.gov-team/issues/39727
This removes the redundant `aria-labelledby` attribute when the label is connected to the interactive control using the `for` attribute. From @davidakennedy's comment on the ticket:
> The select input has `aria-labelledby="select-label"` or similar. However, this isn't needed since each input is already associated with labels via the `for` attribute like this, `for="select"`. The `aria-labelledby` attributes should be removed.
E2E with axe testing
The only remaining `aria-labelledby` is in `<va-on-this-page>`:
https://github.com/department-of-veterans-affairs/component-library/blob/36614239b1ca1984ebe58a306c11860ab9178e6b/packages/web-com …

Remove aria-labelledby in form controls

---

packages/web-components/package.json
yarn.lock

https://puppeteer-bump--60f9b557105290003b387cd5.chromatic.com
With my new laptop on Ubuntu 22.04, I'm unable to run puppeteer tests locally in the `web-components` package. I get the following error:
```
Protocol error (Target.setDiscoverTargets): Target closed. Error: Protocol error
```
With the newer puppeteer version from this branch, I'm able to successfully run the tests:

Bump puppeteer version

---

packages/web-components/src/components/va-date/test/va-date.e2e.ts
packages/web-components/src/components/va-date/va-date.css
packages/web-components/src/components/va-date/va-date.tsx
packages/web-components/src/components/va-memorable-date/test/va-memorable-date.e2e.ts
packages/web-components/src/components/va-memorable-date/va-memorable-date.tsx

https://date-errors-describedby--60f9b557105290003b387cd5.chromatic.com
Part of https://github.com/department-of-veterans-affairs/va.gov-team/issues/39727
This adds `aria-describedby` attributes to each of the child components inside of `<va-date>`. When asked if this would help improve accessibility, @davidakennedy [responded](https://github.com/department-of-veterans-affairs/va.gov-team/issues/39727#issuecomment-1183710345) and said that this solution would work.
After a [discussion with Tiffany Pender](https://github.com/department-of-veterans-affairs/component-library/pull/486#discussion_r921577719), we have decided not to apply those changes to the `<va-memorable-date>` since it doesn't help screen readers.
E2E

Associate date errors with sub components

---

packages/storybook/stories/additional-docs.js

https://mem-date-link--60f9b557105290003b387cd5.chromatic.com
Directs link on va-memorable-date to the correct page on design.va.gov
local

fix link to memorable date docs

---

packages/web-components/src/components.d.ts
packages/web-components/src/components/va-checkbox/test/va-checkbox.e2e.ts
packages/web-components/src/components/va-checkbox/va-checkbox.tsx
packages/web-components/src/components/va-date/test/va-date.e2e.ts
packages/web-components/src/components/va-date/va-date.tsx
packages/web-components/src/components/va-memorable-date/test/va-memorable-date.e2e.ts
packages/web-components/src/components/va-memorable-date/va-memorable-date.tsx
packages/web-components/src/components/va-number-input/test/va-number-input.e2e.ts
packages/web-components/src/components/va-number-input/va-number-input.tsx
packages/web-components/src/components/va-radio/test/va-radio.e2e.ts
packages/web-components/src/components/va-radio/va-radio.tsx
packages/web-components/src/components/va-select/test/va-select.e2e.ts
packages/web-components/src/components/va-select/va-select.tsx
packages/web-components/src/components/va-text-input/test/va-text-input.e2e.ts
packages/web-components/src/components/va-text-input/va-text-input.tsx
packages/web-components/src/components/va-textarea/test/va-textarea.e2e.ts
packages/web-components/src/components/va-textarea/va-textarea.tsx
packages/web-components/src/utils/date-utils.spec.ts
packages/web-components/src/utils/date-utils.ts

https://aria-invalid--60f9b557105290003b387cd5.chromatic.com
Part of:
- https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/844
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/39727
This adds the `aria-invalid` attribute to the `<input>`/`<select>` part of components as well as to the `radiogroup` role for radio buttons. This attribute defaults to false and is set to true when there is an error message. The `<va-checkbox-group>` component doesn't have this update because it looked like the `group` role didn't match the [associated roles of the aria attribute](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-invalid#associated_roles).
The form components which haven't received `aria-invalid` are:
- …

Add aria-invalid to most form components

---

packages/core/package.json
packages/storybook/stories/va-telephone.stories.jsx
packages/web-components/package.json
packages/web-components/src/components.d.ts
packages/web-components/src/components/va-telephone/test/va-telephone.e2e.ts
packages/web-components/src/components/va-telephone/test/va-telephone.spec.tsx
packages/web-components/src/components/va-telephone/va-telephone.tsx

https://telephone-tty--60f9b557105290003b387cd5.chromatic.com
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/775
This allows consumers of the telephone component to indicate that it is for a TTY number. This will add some `TTY` text to the `aria-label` and the link text, but not to the `href`.
- Unit tests
- E2E test

Add tty prop to telephone component

---

packages/core/package.json
packages/web-components/package.json
packages/web-components/src/components/va-breadcrumbs/va-breadcrumbs.css

https://1002-breadcrumb-padding--60f9b557105290003b387cd5.chromatic.com
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1002
Storybook

style: update va-breadcrumbs padding

---

packages/core/package.json
packages/web-components/package.json
packages/web-components/src/components/va-button/va-button.css

https://45000-va-button--60f9b557105290003b387cd5.chromatic.com
Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/45000
Part of https://github.com/department-of-veterans-affairs/va.gov-team/issues/44671
Storybook

style: add active styling for secondary and back va-button variants

---

packages/core/package.json
packages/web-components/package.json
packages/web-components/src/components/va-telephone/va-telephone.css

https://188-telephone-nowrap--60f9b557105290003b387cd5.chromatic.com
Closes department-of-veterans-affairs/vets-design-system-documentation#188
Visual
**Before, without nowrap**
I made the width of the component something ridiculous (22px), as shown by the gray background
**After, with nowrap**
Again, with the same ridiculously small width, as shown by the coral background

Add nowrap to telephone component CSS

---

packages/core/package.json
packages/web-components/package.json
packages/web-components/src/components/va-alert/va-alert.css
packages/web-components/src/components/va-alert/va-alert.tsx

https://1040-va-alert-icons--60f9b557105290003b387cd5.chromatic.com
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1040
Storybook

fix: text does not overlap icon in alerts

---

packages/core/package.json
packages/web-components/package.json
packages/web-components/src/components/va-checkbox-group/va-checkbox-group.css
packages/web-components/src/components/va-checkbox/va-checkbox.css
packages/web-components/src/components/va-date/va-date.css
packages/web-components/src/components/va-memorable-date/va-memorable-date.css
packages/web-components/src/components/va-number-input/va-number-input.css
packages/web-components/src/components/va-radio/va-radio.css
packages/web-components/src/components/va-select/va-select.css
packages/web-components/src/components/va-text-input/va-text-input.css
packages/web-components/src/components/va-textarea/va-textarea.css
packages/web-components/src/mixins/form-field-error.css

https://957-input-error-border--60f9b557105290003b387cd5.chromatic.com
Closes
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/957
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1055
This update will align the form field error state display with USWDS. More specifically, it addresses padding inconsistencies across the following web components:
```
va-textarea
va-text-input
va-number-input
va-select
va-date
va-radio
va-memorable-date
va-checkbox-group
va-checkbox
```
Additionally, it fixes an issue with the error left border not displaying on smaller viewports. The USWDS solves this by shifting the field to the right which is what this update does as well.
Below is the current style and responsive behavior …

Updating form web component error styles to align with USWDS.

---

packages/storybook/stories/va-date.stories.jsx

https://date-sb-real-example--60f9b557105290003b387cd5.chromatic.com
Part of https://github.com/department-of-veterans-affairs/va.gov-team/issues/45152
As part of the staging review for the `monthYearOnly` date variant and `<va-memorable-date>`, it was pointed out that both components were presented as "Date of birth" fields. This doesn't make the difference very obvious, so this PR changes the example for `<va-date>` to use [an example based on real code](https://github.com/department-of-veterans-affairs/vets-website/blob/f22b2c3be6be9735d52ff202d580badfce818732/src/applications/disability-benefits/wizard/pages/bdd.jsx#L109-L116).

Replace the "Date of Birth" label with a real one

---

packages/core/package.json
packages/web-components/package.json
packages/web-components/src/components/va-modal/test/va-modal.e2e.ts
packages/web-components/src/components/va-modal/va-modal.tsx

https://a11y-fix-modal--60f9b557105290003b387cd5.chromatic.com
Moves the `aria-label`, `aria-modal` and `role` attributes to the `host` element.
Visual in storybook

Move aria attributes for va-modal to host

---

packages/core/package.json
packages/web-components/package.json
packages/web-components/src/components/va-additional-info/test/va-additional-info.e2e.ts
packages/web-components/src/components/va-additional-info/va-additional-info.css
packages/web-components/src/components/va-additional-info/va-additional-info.tsx
packages/web-components/src/components/va-alert-expandable/test/va-alert-expandable.e2e.ts
packages/web-components/src/components/va-alert-expandable/va-alert-expandable.css
packages/web-components/src/components/va-alert-expandable/va-alert-expandable.tsx

https://904-expandable--60f9b557105290003b387cd5.chromatic.com
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/904
va-alert-expandable:
va-additional-info:

Fixes for va-alert-expandable

---

packages/css-library/src/stylesheets/utilities.scss
packages/css-library/src/tokens/border.scss
packages/css-library/src/tokens/display.scss
packages/css-library/src/tokens/font.scss
packages/css-library/src/utilities/_index.scss
packages/css-library/src/utilities/border.scss
packages/css-library/src/utilities/display.scss
packages/css-library/src/utilities/font.scss
packages/css-library/src/utilities/settings.scss

https://1027-bdf-utilities--60f9b557105290003b387cd5.chromatic.com
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1027

chore: add v3 border, display and font utilities

---

packages/core/package.json
packages/storybook/stories/va-date.stories.jsx
packages/web-components/package.json
packages/web-components/src/components.d.ts
packages/web-components/src/components/va-date/test/va-date.e2e.ts
packages/web-components/src/components/va-date/va-date.tsx
packages/web-components/src/components/va-memorable-date/test/va-memorable-date.e2e.ts
packages/web-components/src/components/va-memorable-date/va-memorable-date.tsx
packages/web-components/src/utils/date-utils.spec.ts
packages/web-components/src/utils/date-utils.ts

https://date-validation--60f9b557105290003b387cd5.chromatic.com
Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/44929
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/848
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/875
This reworks the validation of our date components. Both `<va-date>` and `<va-memorable-date>` now run the same build-in validation, and users can apply any custom validation afterwards on the handler for `dateBlur`. The built-in validation consists of:
- An error message when year is incomplete
- An error message when month is provided but outside of a range (only really useful for memorable date)
- An error message when day is provided but …

Rework date validation

---

packages/core/package.json
packages/web-components/package.json
packages/web-components/src/components/va-alert/va-alert.css

https://1080-alert-safari-positioning--60f9b557105290003b387cd5.chromatic.com
The [issue reported ](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1080) describes a visual defect on the alert web component in Safari.
I could only reproduce this defect in Safari version 15.3 and earlier via Browserstack. I was unable to reproduce it in the latest version of Safari 15.6.1.
It appears that Safari 15.3  and earlier is calculating selector specificity differently between these two selectors where the selector prepended with the `.bg-only` class _should_ be the higher of the two but that doesn't seem to be the case for those Safari versions:
```
::slotted(:not([slot])) {
margin-top: 2rem;
}
.bg-only ::slotted(*) {
margin-top: 0;
}
```
Closes …

Fix visual defect in Safari for the va-alert component

---

packages/storybook/stories/va-alert.stories.jsx
packages/storybook/stories/va-banner.stories.jsx

https://alert-banner-cleanup--60f9b557105290003b387cd5.chromatic.com
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1089
This doesn't remove the `fullWidth` prop from the args table - only the "Full width" story.

Remove fullwidth alert story & update banner stories

---

packages/core/package.json
packages/core/src/i18n/i18n-setup.js
packages/core/src/i18n/translations/en.js
packages/core/src/i18n/translations/es.js
packages/core/src/i18n/translations/tl.js
packages/storybook/stories/va-on-this-page.stories.jsx
packages/web-components/package.json
packages/web-components/src/components/va-on-this-page/test/va-on-this-page.e2e.ts
packages/web-components/src/components/va-on-this-page/va-on-this-page.tsx

https://on-this-page-translation--60f9b557105290003b387cd5.chromatic.com
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1100
This PR adds translation functionality to the "On this page" component. It is the first component to offer Tagalog translation, and this doesn't have any impact on other components which don't have translations for the new language. The specific translation values used are from [this comment](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1100#issuecomment-1220903449).
- Storybook :eyes: 
- E2E updates
- Prerelease testing in `vets-website` and `content-build`
I modified the built HTML pages to so that the `<main>` tag had an appropriate `lang` attribute for each of the …

Translate "On this page" component

---

packages/core/package.json
packages/web-components/package.json
packages/web-components/src/components/va-checkbox/va-checkbox.css
packages/web-components/src/components/va-checkbox/va-checkbox.tsx

https://fix-va-checkbox-label-alignment--60f9b557105290003b387cd5.chromatic.com
As part of the Privacy Agreement web component work, it was discovered that the `va-checkbox` label was not aligning the same as the Sketch designs as described here: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/991#issuecomment-1240758320
Related: https://github.com/department-of-veterans-affairs/component-library/pull/524#discussion_r969881058
Sketch Reference: 
https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/symbols?g=Privacy%2520agreement
Storybook
**Old Alignment**
**New Alignment**

Fix va-checkbox label alignment.

---

packages/storybook/stories/va-featured-content.stories.jsx

https://featured-content-id--60f9b557105290003b387cd5.chromatic.com
A quick fix to repair the link to the featured content story in storybook.

add id to featured content story

---

packages/web-components/src/components/va-file-input/va-file-input.tsx

https://file-input-button-label-prop--60f9b557105290003b387cd5.chromatic.com
As part of the following [a11y review](https://github.com/department-of-veterans-affairs/va.gov-team/issues/46990), it was mentioned that some text was not being announced by NVDA. As part of that investigation, I noticed that the `label` prop on the `va-button` component was not set in `va-file-input`. This prop is mapped to the button's `aria-label`.  This pull request adds a value to that prop.
Storybook
N/A

Add label prop value to va-button in the va-file-input component

---

packages/web-components/src/utils/date-utils.spec.ts
packages/web-components/src/utils/date-utils.ts

https://month-date-validation-fix--60f9b557105290003b387cd5.chromatic.com
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1173
This updates the date validation so that if the day is invalid and we don't have a month value, we override the invalid day message with the invalid month message.
The valid day range was being calculated based on the month, since for some months 31 will be valid and for others it won't.

Fix month validation

---

packages/web-components/src/components/va-checkbox/va-checkbox.css
packages/web-components/src/components/va-date/va-date.css
packages/web-components/src/components/va-memorable-date/va-memorable-date.css
packages/web-components/src/mixins/form-field-error.css

https://va-checkbox-error-bold--60f9b557105290003b387cd5.chromatic.com
This update resolves the comment from the [Policy Agreement web component work](https://github.com/department-of-veterans-affairs/component-library/pull/524) as well as [this comment regarding aligning all of the components](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1115#issuecomment-1246993947).
- https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/991#issuecomment-1246993075
- https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1115#issuecomment-1246993947
> the team has discussed and decided that the error message will be in bold but not the checkbox label or the description. This means the …

Align web component labels, descriptions, and error message font weights.

---

packages/storybook/stories/FileInput.stories.jsx
packages/storybook/stories/additional-docs.js
packages/storybook/stories/va-file-input.stories.jsx
packages/web-components/src/components/va-file-input/va-file-input.tsx

https://1206-move-file-input-in-sidebar--60f9b557105290003b387cd5.chromatic.com
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1206
Storybook
---
---

Moving file input web component and React component in Storybook sidebar

---

packages/web-components/src/components/va-checkbox/va-checkbox.css

https://adjust-va-checkbox-error-margin--60f9b557105290003b387cd5.chromatic.com
This update will adjust the margin between the `#error-message` and the `label` element as discussed in the comment here: https://github.com/department-of-veterans-affairs/component-library/pull/524#issuecomment-1251085519
Storybook

Move margin from error-message to label in va-checkbox.

---

packages/web-components/src/components/va-select/va-select.css
packages/web-components/src/components/va-text-input/va-text-input.css

https://1133-va-text-input-font--60f9b557105290003b387cd5.chromatic.com
The reported issue says that the `va-text-input` was not displaying the correct font family and I also observed that the select element in `va-date` was not displaying the correct font family as well so this update includes both.
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1133
Storybook

Fix font family for input elements

---

packages/storybook/stories/va-radio.stories.jsx

https://va-radio-storybook-example-update--60f9b557105290003b387cd5.chromatic.com
An [issue](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1096) was reported for `va-button` that demonstrates events not firing correctly for keyboard events. After some testing, it seemed that the incorrect event may have been used and after reviewing Storybook, it wasn't completely clear which events to use in order to track option changes (making it seem like a defect). 
This PR updates the va-button Storybook page with a React binding example so that we can more clearly demonstrate using the `onVaValueChange` event to track option changes. 
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1096
Storybook

Updating va-button Storybook example to React binding

---

packages/web-components/src/components/va-privacy-agreement/test/va-privacy-agreement.e2e.ts

https://skip-privacy-agreement-shadowroot-tests--60f9b557105290003b387cd5.chromatic.com
Skipping the tests that are needing to access the shadowRoot of va-checkbox. The tests pass locally but fail in CI. Created a separate ticket to investigate: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1260

Skipping flakey shadowRoot tests in va-privacy-agreement

---

packages/web-components/src/components/va-alert/va-alert.css

https://60f9b557105290003b387cd5-ylsmqveawh.chromatic.com/?path=/docs/components-va-alert--background-only
Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/48200.
When using the `va-alert` web component with the `background-only` prop set to true
there is extra space between the content and the border on the left side of the alert versus on the right side
```jsx
<>
<div className="usa-alert usa-alert-info background-color-only claims-alert-status">
We’ve received your claim and are still adding some of your information.
Check back soon to see the complete details of your claim.
</div>
<va-alert background-only class="claims-alert-status">
We’ve received your claim and are still adding some of your information.
Check back soon to see the complete details of your …
```

va-alert background-only layout issue

---

packages/core/package.json
packages/storybook/stories/va-checkbox-group.stories.jsx
packages/storybook/stories/va-checkbox.stories.jsx
packages/storybook/stories/va-number-input.stories.jsx
packages/storybook/stories/va-radio.stories.jsx
packages/web-components/package.json
packages/web-components/src/components/va-checkbox-group/test/va-checkbox-group.e2e.ts
packages/web-components/src/components/va-checkbox-group/va-checkbox-group.tsx
packages/web-components/src/components/va-checkbox/test/va-checkbox.e2e.ts
packages/web-components/src/components/va-checkbox/va-checkbox.tsx
packages/web-components/src/components/va-number-input/va-number-input.tsx
packages/web-components/src/components/va-radio/test/va-radio.e2e.ts
packages/web-components/src/components/va-radio/va-radio.tsx

https://add-i18next-to-web-cpmponents--60f9b557105290003b387cd5.chromatic.com
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1297
This PR adds the following functionality:
- Adds translation functionality to component
- Adds Internationalization Story
- Adds Spanish, English and Tagalog languages to Internationalization Story
- Adds translation functionality to component
- Adds Internationalization Story
- Adds Spanish, English and Tagalog languages to Internationalization Story
- Adds translation functionality to component
- Adds Internationalization Story
- Adds Spanish, English and Tagalog languages to Internationalization Story
- Adds `Error` param to Internationalization Story
- Adds Tagalog language to Internationalization Story
- …

Translate "va-checkbox", "va-checkbox-group", "va-number-input" and "va-radio" component

---

.github/workflows/publish.yml
packages/css-library/package.json

https://css-library-prerelease--60f9b557105290003b387cd5.chromatic.com
This is getting us ready to be able to publish the `css-library` package by tagging a pre-release. We still haven't solved the problem of publishing it as a full release yet since we can't distinguish between release notes/changes for the `component-library` package and the `css-library` package.

Prepare css-library for publishing

---

packages/web-components/src/components.d.ts
packages/web-components/src/components/va-telephone/va-telephone.tsx

We now support numbers other than 3 or 10 digits.
https://telephone-contact-update--60f9b557105290003b387cd5.chromatic.com
Part of https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1298
This updates documentation which will be reflected in storybook and on design.va.gov

Update contact prop documentation

---

packages/core/src/i18n/translations/en.js
packages/core/src/i18n/translations/es.js
packages/storybook/stories/va-memorable-date.stories.jsx
packages/storybook/stories/va-text-input.stories.jsx
packages/web-components/src/components/va-memorable-date/test/va-memorable-date.e2e.ts
packages/web-components/src/components/va-memorable-date/va-memorable-date.tsx
packages/web-components/src/components/va-text-input/test/va-text-input.e2e.ts
packages/web-components/src/components/va-text-input/va-text-input.tsx

https://add-i18next-to-va-memorable-date--60f9b557105290003b387cd5.chromatic.com
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1292
This PR adds the following functionality:
- Adds translation functionality to component
- Adds Internationalization Story
- Adds Spanish to Internationalization Story
- Adds Spanish to Internationalization Story for minimum length
- Storybook :eyes: 
- E2E updates

Spanish translation for va-memorable-date & va-text-input

---

packages/storybook/stories/va-omb-info.stories.jsx
packages/web-components/src/components/va-omb-info/va-omb-info.tsx

https://storybook-move-va-omb-info--60f9b557105290003b387cd5.chromatic.com
- Moves `va-omb-info` from "Under Development" to the "Components" section in Storybook
- Updates the maturity to "Use: Best Practice"
Storybook

Update va-omb-info maturity and location in Storybook

---

packages/web-components/src/components.d.ts
packages/web-components/src/components/va-text-input/test/va-text-input.e2e.ts
packages/web-components/src/components/va-text-input/va-text-input.tsx

https://va-text-input-missing-autocomplete--60f9b557105290003b387cd5.chromatic.com
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1156
This PR adds the following functionality:
- Adds autocomplete prop to component
- Storybook :eyes: 
- E2E updates

Added autocomplete prop to va-text-input

---

packages/web-components/src/components/va-pagination/test/va-pagination.e2e.ts
packages/web-components/src/components/va-pagination/va-pagination.tsx

https://1332-aria-label-va-pagination--60f9b557105290003b387cd5.chromatic.com
Closes [1332](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1332)
- Updated unit tests to include `aria-label="Pagination"`

add aria-label to va-pagination navigation landmark

---

packages/storybook/.storybook/preview.js
packages/storybook/.storybook/style.scss

https://1331-storybook-u-s-w-d-s-style--60f9b557105290003b387cd5.chromatic.com
This PR includes a script that will dynamically update the `body` and `html` tags in Storybook when the URL contains the value "uswds" as well as some global CSS required to reset Formation values to pixels. 
**Note:** We will need to be mindful of the branch names we're creating as we are developing for USWDS v3. If the branch name has "uswds" in it, the Chromatic link will trigger the dynamic CSS update on all pages.
This branch does not include the work in progress for the USWDS v3 va-radio component so testing for this can be done on the Chromatic link generated from the discovery ticket draft PR (which includes the va-radio USWDS section):
https://github.com/department-of-veterans-affairs/component-library/ …

Add Storybook style overrides for USWDS v3 components

---

packages/web-components/package.json
packages/web-components/src/components/va-radio/va-radio.tsx

https://1324-radio-part--60f9b557105290003b387cd5.chromatic.com
Part of https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1324
Adding this to allow styling of the `va-radio` legend. ~Placing an H3 inside the legend may be the best solution, but we need to have a11y discussions first~ styling only, no headers inside
N/A
N/A

va-radio: add part attr to legend

---

packages/web-components/package.json
packages/web-components/src/components/va-textarea/va-textarea.css

https://1372-va-textarea-update--60f9b557105290003b387cd5.chromatic.com/?path=/docs/components-va-textarea--default
This PR will add the a11y css import so that `.sr-only` will work. It also adds font styling for the `textarea`. The styles used are [the same ones used for `va-input`](https://github.com/department-of-veterans-affairs/component-library/blob/main/packages/web-components/src/components/va-text-input/va-text-input.css#L24-L29) and also confirmed via [Sketch](https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/p/C6340B6C-F41E-423B-BDEA-B340A81C9714/canvas).
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1372
Storybook

va-textarea: Add a11y css import and font styles.

---

packages/web-components/src/components/va-radio-option/va-radio-option.css
packages/web-components/src/components/va-radio/va-radio.css

https://1345-va-radio-spacing--60f9b557105290003b387cd5.chromatic.com/?path=/docs/components-va-radio--default
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1345
Related Design Issue: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1346
Related Formation PR: https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/891
Storybook

Remove left padding and adjust option spacing in va-radio and va-radio-option

---

packages/storybook/stories/va-link.stories.jsx
packages/web-components/package.json
packages/web-components/src/components.d.ts
packages/web-components/src/components/va-link/test/va-link.e2e.ts
packages/web-components/src/components/va-link/va-link.css
packages/web-components/src/components/va-link/va-link.tsx

https://603-add-calendar-link-to-va-link--60f9b557105290003b387cd5.chromatic.com
Closes [Create a component for adding a calendar event #603](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/603) by adding a `Add to calendar` variation to the `va-link` component.
This is also referenced in[department-of-veterans-affairs/va.gov-team/issues/13011](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13011)
VAOS currently uses the `fa-regular` version of the calendar icon, this uses the `fa-solid` version of the icon. Currently unsure if it is possible to use the `fa-regular` version without a [pro license](https://fontawesome.com/v5/docs/web/advanced/css-pseudo-elements) for FontAwesome.
- e2e testing

Add add to calendar variation to va-link

---

packages/core/package.json
packages/web-components/package.json
packages/web-components/src/components/va-radio/test/va-radio.e2e.ts
packages/web-components/src/components/va-radio/va-radio.tsx

https://49541-req-radio--60f9b557105290003b387cd5.chromatic.com
Related to [#49539](https://github.com/department-of-veterans-affairs/va.gov-team/issues/49539)
We're using css to enlarge the legend text to `H3` size to match the design of our form. Recently, we decided to make this question required, and thus an `H3` sized required label also appeared; but we can't modify the style using css. 
This PR adds a `part` attribute to include the new USWDS elements, and also include hint and error messaging.
N/A
N/A

va-radio: add part attr to all elements

---

packages/core/package.json
packages/web-components/package.json
packages/web-components/src/components/va-modal/va-modal.css

https://z-index-n-vaModel-component--60f9b557105290003b387cd5.chromatic.com
Closes [1374](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1374)
Used dev-tools in https://staging.va.gov/my-health/secure-messages/folders

Bug: Increase z-index in vaModel component

---

packages/react-components/package.json
packages/storybook/package.json
packages/web-components/package.json
yarn.lock

https://update-formation-7.0.4--60f9b557105290003b387cd5.chromatic.com
This PR will update the [Formation](https://www.npmjs.com/package/@department-of-veterans-affairs/formation) dependencies to the latest version (7.0.4). 
As part of the work done in [1249](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1249), we want to also make sure the base color is set to `--color-base #212121` which was fixed in the latest version.
Storybook
N/A

Update Formation dependencies to latest version (7.0.4)

---

packages/css-library/src/tokens/flexbox.scss
packages/css-library/src/utilities/flexbox.scss

https://Add-missing-vads-align-self-class-to-css-library--60f9b557105290003b387cd5.chromatic.com
Closes [1403](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1403)
Locally

Add vads-align-self class to css-library

---

packages/web-components/src/components/va-alert/va-alert.css

https://1106-alert-close-focus-style--60f9b557105290003b387cd5.chromatic.com
This PR fixes the focus style missing from the va-alert close button. The component was not importing the button mixin which contained the focus styles. 
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1106
Storybook (Firefox and Chrome)
Chrome
Firefox

Add focus style to va-alert close button

---

packages/core/src/i18n/translations/tl.js
packages/storybook/stories/va-memorable-date.stories.jsx

https://1291-Tagalog-translations--60f9b557105290003b387cd5.chromatic.com
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1291
This PR adds the following functionality:
- Adds Tagalog to Internationalization Story for hint text
- Adds Tagalog to Internationalization Story for minimum length
- Storybook :eyes: 
- E2E updates

Tagalog translation for va-memorable-date & va-text-input

---

packages/web-components/src/components/va-textarea/test/va-textarea.e2e.ts
packages/web-components/src/components/va-textarea/va-textarea.tsx

https://1410-add-part-attr-to-textarea--60f9b557105290003b387cd5.chromatic.com
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1410
I added a "part" attribute to the label, textarea, and small (validation) elements, copying the pattern of "part" attributes in the va-text-input component. 
E2e tests for the textarea component have been updated to include the "part" attribute. 
No UI changes.

Add part attribute to textarea component (#1410)

---

packages/storybook/.storybook/manager-head.html

https://dst-storybook-favicons--60f9b557105290003b387cd5.chromatic.com
There is no related ticket to this update. I just noticed that the design.va.gov Storybook instance was not displaying a favicon instead of one for VA. This PR adds a `manager-head.html` file which will allow us to add additional meta items to the `head` markup of Storybook.
Storybook

Add VA favicons to Storybook

---

packages/core/package.json
packages/storybook/stories/va-pagination.stories.jsx
packages/web-components/package.json
packages/web-components/src/components/va-pagination/test/va-pagination.e2e.ts
packages/web-components/src/components/va-pagination/va-pagination.css
packages/web-components/src/components/va-pagination/va-pagination.tsx

https://1408-pagination-a11y--60f9b557105290003b387cd5.chromatic.com
This PR addresses some accessibility issues mentioned in the ticket below. The word `prev` was updated to `previous` and the `aria-labels` were tested using Voice Control on mac to make sure that the component could be used entirely by voice control. The `aria-labels` were mostly just refactored and the word "page" added where relevant for using the voice controls.
Voice Commands that are working:
- "Click page 3" ✅  (and other page specific numbers)
- "Click previous page" ✅ 
- "Click next page" ✅ 
The command structure that I was unable to make work:
- "Click 3" ❌ 
It also fixes a bug where the selected page was not losing its active style (making it appears like two pages were selected at the same time). 
Related …

Accessibility updates to va-pagination to support Voice Control

---

packages/core/src/i18n/translations/en.js
packages/core/src/i18n/translations/es.js
packages/core/src/i18n/translations/tl.js
packages/web-components/src/components/va-date/test/va-date.e2e.ts
packages/web-components/src/components/va-memorable-date/test/va-memorable-date.e2e.ts
packages/web-components/src/utils/date-utils.spec.ts
packages/web-components/src/utils/date-utils.ts

https://1416-error-message-i18n--60f9b557105290003b387cd5.chromatic.com
Closes [1614](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1416)
Translation was added to the memorable date but no translation was added to the date validator utils used by the memorable date component. This PR adds all translations to the date validators. 
Locally
Storybook
Since the translation validators only react when the validation is been performed, it was easier to use a video to test all permutations
https://user-images.githubusercontent.com/55560129/213753309-19e1a5d9-dab7-4222-9cf9-1c3b7d4cda97.mov

Add translation to date error message validators

---

packages/core/package.json
yarn.lock

https://1415-react-18-upgrade--60f9b557105290003b387cd5.chromatic.com
Closes [1415](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1415)
Closes [1479](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1479)
Fixes [dependency issue](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1479) of a fresh install of `vets-design-system-documentation`
Locally
Run all installation to ensure nothing breaks
1. `cd packages/web-components/`
1. `yarn install`
2. `yarn build`
3. `yarn build-bindings` (build React bindings)
2. `cd ../react-components/`
1. `yarn install`
2. `yarn build`
3. `cd ../core/`
1. `yarn install`
2. `yarn build`
4. `cd ../storybook/`
1. `yarn install`
2. `yarn …

Upgrade React to v18 in component-library

---

packages/core/package.json
packages/web-components/package.json
packages/web-components/src/mixins/form-field-error.css

https://text-input-error-style--60f9b557105290003b387cd5.chromatic.com/?path=/docs/components-va-text-input--error
We lost the red and bold style for the error message in a [previous update](https://github.com/department-of-veterans-affairs/component-library/pull/615#discussion_r1098917790) so this is adding it back:
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1537
Storybook

Fix va-text-input error message style

---

packages/storybook/stories/va-text-input.stories.jsx
packages/web-components/src/components.d.ts
packages/web-components/src/components/va-text-input/test/va-text-input.e2e.ts
packages/web-components/src/components/va-text-input/va-text-input.tsx

https://23381-text-input-aria-message--60f9b557105290003b387cd5.chromatic.com
During an [Axe scan in an e2e test](https://github.com/department-of-veterans-affairs/vets-website/pull/23381), we discovered that the new prop name `aria-describedby-message` in va-text-input was failing an accessibility scan because it was not a valid aria attribute name.
I was able to confirm this locally as well:
This PR changes the prop name to `message-aria-describedby` so that it passes the a11y scan and I have also updated our component tests to check for this as well.
Confirmed that it is still working with VoiceOver.
Original issue: https://github.com/department-of-veterans-affairs/va.gov-team/issues/24502
Storybook
VoiceOver

va-text-input: Update aria message prop name

---

packages/core/package.json
packages/web-components/package.json
packages/web-components/src/components/va-official-gov-banner/va-official-gov-banner.scss

https://banner-official-gov-close-icon--60f9b557105290003b387cd5.chromatic.com
This updates the close icon "X" to what is currently displayed in the [USWDS v3 version](https://designsystem.digital.gov/components/banner/). There is no associated issue ticket. We just noticed that it was not [matching the design](https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/p/B87991F3-2AC5-4C6D-94AE-43B5A4B2EFD3/canvas) (the close icon was displaying much smaller than it should have been).
Storybook

va-official-gov-banner: Update mobile close icon so it matches USWDS

---

packages/storybook/stories/ExpandingGroup.stories.jsx
packages/storybook/stories/additional-docs.js

https://1378-move-expanding-group-deprecated--60f9b557105290003b387cd5.chromatic.com
Related issue: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1378
Storybook

Move ExpandingGroup React component to deprecated section in Storybook

---

packages/core/package.json
packages/storybook/stories/va-memorable-date.stories.jsx
packages/web-components/package.json
packages/web-components/src/components.d.ts
packages/web-components/src/components/va-memorable-date/test/va-memorable-date.e2e.ts
packages/web-components/src/components/va-memorable-date/va-memorable-date.css
packages/web-components/src/components/va-memorable-date/va-memorable-date.tsx

https://54215-memorable-hints--60f9b557105290003b387cd5.chromatic.com
See [#54215](https://github.com/department-of-veterans-affairs/va.gov-team/issues/54215)
Added e2e test for hint property rendering

va-memorable-date: add hint property

---

packages/storybook/.storybook/style.scss

https://storybook-formation-v3-css-overrides--60f9b557105290003b387cd5.chromatic.com
Some v3 override styles were accidentally removed and this PR is adding them back. Without these styles, Storybook displays buttons and labels at the wrong base font size:
Related PR: https://github.com/department-of-veterans-affairs/component-library/pull/636
Storybook
**Before**
**After**

Adding Storybook v3 override styles

---

packages/web-components/package.json
packages/web-components/src/components/va-button/va-button.css
packages/web-components/src/global/_settings.scss
packages/web-components/src/global/variables.css
packages/web-components/src/mixins/focusable.css

https://1585-va-button-colors--60f9b557105290003b387cd5.chromatic.com
This PR updates the `va-button` component states so that they match what is in Sketch.
Sketch: https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/p/5317C603-D6BD-4AFF-84E6-151F7A197B91/canvas
Related ticket: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1585
Related PR: https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/909
Storybook
**Default**
--color-primary (#0071bb)
**Hover**
--color-primary-darker (#003e73)
**Focus**
--color-primary-darker (#003e73)
**Active**
--color-primary-darkest (#112E51)
**Default**
bg: --color-white
Txt & border: --color-primary #0071BB
**Hover**
bg: --color-gray-cool-light #DCE4EF
Txt & border: …

Update va-button states to match Sketch 

---

packages/react-components/package.json
packages/storybook/package.json
packages/web-components/package.json
yarn.lock

https://update-formation-v7.0.5--60f9b557105290003b387cd5.chromatic.com
This updates Formation to the latest version v7.0.5. This version adds the following updates:
- https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/909
- https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/908
Storybook
N/A

Update Formation to v7.0.5

---

packages/web-components/package.json
packages/web-components/src/components/va-button/va-button.css

https://1585-secondary-button-hover--60f9b557105290003b387cd5.chromatic.com
Updates the va-button secondary hover state from `--color-primary-darkest` to `--color-primary-darker`.
Sketch: https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/p/5317C603-D6BD-4AFF-84E6-151F7A197B91/canvas
Closes https://github.com/department-of-veterans-affairs/component-library/pull/642
Storybook
--color-primary-darker   #003e73

va-button: Update the secondary hover color

---

packages/core/package.json

https://core-version-bump-v14.0.0--60f9b557105290003b387cd5.chromatic.com
I forgot to bump the `core` version as part of this PR: https://github.com/department-of-veterans-affairs/component-library/pull/650
With the removal of a React component, that was a major release bump so I'm doing that here and will create a release for it afterward.
Storybook
N/A

Bump core version to v14.0.0

---

packages/storybook/stories/va-featured-content.stories.jsx

https://Fix-featured-content--60f9b557105290003b387cd5.chromatic.com
The code display in `Featured content` is missing from Storybook. This PR fixes that.
Locally
Storybook

Fixed the missing code in Featured content

---

.github/workflows/codeql.yml

https://codeql-v2--60f9b557105290003b387cd5.chromatic.com
This PR updates references from v1 to v2 in the CodeQL workflow file based on these docs: https://github.blog/changelog/2023-01-18-code-scanning-codeql-action-v1-is-now-deprecated/
We are not receiving PR errors yet but this preemptively updates codeql to v2 similar to what we needed to do for the documentation repo: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/1639
Checked that this PR passes CodeQL test
N/A

Update to codeql v2

---

README.md

https://build-steps-readme-update--60f9b557105290003b387cd5.chromatic.com
This PR will add an optional step to the web components build step `yarn watch:stencil` which will watch for changes in the stencil component files and refresh the build.

Add yarn watch:stencil to build steps

---

packages/storybook/stories/DropDownPanel.stories.jsx
packages/storybook/stories/ExpandingGroup.stories.jsx
packages/storybook/stories/OMBInfo.stories.jsx
packages/storybook/stories/SystemDownView.stories.jsx
packages/storybook/stories/additional-docs.js
packages/web-components/src/components/va-alert-expandable/test/va-alert-expandable.e2e.ts

https://move-deprecated-react-c--60f9b557105290003b387cd5.chromatic.com
Closes [1637](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1637)
Storybook

Move all react components to deprecated section

---

packages/storybook/stories/DropDownPanel.stories.jsx
packages/storybook/stories/ExpandingGroup.stories.jsx
packages/storybook/stories/SystemDownView.stories.jsx
packages/storybook/stories/additional-docs.js

https://storybook-deprecated-icons--60f9b557105290003b387cd5.chromatic.com
Storybook
**Before**
**After**

Fix maturity scale icons for deprecated React components

---

packages/storybook/stories/va-number-input-uswds.stories.jsx
packages/web-components/package.json
packages/web-components/src/components.d.ts
packages/web-components/src/components/va-number-input/test/va-number-input.e2e.ts
packages/web-components/src/components/va-number-input/va-number-input.scss
packages/web-components/src/components/va-number-input/va-number-input.tsx
packages/web-components/src/components/va-text-input/test/va-text-input.e2e.ts

https://1625-uswds-va-number-input--60f9b557105290003b387cd5.chromatic.com/?path=/docs/uswds-va-number-input--default
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1625
Below is the Sketch file for `va-text-input`. This component does not have all of the same states but it inherits the same general style modules for USWDS:
- https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/a/nRYozkW
Storybook

 Add va-number-input USWDS v3 variation

---

packages/web-components/package.json
packages/web-components/src/components/va-button-pair/va-button-pair.scss

https://1673-button-pair-responsive-bug--60f9b557105290003b387cd5.chromatic.com
---
Update CSS so that the continue variation is responsive, and the buttons stack in mobile. Also update continue variation styles to match other button pair styles
Closes [1673](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1673)
- Story Book
- Tested in Chrome, Firefox, Edge, Safari
- Mobile responsiveness tested in all above browsers
Desktop
Mobile
- [x ] Buttons do not overflow the web view in mobile
- [x ] Mobile styles resemble those of other button pair variations
- [x ] Styles remain constant for other button pair variations
- [x ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)

1673 button pair responsive bug

---

packages/web-components/package.json
packages/web-components/src/components/va-accordion/va-accordion.e2e.ts
packages/web-components/src/components/va-accordion/va-accordion.tsx

https://1663-accordion-button-accessibility--60f9b557105290003b387cd5.chromatic.com
---
Update 'Expand all' and 'Close all' button on the accordion to include `aria-controls` and `aria-expanded` attributes.
Closes [1663](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1663)
- Tested with Chrome ChromeVox extension and Mac Voice-over
- No visual changes
- [ x] The expand/collapse button includes a aria-controls attribute that is set to a space separated list containing the IDs of all accordion item button IDs
- [ x] The expand/collapse button includes the aria-expanded attribute that changes value when the button is clicked
- [ x] Documentation has been updated, if applicable
- [ x] A link has been provided to the originating GitHub issue (or …

add aria-controls and aria-expanded to expand/collapse all button

---

.yarn/versions/916472c4.yml
packages/core/package.json
packages/web-components/package.json
packages/web-components/src/components/va-loading-indicator/va-loading-indicator.tsx

https://asteele-dispose-of-loading-indicator-observer-1664--60f9b557105290003b387cd5.chromatic.com
---
Closes [#1664](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1664)
Ran 'yarn test'

Dispose of loading indicator observer - 1664

---

packages/core/package.json
packages/web-components/package.json
packages/web-components/src/components/va-accordion/va-accordion-item.css

https://va-accordion-item&#x2F;alignment-patch--60f9b557105290003b387cd5.chromatic.com
- Fixing a bug that was introduced by a CSS Change.

(bug) fixed styling issue for sub header

---

packages/storybook/stories/va-text-input-uswds.stories.jsx
packages/storybook/stories/va-text-input.stories.jsx

https://update-va-textinput-1334--60f9b557105290003b387cd5.chromatic.com/?path=/docs/components-va-text-input--with-hint-text
https://update-va-textinput-1334--60f9b557105290003b387cd5.chromatic.com/?path=/docs/uswds-va-text-input--with-hint-text
Closes [Update va-textinput web component #1334](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1334)
Tested in Storybook in Safari, Edge, Firefox and Chrome

va-textinput add inline hint to storybook

---

packages/storybook/stories/va-accordion.stories.jsx
packages/web-components/package.json
packages/web-components/src/components/va-accordion/va-accordion-item.css
packages/web-components/src/components/va-accordion/va-accordion-item.e2e.ts
packages/web-components/src/components/va-accordion/va-accordion-item.tsx

https://1709-accordion-subheader-icon--60f9b557105290003b387cd5.chromatic.com
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1709
- Storybook
- unit
- screen sizes
I still need to update the unit tests and documentation. But I am getting a review early

Add icon support to va-accordion-item subheader

---

packages/web-components/package.json
packages/web-components/src/components/va-text-input/va-text-input.scss

https://asteele-text-input-label-font-size--60f9b557105290003b387cd5.chromatic.com
---
Relates to [#906](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/906)
- Tested locally using Brave and UXPin

Text input label font-size fix for UXPin

---

packages/core/package.json
packages/web-components/package.json
packages/web-components/src/components/va-alert/va-alert.scss
packages/web-components/src/global/_formation_overrides.scss

https://1741-baner-alert-border--60f9b557105290003b387cd5.chromatic.com
A bug was introduced when we added the v3 variation to `va-alert`. This component is used in `va-banner` and it was displaying a left border when before there wasn't one.
This update makes sure that the left border is not displayed when the `va-banner` component is being used:
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1728
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1741
Storybook (checked both va-banner, va-alert (v1), and va-alert (v3)

Fix va-banner displaying left border

---

packages/storybook/stories/va-alert.stories.jsx

https://add-sign-in-to-start-your-application-story-to-alert-1731--60f9b557105290003b387cd5.chromatic.com
Closes 1731
Verified in Chrome on localhost

Adds a Sign in to start your application story to Alert.

---

packages/core/package.json
packages/web-components/package.json
packages/web-components/src/components/va-loading-indicator/va-loading-indicator.tsx

https://asteele-loading-indicator-hotfix--60f9b557105290003b387cd5.chromatic.com
---
Hotfix to stop Sentry errors related to disconnecting the MutationObserver within the va-loading-indicator. Removing the code to manually disconnect the MutationObserver as the disconnect was sometimes being called after the MO had already been garbage collected, leading to 'undefined' errors.
No testing done, just stopped trying to disconnect the observer after it has already been garbage collected.

Hotfix to loading indicator observer disconnect

---

packages/web-components/package.json
packages/web-components/src/global/_formation_overrides.scss

https://asteele-uxpin-override-906--60f9b557105290003b387cd5.chromatic.com
---
Closes [#906](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/906)
Works in Brave and Storybook

Button icon font size override

---

packages/react-components/package.json
packages/storybook/package.json
packages/web-components/package.json
yarn.lock

https://1706-formation-update--60f9b557105290003b387cd5.chromatic.com
Update formation to fix action link icon underline bug
<https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1706>
Chrome, safari browser testing

Formation - 7.0.7

---

packages/core/package.json
packages/storybook/stories/va-additional-info-uswds.stories.jsx
packages/web-components/package.json
packages/web-components/src/components.d.ts
packages/web-components/src/components/va-additional-info/test/va-additional-info.e2e.ts
packages/web-components/src/components/va-additional-info/va-additional-info.css
packages/web-components/src/components/va-additional-info/va-additional-info.tsx

https://1695-additional-info-v3--60f9b557105290003b387cd5.chromatic.com
This pull request adds a new additional info component. CSS sizes defined in rem units to px units
Sketch: https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/symbols?g=Additional%2520info%252Fuswds-DO%2520NOT%2520USE%252FMVP#Version
Closes [1695](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1695)
Storybook
Chrome/Edge/Mozilla

feat: Additional info v3

---

README.md

https://asteele-update-releasing-readme-1734--60f9b557105290003b387cd5.chromatic.com
---
Closes [#1734](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1734)

Updates to "Releasing" section of README - 1734

---

packages/storybook/stories/va-text-input-uswds.stories.jsx
packages/storybook/stories/va-text-input.stories.jsx
packages/web-components/package.json
packages/web-components/src/components.d.ts
packages/web-components/src/components/va-text-input/va-text-input.scss
packages/web-components/src/components/va-text-input/va-text-input.tsx
packages/web-components/src/mixins/uswds-input-width.scss

https://1712-va-text-input-width--60f9b557105290003b387cd5.chromatic.com
This PR adds a `width` prop that sets a corresponding USWDS input width class (for both v1 and v3):
https://designsystem.digital.gov/components/text-input/#component-variants-text-input
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1712
Storybook
Browserstack iOS

Add width option to va-text-input

---

packages/web-components/package.json
packages/web-components/src/components/va-checkbox/va-checkbox.scss

https://1713-vacheckbox-issue--60f9b557105290003b387cd5.chromatic.com
This PR fixes two issues with the VaCheckbox web-component:
1. Fix issue where cursor showed as pointer on bottom half of checkbox and default cursor on top half of checkbox. Now it shows as a pointer
2. Update checkbox to have a white background so it looks the same on darker backgrounds
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1713
Storybook
Chrome

1713 vacheckbox issue

---

packages/storybook/stories/va-number-input-uswds.stories.jsx
packages/storybook/stories/va-number-input.stories.jsx
packages/web-components/package.json
packages/web-components/src/components.d.ts
packages/web-components/src/components/va-number-input/va-number-input.tsx

https://1771-va-num-input-width--60f9b557105290003b387cd5.chromatic.com
This PR adds a `width` prop that sets a corresponding USWDS input width class (for both v1 and v3). It mimics the same approach that was taken for va-text-input: https://github.com/department-of-veterans-affairs/component-library/pull/707
https://designsystem.digital.gov/components/text-input/#component-variants-text-input
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1771
Storybook
Browserstack iOS

Add width option to va-number-input

---

packages/storybook/stories/va-memorable-date-uswds.stories.jsx
packages/web-components/package.json
packages/web-components/src/components/va-memorable-date/va-memorable-date.tsx

https://1845-va-memorable-date-month-select-fix--60f9b557105290003b387cd5.chromatic.com
---
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1845
Related to https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team/60060
Tested in storybook using Chrome with with setting values:  '2022-04-19', '2022-4-19', '2022-12-19', '2022-08-19', '2022-1-19' and all values work.

Allow month to be selected for va-memorable-date using 'month-select'

---

package.json

https://chromatic-publish-error--60f9b557105290003b387cd5.chromatic.com
Our Chromatic github workflow for publishing Storybook previews stopped working a few days ago. There is [an issue reported to the chromatic-cli](https://github.com/chromaui/chromatic-cli/issues/766) that is similar to what we are experiencing:
The resolution mentioned in that issue is to add an empty `"scripts": {},` tag to the root package.json file but this did not work in our case (see the failure below in commit [ffb57dc](https://github.com/department-of-veterans-affairs/component-library/pull/721/commits/ffb57dcdb7ee5db43f783a1bdd565b02ca01b8ee)). 
Adding a "fake script" _does_ work though (which is how this PR is passing at the moment):
```
"scripts": {
"chromatic-bridge": "echo \"Nothing to see here\""
},
``` …

Update for Chromatic Publish Action

---

packages/web-components/src/components/va-date/test/va-date.e2e.ts
packages/web-components/src/components/va-date/va-date.tsx
packages/web-components/src/components/va-memorable-date/test/va-memorable-date.e2e.ts
packages/web-components/src/components/va-memorable-date/va-memorable-date.tsx
packages/web-components/src/utils/date-utils.spec.ts
packages/web-components/src/utils/date-utils.ts

https://allow-paste-in-date-component--60f9b557105290003b387cd5.chromatic.com
Closes [va-memorable-date doesn't allow for copy/paste/cut keyboard actions #1775](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1775)
Previously the date inputs restricted what key presses would be registered in order to disallow any non-numeric input. This PR removes that restriction and adds new validation to prevent incorrect inputs.
Tested in Chrome and Safari on Mac

Allow date field copy/paste with keyboard shortcut

---

packages/web-components/src/components/va-notification/va-notification.scss

https://bug-va-notification-button-padding--60f9b557105290003b387cd5.chromatic.com
---
Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/60661
- visually on local (Storybook)
- all e2e tests pass
| -- | -- |
| ![Screenshot 2023-06-21 at 3 33 56 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/45603961/16ce7f97-625e-4d9d-92f1-1fb46971e1d4) |  ![Screenshot 2023-06-22 at 10 33 15 …

va-notification: align CLOSE text with card padding

---

packages/web-components/package.json
packages/web-components/src/components/va-radio-option/va-radio-option.scss

https://va-radio-option-max-width-patch--60f9b557105290003b387cd5.chromatic.com
Change `width` from fixed width to `max-width` and added `width: auto` to address 400% zoom accessibility testing. 
Closes [#1797](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1797)
- Chrome
- Storybook

Accessibility fix for radio option width for va-radio-option.scss

---

packages/web-components/package.json
packages/web-components/src/components/va-table/va-table.tsx

https://1821-table-mutation-observer--60f9b557105290003b387cd5.chromatic.com
It was [brought to our attention](https://dsva.slack.com/archives/C01DBGX4P45/p1687899378028149) that the pagination update previously made was not fully working with a certain data set. I was able to reproduce this issue locally based on this [codesandbox example](https://codesandbox.io/s/nervous-nightingale-ng7rp7?file=/src/App.js).
The issue seemed to be related to the way the data is provided as an array of objects rather than just arrays. In our original testing, I did not fully check these different data structures with the pagination.
Adding the `characterData` option to the observe() method makes sure that we are monitor subtrees in the slot as well as its descendants. Reference: …

va-table: Update MutationObserver for pagination

---

packages/web-components/package.json
packages/web-components/src/components/va-accordion/va-accordion-item.e2e.ts
packages/web-components/src/components/va-accordion/va-accordion-item.tsx

https://asteele-accordion-tabindex-fix-1875--60f9b557105290003b387cd5.chromatic.com
Closes #[1875](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1875)
No testing done.

Removing accordion-item tabindex

---

packages/core/src/i18n/translations/en.js
packages/core/src/i18n/translations/es.js
packages/core/src/i18n/translations/tl.js

https://1791-memorable-date-numbers--60f9b557105290003b387cd5.chromatic.com
Replace "two" and "four" in the en.js translation bundle with "2" and "4"
Task: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1791
Local browser testing in chrome
Before:
After:

va-memorable-date: Change two and four to 2 and 4

---

packages/web-components/src/components/va-radio/va-radio.scss

https://1780-update-va-radio-margin-top--60f9b557105290003b387cd5.chromatic.com
---
Make the margin top of va-radio component consistent with the corresponding USWDS component
Task: https://app.zenhub.com/workspaces/platform-design-system-5f8de67192551b0012ebb802/issues/gh/department-of-veterans-affairs/vets-design-system-documentation/1780 
local testing in chrome
Before:
After:

sync va-radio margin top with uswds

---

packages/web-components/src/components/va-checkbox-group/va-checkbox-group.scss

https://1780-update-va-checkbox-group-margin-top--60f9b557105290003b387cd5.chromatic.com
---
Make the margin top of va-checkbox-group component consistent with the corresponding USWDS component
Task: https://app.zenhub.com/workspaces/platform-design-system-5f8de67192551b0012ebb802/issues/gh/department-of-veterans-affairs/vets-design-system-documentation/1780
local testing in chrome
Before:
After:

sync margin top of checkbox-group with uswds

---

packages/storybook/stories/va-alert-uswds.stories.jsx
packages/storybook/stories/va-alert.stories.jsx

https://update-va-alert-storybook--60f9b557105290003b387cd5.chromatic.com
This PR adds back the sign-in button (instead of action) to the "Sign in to start your application" example in Storybook as well as adds that example to the USWDS variation. We are changing it back to button because the sign-in is a modal which should be triggered by a [button instead of a link](https://design.va.gov/components/button/#when-to-use-a-button).
Related https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/908
Storybook locally

va-alert Storybook: Remove action link and add button for sign-in prompt

---

packages/core/package.json
packages/web-components/package.json
packages/web-components/src/components/va-notification/test/va-notification.e2e.ts
packages/web-components/src/components/va-notification/va-notification.tsx

https://61157-va-notification-role--60f9b557105290003b387cd5.chromatic.com
Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/61157
- On the `<va-notification>` web-component, remove the `role="alert"` attribute so it does not read every `va-notification` immediately on page load
- Manual testing on chrome/safari with VoiceOver utility on Mac
Before (with all notifications):
https://github.com/department-of-veterans-affairs/component-library/assets/15200011/84c572c0-ded2-4d86-8db9-2bdacd6443f7
After removing role="alert":
https://github.com/department-of-veterans-affairs/component-library/assets/15200011/e2cf44c0-6e22-4b46-89e1-d160aae39907

61157 - Remove role="alert" from va-notification. Update package.json versions

---

packages/storybook/stories/va-modal.stories.jsx
packages/web-components/package.json
packages/web-components/src/components.d.ts
packages/web-components/src/components/va-button-pair/va-button-pair.scss

https://59774-cut-off-buttons--60f9b557105290003b387cd5.chromatic.com
- Change button widths to max-widths to make them flexible and able to fit inside modals
- Give buttons a flex: 1 1 auto so they will fill the space available
- Define a width on the button pair to constrain the width when not inside a modal
- Added a story on the va-modal to test with and verify changes
Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/59774
- Local testing in Chrome, Firefox, Safari, and Edge (Both Modal and ButtonPair)
Button Pair: 
Button Pair inside modal:

Update styles to fix buttons from overflowing on modals (non-uswds)

---

packages/web-components/src/components/va-date/va-date.tsx
packages/web-components/src/components/va-memorable-date/va-memorable-date.tsx
packages/web-components/src/utils/date-utils.spec.ts
packages/web-components/src/utils/date-utils.ts

https://1834-zero-pad--60f9b557105290003b387cd5.chromatic.com
While monitoring Sentry errors, we noticed quite a large number of [`undefined is not a constructor (evaluating 'new Intl.NumberFormat(j,p)')` errors](http://sentry.vfs.va.gov/organizations/vsp/issues/?project=4&query=is%3Aunresolved+Intl.NumberFormat&statsPeriod=90d) (~3k events in the past 90 days). See [#1834](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1834).
This happens because the [`Intl.NumberFormat` requires modern up-to-date browsers](https://caniuse.com/?search=Intl.NumberFormat), and we have Veterans still using Safari v9. We can't use [`padStart` since it also requires Safari v10+](https://caniuse.com/?search=padStart)
This PR switches from using `intl.NumberFormat` to …

va-date & va-memorable-date: Switch to zero pad function

---

packages/web-components/src/components.d.ts
packages/web-components/src/components/va-memorable-date/test/va-memorable-date.e2e.ts
packages/web-components/src/utils/date-utils.spec.ts
packages/web-components/src/utils/date-utils.ts

https://1593-mem-date-feb--60f9b557105290003b387cd5.chromatic.com
The max number of days for the month of February is hard-coded to be the length of the `twentyNineDays` array for non-leap years (which is 29). There isn't a 28 days array, so I opted for a simpler method by calculating the days. If the month or year are undefined, it returns 31 as the max - which seems like a reasonable fallback (instead of zero). This PR fixes one portion of issue [#1593](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1593), which is also referenced in [#61363](https://github.com/department-of-veterans-affairs/va.gov-team/issues/61363)
Updated utility tests
|--------|-------|
| ![date-error-feb-before](https://github.com/department-of-veterans-a …

va-memorable-date: Fix days of month calculation

---

packages/storybook/stories/va-memorable-date-uswds.stories.jsx
packages/storybook/stories/va-memorable-date.stories.jsx
packages/web-components/package.json
packages/web-components/src/components/va-memorable-date/test/va-memorable-date.e2e.ts
packages/web-components/src/components/va-memorable-date/va-memorable-date.tsx
packages/web-components/src/utils/date-utils.spec.ts
packages/web-components/src/utils/date-utils.ts

https://1593-mem-date-fixes--60f9b557105290003b387cd5.chromatic.com
When custom validation applies a custom error message, and the date within the `va-memorable-date` is valid, blurring any of the inputs a second time would result in the custom error message being removed. This appears to be a race condition of the internal validation code removing the error and the external validation code adding the custom error.
To fix this issue, the emitted blur event (which triggers the custom validation), was moved _before_ the internal validation check and the internal validation only add & remove empty, and internal validation errors. Fixes one portion of issue [#1593](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1593), which is also referenced in …

va-memorable-date: Fix clearing error message bug

---

packages/web-components/package.json
packages/web-components/src/components/va-back-to-top/test/va-back-to-top.e2e.ts
packages/web-components/src/components/va-back-to-top/va-back-to-top.css
packages/web-components/src/components/va-back-to-top/va-back-to-top.tsx

https://899-back-to-top-a11y--60f9b557105290003b387cd5.chromatic.com/?path=/docs/components-va-back-to-top--default
Sketch: https://www.sketch.com/s/73212626-acc4-47e6-acd8-d4e2f5a98372
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/899
Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/58413
Related https://github.com/department-of-veterans-affairs/va.gov-team/issues/60812
Storybook
Voiceover
vets website locally
Vets Website Demo
https://github.com/department-of-veterans-affairs/component-library/assets/872479/f82c896a-6f12-416e-97df-6a8520399024

va-back-to-top: Change button to anchor link

---

packages/storybook/stories/va-notification.stories.jsx
packages/web-components/package.json
packages/web-components/src/components.d.ts
packages/web-components/src/components/va-notification/test/va-notification.e2e.ts
packages/web-components/src/components/va-notification/va-notification.tsx

https://notification-add-datetime-prop--60f9b557105290003b387cd5.chromatic.com
---
This PR adds a dateTime prop to the `va-notification` web component so that and `aria-describedby` label for the headline can be unique and describe content of the notification more clearly. 
- closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/61399 (Authenticated Experience)
- also closes https://github.com/department-of-veterans-affairs/va.gov-team/ …

va-notification - add dateTime prop

---

packages/storybook/stories/va-checkbox-uswds.stories.jsx
packages/storybook/stories/va-checkbox.stories.jsx
packages/web-components/package.json
packages/web-components/src/components.d.ts
packages/web-components/src/components/va-checkbox/test/va-checkbox.e2e.ts
packages/web-components/src/components/va-checkbox/va-checkbox.tsx

https://1852-chkbx-msg-aria--60f9b557105290003b387cd5.chromatic.com
add `message-aria-describedby` property to enable adding an optional message for screen readers.
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1852
- Mac Voice-over 
- Local testing done in Chrome
- No visual changes made

va-checkbox - add message-aria-describedby property for optional additional message for screen readers

---

packages/storybook/stories/va-text-input-uswds.stories.jsx
packages/web-components/package.json
packages/web-components/src/components/va-text-input/va-text-input.tsx

https://1893-uswds-described-by--60f9b557105290003b387cd5.chromatic.com
Add ability to set an additional message for screen readers to the USWDS text input
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1893
- Mac Voice-over
- Local testing in Chrome
- Non-visual changes

va-text-input (USWDS) add aria-described-by optional message

---

packages/web-components/package.json
packages/web-components/src/components/va-modal/test/va-modal.e2e.ts
packages/web-components/src/components/va-modal/va-modal.tsx

https://1892-va-modal-analytics--60f9b557105290003b387cd5.chromatic.com
The primary and secondary buttons in va-modal were not firing analytics events so this PR adds that functionality.
Related https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1892
Related https://github.com/department-of-veterans-affairs/vets-website/pull/24944
Locally in Storybook
Added tests for analytics event

va-modal: Add button click analytics

---

packages/storybook/stories/va-checkbox-uswds.stories.jsx
packages/storybook/stories/va-radio-uswds.stories.jsx
packages/web-components/package.json
packages/web-components/src/components/va-checkbox/va-checkbox.scss
packages/web-components/src/components/va-radio-option/va-radio-option.scss

https://1902-chkbox-radio-bg--60f9b557105290003b387cd5.chromatic.com
override the white background color on .usa-checkbox and .usa-radio to be transparent.
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1902
- local testing in Chrome, Safari, Firefox, and Edge
Before:
After:

va-checkbox, va-radio - override .usa white background color to be transparent

---

packages/css-library/tokens/color.json
packages/css-library/tokens/fonts.json
packages/storybook/stories/va-alert-uswds.stories.jsx
packages/storybook/stories/va-alert.stories.jsx
packages/storybook/stories/va-button-uswds.stories.jsx
packages/storybook/stories/va-button.stories.jsx
packages/web-components/package.json
packages/web-components/src/components.d.ts
packages/web-components/src/components/va-button/va-button.scss
packages/web-components/src/components/va-button/va-button.tsx
packages/web-components/src/global/_variables.scss
packages/web-components/src/global/variables.css

https://1789-primary-alt-btn--60f9b557105290003b387cd5.chromatic.com
Add an alternate primary button variation with a green background, update va-button stories and include an example on the va-alert stories using the variation. Update the core colors to include the required greens.
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1789
- Local browser testing in Chrome, Firefox, Edge, and Safari

va-button - add alternate (green) version to primary button

---

packages/web-components/package.json
packages/web-components/src/components/va-loading-indicator/va-loading-indicator.tsx

https://asteele-fix-for-null-loading-nodes-1952--60f9b557105290003b387cd5.chromatic.com
---
Prevents an error when nodes are either null or don't have a tagName
Closes [#1952](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1952)
Tested in Brave browser's console REPL.
N/A

Check for node, tagName for va-loading-indicator

---

packages/core/package.json
packages/web-components/package.json
packages/web-components/src/components/va-notification/va-notification.tsx
packages/web-components/src/components/va-radio/va-radio.tsx

https://bug-make-header-tag-lowercase--60f9b557105290003b387cd5.chromatic.com
---
This PR updates functions for creating dynamic headers (passed on props set by user) for `va-radio` and `va-notification` components.
|--|--|
| <img width="584" alt="Screenshot 2023-08-03 at 2 51 25 PM" src="https://github.com/department-of-veterans-affairs/component-library/assets/8542413/4d17fe34-c39f-481d-a33b-645b71345ef7"> | <img width="583" …

(bug): make html header tag lowercase

---

packages/web-components/package.json
packages/web-components/src/components/va-additional-info/va-additional-info.css

https://fix-additional-info-margin-whitlock--60f9b557105290003b387cd5.chromatic.com
Adjusts the margin on the additional info component to only be present when the component is in it's 'open' state.
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1203
Visually tested in storybook. All tests pass for Additional Info component.
BEFORE
AFTER

fix: only add margin for when additional info is open

---

packages/web-components/package.json
packages/web-components/src/components/va-pagination/va-pagination.tsx

https://va-pagination-active-blur--60f9b557105290003b387cd5.chromatic.com
No ticket - This is from a support request in Slack: https://dsva.slack.com/archives/C01DBGX4P45/p1691419861861739
The issue reported was that when using a filtering mechanism with the va-pagination component, an error started to appear in the console:
From that Slack message:
> To reproduce nav to https://staging.va.gov/my-health/secure-messages/inbox/, enter `test` in filter box, click Filter button and then use pagination
> vets.gov.user+41@gmail.com
> 109SsNrLgPv5
I was not able to reproduce this locally but I think the problem might be that when we are removing the focus state with `.blur`, there could be scenarios where an `.activeElement` element does not exist yet. So this adds optional chaining to account …

va-pagination: Add optional chaining to activeElement blur

---

packages/web-components/package.json
packages/web-components/src/components/va-radio-option/test/va-radio-option.e2e.ts
packages/web-components/src/components/va-radio-option/va-radio-option.tsx

https://1961-multiple-tab-presses--60f9b557105290003b387cd5.chromatic.com
Closes [v3 va-radio button uses more than one tab to get to next focusable item #1961](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1961)
Tested locally in Storybook in Chrome, Firefox, Edge, Safari

va-radio-option: Set tab index to -1 for radio button input

---

packages/web-components/stencil.config.ts

https://copy-assets-to-dist--60f9b557105290003b387cd5.chromatic.com
This PR updates the Stencil config so that static assets get copied to the `dist` folder during build. This is necessary because when the `va-icon` component is used in `vets-website` a 404 was thrown when the browser tried to resolve the path on the icon.
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1977

update stencil config to copy static assets to dist folder during build

---

packages/core/package.json
packages/storybook/stories/va-number-input-uswds.stories.jsx
packages/storybook/stories/va-number-input.stories.jsx
packages/web-components/src/components.d.ts
packages/web-components/src/components/va-number-input/test/va-number-input.e2e.ts
packages/web-components/src/components/va-number-input/va-number-input.tsx

https://add-back-inputmode--60f9b557105290003b387cd5.chromatic.com
---
This PR adds back the `inputmode` prop which was erroneously removed in a [previous PR](https://github.com/department-of-veterans-affairs/component-library/pull/804). The `inputmode` prop is important because it governs which virtual keyboard is displayed on mobile devices, i.e. whether the "." is shown (when `inputmode` = decimal).
local testing in chrome, firefox, safari, edge, mobile simulators for ios
With `<va-number-input uswds inputmode="decimal" />` we get a "." in the iOS virtual keyboard:

add back inputmode prop to va-number-input and adjust tests and stories

---

packages/web-components/package.json
packages/web-components/src/components/va-accordion/va-accordion-item.scss

https://2000-accordion-line-height--60f9b557105290003b387cd5.chromatic.com
Change accordion item line-height from 1 to 1.15 per the USWDS design
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2000
Local testing in Chrome
before:
After:

va-accordion: change line-height to 1.15

---

packages/css-library/copy-uswds-color-tokens.js
packages/css-library/dist/tokens/css/variables.css
packages/css-library/dist/tokens/figma/colors/variables.json
packages/css-library/dist/tokens/json/variables.json
packages/css-library/dist/tokens/scss/variables.scss
packages/css-library/package.json
packages/css-library/tokens/color.json
packages/css-library/tokens/uswds.json

https://asteele-passthrough-tokens-1967--60f9b557105290003b387cd5.chromatic.com
---
Adds a script for copying over desired USWDS tokens into the CSS Library package. The list of desired tokens is taken from this [VA Design System Airtable](https://airtable.com/appF4FJKBeNVNGrlm/tblaTo3cDAURdk22q/viwkqvCZIOuv2RT6P?blocks=hide).
Closes #[1967](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1967)
Locally tested.
Example of changing `color-black` to look to the USWDS color:

Introducing a new script to copy USWDS tokens

---

packages/web-components/package.json
packages/web-components/src/components/va-accordion/va-accordion.scss

https://2033-accordion-font-family--60f9b557105290003b387cd5.chromatic.com
The expand/collapse all was not displaying the correct font family (Arial). This update allows the element to inherit the correct font-family (Source Sans Pro) 
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2033
Storybook
**Before**
**After**

va-accordion: Load correct font family for expand/collapse

---

packages/web-components/src/components/va-radio-option/test/va-radio-option.e2e.ts
packages/web-components/src/components/va-radio-option/va-radio-option.scss
packages/web-components/src/components/va-radio/test/va-radio.e2e.ts
packages/web-components/src/components/va-radio/va-radio.tsx

https://2041-radio-options-label-width--60f9b557105290003b387cd5.chromatic.com
---
This PR modifies the va-radio component to allow the legend to have more space. 
Note: this is one response to the the ticket below. Another possibility is to increase the size of the radio-option labels to 480px as well as the legend.
Closes [2041](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2041)
local testing in chrome, firefox, safari, edge

va-radio: increase legend width to 480px

---

packages/web-components/src/components/va-checkbox/va-checkbox.tsx
packages/web-components/src/components/va-number-input/va-number-input.tsx
packages/web-components/src/components/va-text-input/va-text-input.tsx
packages/web-components/src/components/va-textarea/va-textarea.tsx

https://61817-message-pii--60f9b557105290003b387cd5.chromatic.com
We're using Datadog RUM session replays which records Veteran's interacting with the page. But when a `message-aria-describedby` is set and contains PII/PHI, it gets displayed in the recording. So we need to add a [`dd-privacy-hidden`](https://docs.datadoghq.com/real_user_monitoring/session_replay/privacy_options/#override-an-html-element) class to this screen reader only content to ensure it isn't visible.
Closes #64871 
No changes
N/A

Add Datadog privacy class to hide screen reader text

---

packages/storybook/stories/va-accordion-uswds.stories.jsx
packages/storybook/stories/va-accordion.stories.jsx
packages/web-components/package.json
packages/web-components/src/components.d.ts
packages/web-components/src/components/va-accordion/va-accordion.tsx

https://2060-accordion-scrolling--60f9b557105290003b387cd5.chromatic.com
The page was scrolling because calling `button.click()` scrolls to the clicked element if it is not in view. This change simplifies the logic for expanding/collapsing accordionItems and makes it so that `setAttribute` is used on the USWDS version. The scrolling can only be seen when the number of accordions is greater than height of the viewport, I have added a story with more accordion items to verify.
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2060
Local testing in Chrome, Firefox, Safari, and Edge

va-accordion: use setAttribute instead of calling click on accordion buttons

---

packages/web-components/src/components/va-memorable-date/va-memorable-date.scss
packages/web-components/src/components/va-memorable-date/va-memorable-date.tsx

https://61627-mem-date-selective-errors--60f9b557105290003b387cd5.chromatic.com
---
Making mem date only show error borders on certain fields, dependent on the error message.
- Fixing CSS to only show error border for V1 components
- Fixing component to only show error border for V3 components
Closes #[61627](https://github.com/department-of-veterans-affairs/va.gov-team/issues/61627)
Tested locally using Storybook

61627 mem date selective errors

---

packages/storybook/stories/va-checkbox-group-uswds.stories.jsx
packages/storybook/stories/va-checkbox-group.stories.jsx
packages/web-components/src/components.d.ts
packages/web-components/src/components/va-checkbox-group/test/va-checkbox-group.e2e.ts
packages/web-components/src/components/va-checkbox-group/va-checkbox-group.scss
packages/web-components/src/components/va-checkbox-group/va-checkbox-group.tsx
packages/web-components/src/components/va-radio/va-radio.scss
packages/web-components/src/mixins/headers.css

https://2078-add-header-checkbox-group--60f9b557105290003b387cd5.chromatic.com
---
Part of [#2078](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2078)
Added tests for headers

Add label-header-level to checkbox group

---

packages/web-components/package.json
packages/web-components/src/components.d.ts
packages/web-components/src/components/va-telephone/test/va-telephone.e2e.ts
packages/web-components/src/components/va-telephone/va-telephone.tsx

https://va-telephone-ext-type--60f9b557105290003b387cd5.chromatic.com
When deprecating the React Telephone component for va-telephone, I was getting a failed test on vets-website because it was checking for an extension of `0000` but the web component was not displaying it.
The `extension` prop was being set correctly but the web component wasn't able to accept the value `0000`. In VS Code, a linting error was showing as:
> Octal literals are not allowed. Use the syntax '0o0'.ts(1121)
I was able to verify this issue in Storybook locally.
I tried using `Number` and `parseInt` to make sure it was getting passed as a number type but it still didn't work _specifically_ for the value `0000`. Other numbers and numeric strings worked fine.
What seems to fix this is changing the `extension` prop …

va-telephone: Change extension prop from number to string type

---

packages/core/package.json
packages/web-components/src/components/va-radio-option/test/va-radio-option.e2e.ts
packages/web-components/src/components/va-radio-option/va-radio-option.scss
packages/web-components/src/components/va-radio-option/va-radio-option.tsx
packages/web-components/src/components/va-radio/test/va-radio.e2e.ts
packages/web-components/src/components/va-radio/va-radio.tsx
packages/web-components/src/global/_formation_overrides.scss

https://2075-radio-group-accessibility--60f9b557105290003b387cd5.chromatic.com
- Remove tabIndex from radio options. They were causing options to be read as a "group"
- Update input Ids so they don't conflict with the web-component element id. This was causing the screen reader to not read the option label
- Change va-radio-option from `shadow: true` to `shadow: false`. This was causing the screen reader to not announce the total number of options and dictate that each option was its own radio group
- Remove label `id` attribute as this is not used and was causing AXE checks to complain about duplicate ids
- Update CSS to work with not having a host/shadow root
- Update tests for changes to HTML and functionality being tied to the input and not the web-component
Closes …

va-radio, va-radio-option: Screen reader and keyboard navigation updates

---

packages/core/package.json
packages/web-components/package.json
packages/web-components/src/components/va-number-input/va-number-input.tsx

https://mc-number-input-fix--60f9b557105290003b387cd5.chromatic.com
---
Re-adds a space to the va-number-input whose removal has introduced a regression into vets-website.

add space back to number input

---

packages/web-components/package.json
packages/web-components/src/components/va-pagination/test/va-pagination.e2e.ts
packages/web-components/src/components/va-pagination/va-pagination.tsx

https://2114-label-pagination--60f9b557105290003b387cd5.chromatic.com
---
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2114
Tested locally using Brave and VoiceOver on Safari.
N/A

Adding aria-label to V3 pagination

---

.github/workflows/disallow-zenhub-link.yml

https://github-workflow-zh-link--60f9b557105290003b387cd5.chromatic.com
This workflow uses the [github-pr-contains-action](https://github.com/dataloudercom/github-pr-contains-action). It checks for the presence of a word in the body or diff in a PR.
In this case, we are checking for the value `zenhub.c0m` (using a zero in the string here so the workflow doesn't fail) because we want to be linking to Github issues; not zenhub links of Github issues.
The reason we only want to use Github links is because it provides us with **very low effort documentation** by auto-generating cross-references between issues. This cross-referencing is very important for understanding context of changes and makes reviewing PRs easier.
There can also be access issues with Zenhub where other teams are unable to …

Github action to disallow zenhub links in PR descriptions

---

packages/storybook/stories/va-modal-uswds.stories.jsx
packages/web-components/package.json
packages/web-components/src/components/va-modal/va-modal.scss

https://2116-modal-storybook--60f9b557105290003b387cd5.chromatic.com
- Update to make the buttons be full width in mobile
- Make the storybook copy/content match sketch
- Update title font to be bitter
- Fix bug that was making the margins of the modal wider than they should be
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2116
Local testing in Chrome, Safari, Edge, and Firefox
Before:
After:

va-modal: button widths, margin bug fix, storybook copy, title font family

---

packages/web-components/package.json
packages/web-components/src/components/va-modal/va-modal.tsx

https://2087-modal-undefined-label--60f9b557105290003b387cd5.chromatic.com
- Don't set aria-label if title is undefined
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2087
- Local testing through storybook
- E2E tests are passing
- No visual changes

va-modal: Fix logic for aria-label, don't set aria-label if title is not provided

---

packages/web-components/package.json
packages/web-components/src/components/va-process-list/va-process-list-item.scss
packages/web-components/src/components/va-process-list/va-process-list.scss

https://2023-process-list-uswds-font--60f9b557105290003b387cd5.chromatic.com
This update will forward the USWDS font setting to the component so that it loads the font family stack for Source Sans Pro.
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2023
Storybook

va-progress-list: Forward the USWDS settings to load Source Sans Pro

---

packages/web-components/src/components/va-memorable-date/test/va-memorable-date.e2e.ts
packages/web-components/src/components/va-memorable-date/va-memorable-date.tsx

https://2077-mem-date-name--60f9b557105290003b387cd5.chromatic.com
The PR updates the way the `name` prop was being applied to the `name` attribute on the input fields. Previously, when the prop wasn't set, it would show up in the DOM as "undefined". This update adds a display condition to avoid that (v1 and v3):
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2077
Storybook
**`name` prop not set**
**`name` prop set**

va-memorable-date: Conditionally display name prop value

---

packages/web-components/package.json
packages/web-components/src/components/va-icon/va-icon.tsx

https://va-icons-sprite-path--60f9b557105290003b387cd5.chromatic.com
I was exploring the reason that we kept getting a new assets folder created locally when running the Stencil build command `yarn watch:stencil` like this:
When I remove the `va-icon` component's `assetsDirs` setting, this asset folder generation stops happening. Do we recall why we needed that to begin with? Looking at the [original discovery PR for creating a va-icon component](https://github.com/department-of-veterans-affairs/component-library/pull/540/files#diff-e080bd09d1ef6211d9591a52df12d9b3111d7547c089089f4095118102da4f9a), it looks like this setting was commented out (maybe because it's not needed?).
The sprite path still seems to be loading ok locally and with Chromatic using just the Stencil `getAssetPath` …

va-icon: Remove assetsDirs setting

---

packages/web-components/src/components/va-privacy-agreement/va-privacy-agreement.scss
packages/web-components/src/components/va-process-list/va-process-list.scss
packages/web-components/src/components/va-radio-option/va-radio-option.scss
packages/web-components/src/components/va-radio/va-radio.scss
packages/web-components/src/components/va-select/va-select.scss

https://2076-3-fix-non-v3-styles--60f9b557105290003b387cd5.chromatic.com
---
Relates to #[2076](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2076)
Converts styles for V1 and V3 to make use of more specific selectors. Previously, non-V3 styles were 'selected' in CSS by checking for the presence or absence of the `uswds` attribute, looking like:
```
:host(:not([uswds]))
```
However, this was not specific enough, because if the `uswds` attribute was present but set to `false`, the CSS engine would still ignore the V1 style. This PR replaces the above with this:
```
:host(:not([uswds='true'], [uswds='']))
```
This will check for both the presence of the attribute (`=''`) and/or if it is present and true (`='true'`). In other places, where we *want* …

2076 Fix V3 and non-V3 CSS Selectors (Part 3)

---

packages/web-components/src/components/va-text-input/va-text-input.scss
packages/web-components/src/components/va-textarea/va-textarea.scss
packages/web-components/src/mixins/focusable.css
packages/web-components/src/mixins/form-field-error.css
packages/web-components/src/mixins/uswds-error-border.scss
packages/web-components/src/mixins/uswds-input-width.scss

https://2076-4-fix-non-v3-styles--60f9b557105290003b387cd5.chromatic.com
---
Relates to #[2076](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2076)
Converts styles for V1 and V3 to make use of more specific selectors. Previously, non-V3 styles were 'selected' in CSS by checking for the presence or absence of the `uswds` attribute, looking like:
```
:host(:not([uswds]))
```
However, this was not specific enough, because if the `uswds` attribute was present but set to `false`, the CSS engine would still ignore the V1 style. This PR replaces the above with this:
```
:host(:not([uswds='true'], [uswds='']))
```
This will check for both the presence of the attribute (`=''`) and/or if it is present and true (`='true'`). In other places, where we *want* …

2076 Fix V3 and non-V3 CSS Selectors (Part 4)

---

packages/core/package.json
packages/react-components/package.json
packages/react-components/src/components/Telephone/contacts.js

https://revert-contacts-react--60f9b557105290003b387cd5.chromatic.com
This PR will revert the removal of the `contacts.js` file from the React package: https://github.com/department-of-veterans-affairs/component-library/pull/873
We discovered that vets-website uses the following import path which broke after this file was removed from the React package:
```
import {
CONTACTS,
} from '@department-of-veterans-affairs/component-library/contacts';
```
Follow-up ticket for fixing this issue: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2194
locally with Storybook. I tested that it worked with the [`va-telephone` Storybook file.](https://github.com/department-of-veterans-affairs/component-library/blob/main/packages/storybook/stories/va-telephone.stori …

Add back the contacts file to the React components package

---

packages/core/package.json
packages/design-system-dashboard-cli/coverage/lcov-report/write-react-owners-to-csv.js.html
packages/design-system-dashboard-cli/src/write-react-owners-to-csv.js
packages/react-components/index.js
packages/react-components/package.json
packages/react-components/src/components/AlertBox/AlertBox.jsx
packages/react-components/src/components/AlertBox/AlertBox.mdx
packages/react-components/src/components/AlertBox/AlertBox.unit.spec.jsx
packages/react-components/src/components/Checkbox/Checkbox.jsx
packages/react-components/src/components/Checkbox/Checkbox.mdx
packages/react-components/src/components/Checkbox/Checkbox.unit.spec.jsx
packages/react-components/src/components/LoadingIndicator/LoadingIndicator.jsx
packages/react-components/src/components/LoadingIndicator/LoadingIndicator.mdx
packages/react-components/src/components/LoadingIndicator/LoadingIndicator.unit.spec.jsx
packages/react-components/src/components/MaintenanceBanner/MaintenanceBanner.jsx
packages/react-components/src/components/MaintenanceBanner/MaintenanceBanner.mdx
packages/react-components/src/components/MaintenanceBanner/MaintenanceBanner.unit.spec.jsx
packages/react-components/src/components/OMBInfo/OMBInfo.jsx
packages/react-components/src/components/OMBInfo/OMBInfo.mdx
packages/react-components/src/components/OMBInfo/OMBInfo.unit.spec.jsx
packages/react-components/src/index.js
packages/storybook/stories/additional-docs.js

https://revert-deprecated-react--60f9b557105290003b387cd5.chromatic.com
Reverting the following commits in an attempt to get our [vets-website release PR](https://github.com/department-of-veterans-affairs/vets-website/pull/26137) to pass:
- https://github.com/department-of-veterans-affairs/component-library/pull/879
- https://github.com/department-of-veterans-affairs/component-library/pull/854
- https://github.com/department-of-veterans-affairs/component-library/pull/882
- https://github.com/department-of-veterans-affairs/component-library/pull/902
Locally with Storybook
N/A

Revert deprecated React components from previous release

---

packages/design-system-dashboard-cli/README.md
packages/design-system-dashboard-cli/src/find-ds-components.js
packages/design-system-dashboard-cli/src/search-files.js

https://mc-2517-uswds-components--60f9b557105290003b387cd5.chromatic.com
---
This pull request adds support to the design system dashboard cli to search for all components using the `uswds` prop. 
Running `yarn search uswds` will use a regex that matches any web component or web component react binding where the `uswds` prop is being used. 
Related to https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2157
Locally tested the regex in both the cli tool and vets-website to ensure results matched up

update search script to support uswds query

---

packages/storybook/stories/va-process-list-uswds.stories.jsx
packages/web-components/package.json
packages/web-components/src/components/va-process-list/test/va-process-list-item.e2e.ts
packages/web-components/src/components/va-process-list/va-process-list-item.scss
packages/web-components/src/components/va-process-list/va-process-list-item.tsx
packages/web-components/src/components/va-process-list/va-process-list.scss

https://65235-process-list-accessibility--60f9b557105290003b387cd5.chromatic.com
- add sr-only text for statuses (pending, active, and complete)
- choose darker color for pending status that meets accessibility requirements
- add alt text to checkbox image in css
Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/65235
Local testing with Chrome and Mac VoiceOver
Only visual change is to the color on pending.
Before:
After:

va-process-list: accessibility updates (staging review)

---

packages/core/package.json
packages/storybook/stories/va-alert-uswds.stories.jsx
packages/web-components/package.json
packages/web-components/src/components.d.ts
packages/web-components/src/components/va-alert/test/va-alert.e2e.ts
packages/web-components/src/components/va-alert/va-alert.tsx
packages/web-components/src/components/va-banner/va-banner.tsx

https://61262-require-alert-icon--60f9b557105290003b387cd5.chromatic.com
Update to ensure that there is always an icon/status for the alert and prevent the alert from rendering as text on a grey background.
- Update Prop definition to list allowed statuses for alert
- Add code to default to 'info' for status if the value is null or not found in the list of supported statuses
- Add tests for this logic
- Add story for USWDS to show "backgroundOnly" version
Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/61262
- E2E tests
- Local testing with Chrome, Firefox, Edge, and Safari
Before:
After:

va-alert: force status to be defined

---

.gitignore
packages/web-components/src/components/va-minimal-header/test/va-minimal-header.spec.tsx
packages/web-components/src/components/va-minimal-header/va-minimal-header.tsx

https://minimal-header-role--60f9b557105290003b387cd5.chromatic.com
---
Matt let me know that the check-in team had an a11y consideration for their version of the minimal header, which was to identify this as a banner landmark. I agree, so I added that to our component.
- Used VoiceOver landmarks menu to ensure it shows up there.
**Before:**
**After:**

Add banner role to minimal header

---

packages/web-components/src/components/va-radio-option/test/va-radio-option.e2e.ts
packages/web-components/src/components/va-radio-option/va-radio-option.tsx

https://62612-dd-radio--60f9b557105290003b387cd5.chromatic.com
Added `data-datadog-action-name` to `va-radio-option` description because clicking on the description would reveal the content in Datadog's event pane.
See [#62612](https://github.com/department-of-veterans-affairs/va.gov-team/issues/62612)
Added `data-datadog-action-name` attribute check
Description showing (mock) PII
Datadog event showing click on description

Add datadog action name to radio description

---

packages/web-components/src/components/va-minimal-header/test/va-minimal-header.spec.tsx
packages/web-components/src/components/va-minimal-header/va-minimal-header.tsx

https://add-alt-minimal-header--60f9b557105290003b387cd5.chromatic.com
---
This PR adds an "alt" attr to the img for a11y reasons.
local testing in chrome, firefox, safari, edge

VaMinimalHeader: add alt attribute to img

---

packages/storybook/stories/va-notification.stories.jsx
packages/web-components/package.json
packages/web-components/src/components/va-notification/va-notification.tsx

https://2248-deprecate-notification-component--60f9b557105290003b387cd5.chromatic.com
---
Closes [#2248](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2248)
Tested locally using Storybook and Brave

2248 - Deprecating va-notification in storybook

---

packages/web-components/src/components/va-modal/va-modal.scss

https://2219-modal-font-icon-fix--60f9b557105290003b387cd5.chromatic.com
---
This PR fixes responsiveness, icon padding, and title font for large modal.
Closes [2219](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2219)
Storybook in Chrome/Safari/Firefox
**Large Modal title font:**
**Large Modal icon spacing:**
**Large Modal width on mobile view:
Firefox:**
**Chrome:**
**Safari:**

va-modal - 2219 font, icon, and responsiveness fix for v3

---

packages/core/package.json

https://bump-core-32.1.0--60f9b557105290003b387cd5.chromatic.com
---
This PR bumps core to 32.1.0 for release

Bump core to 32.1.0

---

packages/storybook/stories/va-statement-of-truth-uswds.stories.jsx
packages/storybook/stories/va-statement-of-truth.stories.jsx

https://2201-statement-of-truth-storybook--60f9b557105290003b387cd5.chromatic.com
This adjusts the Storybook example so that it doesn't create a horizontal scroll on small screens.
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2201
Storybook

va-statement-of-truth: update storybook width display

---

packages/web-components/package.json
packages/web-components/src/components/va-on-this-page/va-on-this-page.css

https://2225-fix-VaOnThisPage-align--60f9b557105290003b387cd5.chromatic.com
---
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2225
Local testing in browser
Before:
After:

Fix issue with va-on-this-page left margin alignment

---

packages/web-components/package.json
packages/web-components/src/components/va-minimal-footer/va-minimal-footer.scss

https://2274-focus-minimal-footer-logo--60f9b557105290003b387cd5.chromatic.com
**Before**
**After**
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2274
Storybook

va-minimal-footer: add focus outline to logo

---

packages/storybook/stories/va-alert-uswds.stories.jsx

https://2246-remove-bkg-only-alerts--60f9b557105290003b387cd5.chromatic.com
---
Closes [#2246](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2246)
Tested locally in Storybook using Brave.
N/A

Removing background-only section from V3 Alerts

---

.github/CODEOWNERS

This reverts commit e10a72af5d5ee7f2d3db83faecf50bc9cffffa78.
https://va-mobile-setup-revert--60f9b557105290003b387cd5.chromatic.com
Matt mentioned last week that the VA Mobile team would be using their own repo so this PR will revert the additions that were previously made:
- https://github.com/department-of-veterans-affairs/component-library/pull/754
The Github workflows were already removed here:
- https://github.com/department-of-veterans-affairs/component-library/pull/852

Remove VA Mobile directories

---

packages/web-components/package.json
packages/web-components/src/components.d.ts
packages/web-components/src/components/va-segmented-progress-bar/test/va-segmented-progress-bar.e2e.ts
packages/web-components/src/components/va-segmented-progress-bar/va-segmented-progress-bar.tsx

https://2209-hide-steppers-aria--60f9b557105290003b387cd5.chromatic.com
---
Closes [#2209](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2209)
Tested locally using storybook, brave, and VoiceOver. Did not have JAWS to test with.
N/A

va-segmented-progress-bar: Hiding steps from JAWS

---

packages/web-components/package.json
packages/web-components/src/components/va-checkbox-group/va-checkbox-group.scss

https://2251-font-fix--60f9b557105290003b387cd5.chromatic.com
---
This PR sets the font of the legend in `va-checkbox-group` to be the same as `va-checkbox`: Source Pro Sans Web
Closes [2251](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2251)
local testing in Chrome, Edge, Safari, Firefox
**Before**: 
**After**

va-checkbox-group: make legend font match design spec

---

packages/storybook/.storybook/preview.js
packages/web-components/package.json
packages/web-components/src/components/va-official-gov-banner/va-official-gov-banner.tsx

https://2255-modal-screen-reading--60f9b557105290003b387cd5.chromatic.com
---
Closes [#2255](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2255)
Introduces a MutationObserver that is scoped to only the `#docs-root` element of storybook and is needed because the `hideOthers` function that we call as part of `setupModal` was hiding the docs-root from screen readers, which effectively meant that inside of storybook modals became 'invisible' to screen readers.
Tested locally using storybook and Brave
N/A

va-modal: fix for screen readers when using Storybook

---

packages/web-components/package.json
packages/web-components/src/components/va-official-gov-banner/va-official-gov-banner.scss

https://2097-gov-banner-wrapping--60f9b557105290003b387cd5.chromatic.com
---
Closes [#2097](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2097)
Fixes overlapping CSS instructions that caused the Medium screen size to be janky.

va-official-gov-banner: Fix for medium screens wrapping wrongly

---

packages/web-components/src/components/va-checkbox/test/va-checkbox.e2e.ts
packages/web-components/src/components/va-checkbox/va-checkbox.tsx

https://2355-checkbox-error-style--60f9b557105290003b387cd5.chromatic.com
Added `usa-error-message` class to `va-checkbox` error message to match expected error message styling. Also added a test to check for the class name
- Closes [#2355](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2355)
- Related [#71502](https://github.com/department-of-veterans-affairs/va.gov-team/issues/71502)
|--------|------|
| <img width="503" alt="before: va checkbox error message with black, non-bold test" src="https://github.com/department-of-veterans-affairs/component-library/assets/136959/d1a38e02-1eb6-44e1-9f64-fd22be10690c"> | <img width="502" alt="after: va checkbox error message with bold, red text" …

va-checkbox: Add error message styling

---

packages/web-components/src/components/va-featured-content/test/va-featured-content.e2e.ts
packages/web-components/src/components/va-featured-content/va-featured-content.tsx

https://featured-content-region-label--60f9b557105290003b387cd5.chromatic.com
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2322
- This adds an `aria-label` for the `role="region"` attribute. This gives the landmark a name, which comes in use when there are multiple regions on one page.
- To test this, certain browser/screen reader combos have to be used per [W3C - See **User Agent and Assistive Technology Support Notes**](https://www.w3.org/WAI/GL/wiki/Using_the_region_role_to_identify_a_region_of_the_page). I did a before and after using Safari and VoiceOver (see screenshots).
**Before**
**After**
- No visual changes

Add ARIA label to featured content region

---

packages/css-library/package.json

https://narin-mobile-tokens--60f9b557105290003b387cd5.chromatic.com
---
The mobile design system team would like to be able to reference the design tokens that live in `css-library`. Our plan is to add `css-library` as a dependency to our component library and convert the `.json` outputted by `build:tokens` into TypeScript for our needs. 
However `css-library`'s `package.json` is currently configured to only expose `.scss` and `.css` files to NPM. I believe the change in this PR and an additional minor/patch release would be all that is needed for us to begin this process.

[Mobile Design System] Include .json in NPM dist

---

packages/core/package.json
packages/css-library/package.json
yarn.lock

Updates core to 34.1.0 and css library to 0.3.0

update core to 34.1.0 and css-library to 0.3.0

---

README.md

https://update-readme-testing--60f9b557105290003b387cd5.chromatic.com
This fixes some of the Stencil testing references so that it points to the correct file path. Also minor grammar updates to the section.

Update references for testing single components in readme

---

packages/web-components/package.json
packages/web-components/src/components/va-checkbox-group/test/va-checkbox-group.e2e.ts
packages/web-components/src/components/va-checkbox-group/va-checkbox-group.tsx
packages/web-components/src/components/va-radio/va-radio.tsx

https://2342-sr-hint-text--60f9b557105290003b387cd5.chromatic.com
Move hint text to legend for va-checkbox-group and va-radio. This will ensure that screen readers read the text along with the label.
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2342
- [x ] Component maintains 1:1 parity with design mocks
- [x ] Text is consistent with what's been provided in the mocks
- [x ] Designer has signed off on changes (if applicable. If not applicable provide reason why) - No visual changes
- [x ] Tab order and focus state work as expected
- [x ] Changes have been tested against screen readers (if applicable. If not applicable provide reason why)
- [x ] New components are covered by e2e …

va-checkbox-group, va-radio - move hint to legend

---

packages/storybook/stories/va-card.stories.jsx
packages/web-components/package.json
packages/web-components/src/components.d.ts
packages/web-components/src/components/va-card/test/va-card.e2e.ts
packages/web-components/src/components/va-card/va-card.scss
packages/web-components/src/components/va-card/va-card.tsx
packages/web-components/src/components/va-notification/test/va-notification.e2e.ts

https://2403-va-card-gray-prop--60f9b557105290003b387cd5.chromatic.com/?path=/docs/components-va-card--default
This PR adds a `background` prop to va-card that applies a gray background. It also refactors some of the style and classes to simplify the component.
Figma: https://www.figma.com/file/afurtw4iqQe6y4gXfNfkkk/VADS-Component-Library?type=design&node-id=2795-113&mode=design&t=iGMBkLHNOAVT7XSa-0
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2403

va-card: add prop to display a gray background

---

packages/web-components/package.json
packages/web-components/src/components/va-alert/va-alert.scss

https://2354-va-alert--60f9b557105290003b387cd5.chromatic.com
---
This ticket addresses a bug in the v3 `va-alert` component. When the `full-width` and `closeable` attributes are set, the close button is rendered below the alert. This change preserves the button's `absolute` position when `full-width` is true, so that it is positioned correctly.
Closes [2354](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2354)
Before:
After:

va-alert: fix close button position on full-width

---

packages/web-components/src/components.d.ts

https://2393-header-minimal-clean-up--60f9b557105290003b387cd5.chromatic.com
---
This pull request includes updates to the `components.d.ts` file, which contains auto-generated typings for our Stencil components.
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2393
N/A

cleanup: auto generated component type changes

---

packages/web-components/src/components/va-checkbox-group/va-checkbox-group.tsx
packages/web-components/src/components/va-radio/va-radio.scss
packages/web-components/src/components/va-radio/va-radio.tsx

https://2269-radio-hint-text-fix--60f9b557105290003b387cd5.chromatic.com
---
This pull request updates the CSS for the `va-radio` v3 hint element. The change involves setting the display property to block.
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2269

va-radio: set display to block for .usa-hint class

---

packages/web-components/package.json
packages/web-components/src/components/va-file-input/va-file-input-upgrader.ts

https://2479-drag-drop-bug--60f9b557105290003b387cd5.chromatic.com
---
This PR fixes a bug that allowed a user to drag and drop multiple files onto the input after which the first file would be added and the others discarded. But the desired behavior is for all files to be rejected in this case, ie we don't support multiple files at this time.
Closes [2479](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2479)
Before:
https://github.com/department-of-veterans-affairs/component-library …

va-file-input: stop multiple file drag and drop

---

packages/web-components/package.json
packages/web-components/src/components/va-pagination/va-pagination.scss

https://2420-pagination-btn-active-color--60f9b557105290003b387cd5.chromatic.com
Update to sync style for va-pagination with USWDS
- Remove override that made the active page background color blue
- Override overflow opacity to match current USWDS style
USWDS Reference: https://designsystem.digital.gov/components/pagination/
Closes: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2420
- [ na - no accessibility changes] Accessibility expert has signed off on code changes (if applicable. If not applicable provide reason why)
- …

va-pagination: remove active button background color, override overflow opacity

---

packages/web-components/package.json
packages/web-components/src/components/va-file-input/va-file-input.scss
packages/web-components/src/global/_settings.scss

https://2441-file-input--60f9b557105290003b387cd5.chromatic.com
Figma: https://www.figma.com/file/afurtw4iqQe6y4gXfNfkkk/VADS-Component-Library?node-id=199%3A1212&mode=dev
USWDS Example: https://designsystem.digital.gov/components/file-input/
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2441
**Focus Before**
**Focus After**
**Error Before**
**Error After**

va-file-input: Add focus border, fix input alignment, and update error state

---

packages/web-components/src/components/va-maintenance-banner/test/va-maintenance-banner.e2e.ts
packages/web-components/src/components/va-maintenance-banner/va-maintenance-banner.tsx

https://2429-maint-banner-role--60f9b557105290003b387cd5.chromatic.com
---
Closes [#2429](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2429)
No design changes.

va-maintenance-banner: Removing maintenance banner's banner role

---

packages/web-components/src/components/va-file-input/va-file-input-upgrader.ts
packages/web-components/src/components/va-file-input/va-file-input.tsx

https://2442-file-input-a11y--60f9b557105290003b387cd5.chromatic.com
---
Closes [#2442](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2442)
Removes legacy code that was unnecessarily 'deleting' the file input's chosen file, thus preventing screen readers from reading out that a file was selected.
- No design changes
No design changes

va-file-input: Fix for screen readers not reading changed file name

---

.github/PULL_REQUEST_TEMPLATE.md

https://2481-update-chromatic--65a6e2ed2314f7b8f98609d8.chromatic.com
---
Closes [#2481](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2481)
This PR updates the pull request template to utilize the new Chromatic App ID.
N/A

Updating Chromatic Link in Pull Request Template

---

packages/web-components/package.json
packages/web-components/src/components/va-radio-option/va-radio-option.scss

https://2491-va-radio-input--65a6e2ed2314f7b8f98609d8.chromatic.com
This will resolve the issue of Formation input styles overriding the USWDS style for the va-radio-option `input` element. The previous solution that added a negative `z-index` caused issue with Cypress testing and it also doesn't follow the USWDS original styles.
USWDS reference: https://designsystem.digital.gov/components/radio-buttons/
related issue https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2491
related pr https://github.com/department-of-veterans-affairs/component-library/pull/1053
**before**
**after**

va-radio-option: revert z-index and add Formation style overrides for USWDS

---

packages/web-components/package.json
packages/web-components/src/components/va-accordion/va-accordion-item.scss

https://000-va-accordion-icon-hover--65a6e2ed2314f7b8f98609d8.chromatic.com
This PR will update the accordion open/close icons from Font Awesome to the USWDS icons.
reference: [Slack thread](https://dsva.slack.com/archives/C01DBGX4P45/p1710200196112369)
see: [USWDS Accordion Component](https://designsystem.digital.gov/components/accordion/)
closes: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2578
**before**
**after**

va-accordion: remove Font Awesome icon override

---

packages/core/package.json
packages/web-components/package.json
yarn.lock

https://bump-css-lib-in-web-components--65a6e2ed2314f7b8f98609d8.chromatic.com
---
This PR bumps the version of `css-library` used in `web-components` to the latest, `0.5.1`

update css-lib version in web-components

---

.github/release.yml

https://000-css-library-release-notes--65a6e2ed2314f7b8f98609d8.chromatic.com
This will update our release yml file so that any PRs that have the label `css-library` will be in its own section in the release notes. This is intended to be a bridge solution until we have more time to integrate a longer term release notes management approach.
The release notes should look something like this when CSS Library PRs are labeled with `css-library`:

Add css-library label to release notes

---

packages/design-system-dashboard-cli/src/create-spreadsheets.js

https://2564-comp-use-v3-default--65a6e2ed2314f7b8f98609d8.chromatic.com
---
Closes [#2564](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2564)
Updates the component-usage script to account for V3 as the new default 'mode' for components.

2564 - Updating comp-usage script to account for V3 as default

---

packages/web-components/package.json
packages/web-components/src/components/va-checkbox/va-checkbox.tsx

https://Add-label-prop-to-va-checkbox--65a6e2ed2314f7b8f98609d8.chromatic.com
---
closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2606
Added label prop to allow bold label for va-checkbox 
There is no UI change for this, a "label" prop was added to the component. We can then reference this prop in a CSS file to make a custom bold label.

va-checkbox: Add part attribute to label and description

---

packages/storybook/stories/va-accordion-uswds.stories.jsx
packages/web-components/src/components/va-accordion/va-accordion-item.e2e.ts
packages/web-components/src/components/va-accordion/va-accordion-item.tsx

https://77064-accordion-styling--65a6e2ed2314f7b8f98609d8.chromatic.com
---
Adds `part` to both the `va-accordion-item` header button and content to allow adding a background to the button and border to the content to alert Veterans that there is something that needs attention on the review & submit page (see screenshots) - I'm not sure why a horizontal scrollbar shows up in the screenshot, but I'll look into it.
Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/77064
|  | Desktop | Mobile |
|---|---|---|
|Before| <img width="623" alt="Screenshot 2024-03-28 at 11 23 28 AM" src="https://github.com/department-of-veterans-affairs/component-library/assets/136959/0958c29c-cb32-48d0-bd76-3460a532154a"> | <img width="301" alt="Screenshot 2024-03-28 at 11 30 12 AM" …

Update accordion styling

---

packages/storybook/stories/va-alert-expandable.stories.jsx
packages/storybook/stories/va-back-to-top.stories.jsx
packages/storybook/stories/va-banner.stories.jsx
packages/storybook/stories/va-card.stories.jsx
packages/storybook/stories/va-date.stories.jsx
packages/storybook/stories/va-header-minimal.stories.jsx
packages/storybook/stories/va-link.stories.jsx
packages/storybook/stories/va-loading-indicator.stories.jsx
packages/storybook/stories/va-maintenance-banner.stories.jsx
packages/storybook/stories/va-minimal-footer.stories.jsx
packages/storybook/stories/va-need-help.stories.jsx
packages/storybook/stories/va-official-gov-banner.stories.jsx
packages/storybook/stories/va-omb-info.stories.jsx
packages/storybook/stories/va-on-this-page.stories.jsx
packages/storybook/stories/va-progress-bar.stories.jsx
packages/storybook/stories/va-promo-banner.stories.jsx
packages/storybook/stories/va-telephone.stories.jsx

https://2589-storybook-sidebar--65a6e2ed2314f7b8f98609d8.chromatic.com
This will move components that are essentially VA specific that we want to continue offering as part of the design system up in the Storybook sidebar (alongside USWDS variations).
The result of this should be that any component under the `V1 Components` section are variations that **we will be removing** in the near future in favor of the USWDS variation:
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2589

Storybook: Move VA specific components in the sidebar

---

packages/storybook/.storybook/manager.js
packages/web-components/src/components/va-header-minimal/va-header-minimal.tsx
packages/web-components/src/components/va-maintenance-banner/va-maintenance-banner.tsx

https://2589-maturity-indicators--65a6e2ed2314f7b8f98609d8.chromatic.com
The maturity indicator dots were not showing for a number of components on Storybook. This PR fixes that.
| Components    | V1 Components |
| -------- | ------- |
| ![Screenshot 2024-03-29 at 10 38 33 AM](https://github.com/department-of-veterans-affairs/component-library/assets/872479/5e21a137-14f5-4adb-9809-438ac9e1da35)  | ![Screenshot 2024-03-29 at 10 38 38 AM](https://github.com/department-of-veterans-affairs/component-library/assets/872479/4aa3b336-da2a-4226-a6fe-3b4f20a82e2c)   |
| Components    | V1 Components |
| -------- | ------- |
| ![Screenshot 2024-03-29 at 10 40 12 AM](https://github.com/department-of-veterans-affairs/component-library/assets/872479/326677b0-36b9-48c4-b577-3f48aebfa210) | ![Screenshot …

Storybook: fix sidebar maturity indicators

---

.github/workflows/require-label.yml
packages/css-library/dist/tokens/css/variables.css
packages/css-library/dist/tokens/json/variables.json
packages/css-library/dist/tokens/scss/variables.scss
packages/css-library/tokens/breakpoints.json

https://2533-add-768-breakpoint--65a6e2ed2314f7b8f98609d8.chromatic.com
---
Closes [#2533](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2533)
Replaces the "medium-screen" breakpoint with 768px in order to keep in line with how Formation currently acts. Adding "medium-mobile" breakpoint for early adopters of the 640px breakpoint style.
N/A

CSS-Library: Adding mobile-medium breakpoint and replacing medium-screen with 768px

---

packages/storybook/stories/va-select-uswds.stories.jsx
packages/storybook/stories/va-select.stories.jsx
packages/web-components/package.json
packages/web-components/src/components.d.ts
packages/web-components/src/components/va-select/test/va-select.e2e.ts
packages/web-components/src/components/va-select/va-select.tsx

https://dst25-87-va-select-add-aria-describedby--65a6e2ed2314f7b8f98609d8.chromatic.com
Adds `aria-describedby` to `va-select` for screen readers.
Closes [va-select needs describedby property #2587](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2587)
Screen reader text:

va-select: Add aria-describedby-message for screen readers

---

.husky/pre-commit
package.json
yarn.lock

https://pre-commit-branch-name--65a6e2ed2314f7b8f98609d8.chromatic.com
In order to generate a Chromatic preview link on PRs, the branch name must follow these rules:
- must not exceed 37 characters
- must contain only lowercase letters, numbers, and dashes
See the repo [readme file](https://github.com/department-of-veterans-affairs/component-library?tab=readme-ov-file#contributing).
This PR will add husky so that we can do pre-commit checks and a primitive bash script. But this might also be useful for things in the future as other teams start contributing more to the component library.
1. Switch to this PRs branch `pre-commit-branch-name`
2. Create a new branch from there that's > 37 chars`pre-commit-branch-name-a-really-long-branch-name-for-testing`
3. Make a change to a file and try to …

Add pre-commit script for checking branch name

---

packages/core/package.json
packages/web-components/package.json

https://9999-icon-release-version-bump--65a6e2ed2314f7b8f98609d8.chromatic.com
---
Fix to release version.

Bumping versions to reflect latest release

---

packages/css-library/dist/tokens/css/variables.css
packages/css-library/dist/tokens/json/variables.json
packages/css-library/dist/tokens/scss/variables.scss
packages/css-library/tokens/breakpoints.json

https://2679-rename-scss-breakpoint--65a6e2ed2314f7b8f98609d8.chromatic.com
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2679
N/A

Rename medium-mobile breakpoint to tablet

---

.husky/pre-commit

https://000-pre-commit-branch-regex--65a6e2ed2314f7b8f98609d8.chromatic.com
We discovered that bash does not support `\d` so valid a branch name with numbers like `000-example-branch` were not passing the pre-commit check.

Update branch name check regex

---

packages/storybook/stories/va-button-uswds.stories.jsx
packages/web-components/src/components.d.ts
packages/web-components/src/components/va-button/test/va-button.e2e.ts
packages/web-components/src/components/va-button/va-button.scss
packages/web-components/src/components/va-button/va-button.tsx

https://aria-describedby-button--65a6e2ed2314f7b8f98609d8.chromatic.com
---
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2739
Adds in optional screen reader text for buttons. To test:
- Open Chromatic link > Button > open example in a new tab
- Open VoiceOver (Command + F5) > tab to button
- It should read out the button text and optional description
- **N/A** - no visual change.
No visual change.

Add message-aria-describedby to button

---

packages/storybook/stories/va-link.stories.jsx
packages/web-components/package.json
packages/web-components/src/components/va-link/test/va-link.e2e.ts
packages/web-components/src/components/va-link/va-link.tsx

https://2693-va-link-analytics--65a6e2ed2314f7b8f98609d8.chromatic.com
This PR will add the `href` prop value (destination) to the analytics details as well as the origin URL based on feedback from the related issue.
related https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2693
Analytics verified using Verdaccio in vets-website:

va-link: Add destination and origin to analytics details

---

packages/web-components/src/components/va-accordion/va-accordion-item.scss

https://2206-accordion-print2--65a6e2ed2314f7b8f98609d8.chromatic.com
Previous changes to add print media are overridden by original component definitions, so this PR adds a duplicate print media definition below the original component definition. Eventually all definitions below the original component definitions comment will be removed, including the duplicate print media definition.
see [#2206](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2206)

va-accordion: add duplicate print media to unhide print content

---

packages/web-components/package.json
packages/web-components/src/components/va-text-input/test/va-text-input.e2e.ts
packages/web-components/src/components/va-text-input/va-text-input.tsx

https://va-text-input-bug-fixes--65a6e2ed2314f7b8f98609d8.chromatic.com
---
This ticket addresses two bugs in `va-text-input`: 
* for the [Valid Range story](https://design.va.gov/storybook/?path=/docs/uswds-va-text-input--valid-range), there is no validation or enforcement of the range
* for the [Currency story](https://design.va.gov/storybook/?path=/docs/uswds-va-text-input--with-currency), there is no enforcement of the input (eg only an integer or a float with two decimal places.
Closes [2860](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2860)

va-text-input: address validation bug for currency / valid range

---

packages/web-components/src/components/va-file-input/va-file-input.tsx

https://rm-lineheight-hotfix--65a6e2ed2314f7b8f98609d8.chromatic.com
This is a quick fix,  adding vads-u-line-height--2 class to va-file-input to tighten the line-height  (so as to be in step with figma). It seems the was reverted  before merging, so I am adding it again.

Fixes line-height on va-file-input

---

packages/core/package.json

https://core-release-v42.1.1--65a6e2ed2314f7b8f98609d8.chromatic.com
---

update core version for release v42.1.1

---

.github/workflows/publish.yml

https://github-workflow-css-library--65a6e2ed2314f7b8f98609d8.chromatic.com
During the last component-library release, I got this error when it [tried to publish ](
https://github.com/department-of-veterans-affairs/component-library/actions/runs/9307901591/job/25620161408) the `css-library` package. 
I think that adding `yarn install` similar to how it's done for the `react-components` package will resolve this.

add yarn install to publish workflow for css-library

---

.github/workflows/publish-storybook.yml

https://set-storybook-build-output-dir--65a6e2ed2314f7b8f98609d8.chromatic.com
---
This PR is an attempt to deal with a [failure]() in the Build storybook and deploy action by explicitly setting the build's output dir.

specify storybook build output dir

---

packages/web-components/package.json
packages/web-components/src/components/va-breadcrumbs/va-breadcrumbs.scss

Fix to visually hidden breadcrumbs so that they are hidden from keyboard focus, too.
https://2837-visually-hidden-breadcrumbs--65a6e2ed2314f7b8f98609d8.chromatic.com
---
Closes [#2837](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2837)
N/A

va-breadcrumbs: Fix for focusability of 'hidden' breadcrumbs

---

.github/workflows/publish.yml

We switched to node 18.x in our [publishing workflow](https://github.com/department-of-veterans-affairs/component-library/blob/main/.github/workflows/publish.yml#L15) which broke our publishing command. This is because [yarn v4 requires](https://yarnpkg.com/advanced/changelog#major-changes) `yarn workspaces foreach` to include one of `--all`, `--recursive`, `--since`, or `--worktree`

update publish script

---

packages/web-components/package.json
packages/web-components/src/components/va-alert/va-alert-slot.css

https://va-alert-slot-style--65a6e2ed2314f7b8f98609d8.chromatic.com
We noticed that some slot styles for `va-alert` were applying to global paragraph styles so this update will make it specific to the component itself.

va-alert: add specificity to slot style

---

packages/core/package.json

https://core-release-v42.2.2--65a6e2ed2314f7b8f98609d8.chromatic.com
---

Update core version for release v42.2.2

---

packages/design-system-dashboard-cli/src/create-spreadsheets.js
packages/design-system-dashboard-cli/src/write-comp-usage-to-csv.js

https://9999-update-icon-usage-with-pages--65a6e2ed2314f7b8f98609d8.chromatic.com
---
Modifies how we tabulate icon data, now shows full page path instead of app path. (No ticket associated with this effort)

Dashboard-CLI: Modifying how we tabulate icons

---

packages/web-components/src/components.d.ts
packages/web-components/src/components/va-breadcrumbs/va-breadcrumbs.tsx

Fixes a build error where components.d.ts couldn't find the type with out the export:
```
[ ERROR ]  TypeScript: ./src/components.d.ts:167:28
Cannot find name 'Breadcrumb'.
L166:   */
L167:  "breadcrumbList"?: Breadcrumb[] | string;
L168:  /**
```

Add export to Breadcrumb type so components.d.ts can find it

---

packages/storybook/stories/va-file-input-multiple-uswds.stories.jsx
packages/storybook/stories/va-file-input-uswds.stories.jsx

https://rename-file-input-addt-component--65a6e2ed2314f7b8f98609d8.chromatic.com
Per [Matt's request](https://dsva.slack.com/archives/G01BJ3ESXL4/p1719329042817809?thread_ts=1719328004.131279&cid=G01BJ3ESXL4), rename the Additional Info story in file input storybook to Additional Form Inputs to be more accurate and to not be confused with Additional Info component

Rename Additional Info in file input to Additional Form Inputs

---

packages/css-library/package.json
packages/css-library/src/stylesheets/base/va.scss

https://mc-2981-add-anchor-tag-to-va-introtext--65a6e2ed2314f7b8f98609d8.chromatic.com
---
Original issue - https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2981
- Just keeping in sync with Formation for the time being

add anchor tag to va-textintro

---

packages/design-system-dashboard-cli/src/create-spreadsheets.js
packages/design-system-dashboard-cli/src/search-files.js
packages/design-system-dashboard-cli/src/write-comp-usage-to-csv.js

https://9999-add-css-to-icon-search--65a6e2ed2314f7b8f98609d8.chromatic.com
---
Adds looking at css/scss and unit/spec tests to Font Awesome icon searches

Add css and tests to FA icon search

---

packages/web-components/package.json
packages/web-components/src/mixins/headers.css

https://2629-hint-text-spacing--65a6e2ed2314f7b8f98609d8.chromatic.com
In form components that have headers instead of labels, legends, etc., a style was being applied that would add a margin to the first adjacent selector. This extra margin is not intended to be in the web components specifically so this PR will `unset` those styles.
It was introduced when we started using USWDS `usa-heading-styles` mixin via CSS Library:
https://github.com/department-of-veterans-affairs/component-library/blob/ff8d9cfaa01e5c01ed85dbb4e2d053830f4932e9/packages/css-library/src/stylesheets/base/headings.scss#L10
https://github.com/uswds/uswds/blob/369cf3fdf9abf721a357e864a0f6adbf667ba862/packages/uswds-core/src/styles/mixins/typography/typeset.scss#L43-L53
```sass
@mixin typeset-heading {
@include …
```

Add override to header margin on adjacent selector

---

packages/web-components/package.json
packages/web-components/src/components/va-search-input/va-search-input.tsx

https://2795-close-search-suggestions--65a6e2ed2314f7b8f98609d8.chromatic.com
---
- Fix the va-search-input component from having suggestions list stuck open
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2795
https://github.com/department-of-veterans-affairs/component-library/assets/15200011/827ab0b4-485f-45cc-afde-24d9b42cc5b2

va-search-input: fix suggestion box from always staying open

---

packages/web-components/package.json
packages/web-components/src/components/va-telephone/test/va-telephone.e2e.ts
packages/web-components/src/components/va-telephone/test/va-telephone.spec.tsx
packages/web-components/src/components/va-telephone/va-telephone.tsx

https://2884-va-telephone-aria-label--65a6e2ed2314f7b8f98609d8.chromatic.com
Based on a [discussion with the accessibility group at VA.gov](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2884), the `aria-label` should be removed from the telephone link.
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2884

va-telephone: remove number formatting from aria-label

---

packages/web-components/package.json
packages/web-components/src/components/va-link/va-link.css

https://va-link-inherit-style--65a6e2ed2314f7b8f98609d8.chromatic.com
When the `va-link` component is used with a header element, the anchor link inside of the component was not inheriting the header styles. 
[Slack convo](https://dsva.slack.com/archives/C01DBGX4P45/p1720728278101819) for reference
**before**
**after**

va-link: add style inheritance to anchor element

---

packages/storybook/stories/va-alert-uswds.stories.jsx
packages/web-components/src/components/va-alert/test/va-alert.e2e.ts
packages/web-components/src/components/va-alert/va-alert.tsx
packages/web-components/src/components/va-banner/test/va-banner.e2e.ts

https://alert-error-update--65a6e2ed2314f7b8f98609d8.chromatic.com
---
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2910
Removed the special conditions for the error status. Adding a `role="alert"` to the web component itself will turn this into an ARIA live region and announce the alert when it appears, so this code was not needed. This gives some flexibility and allows usage of other `role` (`role="status"`, etc.) attributes as well.
- N/A - no visual change.
No before screenshot: I was previously able to recreate it not doing that for error when it was brought up at DSC, but for some reason I couldn't get that to happen now. But I was able to confirm that with the changes made, it still works as expected. 
This shows how it functions …

Align error alert with other statuses

---

README.md

https://readme-version-guidance--65a6e2ed2314f7b8f98609d8.chromatic.com
This will add a few more examples to the [How to choose a version number](https://github.com/department-of-veterans-affairs/component-library?tab=readme-ov-file#how-to-choose-a-version-number) section of the readme for selecting a label for PRs (which will ultimately determine the `core` version when creating a release).
These examples should relate to the general [semver guidance on versioning](https://semver.org/#summary).

Update readme with more versioning examples 

---

packages/web-components/src/components/va-promo-banner/va-promo-banner.tsx

https://85927-rename-promo-key--65a6e2ed2314f7b8f98609d8.chromatic.com
---
Closes [#85927](https://github.com/department-of-veterans-affairs/va.gov-team/issues/85927)
Fixes a Snyk issue where the variable name had the word "key" in it and caused false positive security errors.
N/A

va-promo-banner: Renaming localstorage key var name

---

packages/web-components/src/components/va-file-input-multiple/va-file-input-multiple.scss
packages/web-components/src/components/va-file-input-multiple/va-file-input-multiple.tsx
packages/web-components/src/components/va-file-input/va-file-input.scss
packages/web-components/src/components/va-file-input/va-file-input.tsx

https://update-file-input-label--65a6e2ed2314f7b8f98609d8.chromatic.com
---
When using browser text resizing, labels are not resizing on the file input.
**Before/After** - Only with font size set to extra large in the browser.

Add class to file input labels to fix text resizing

---

packages/core/src/i18n/translations/en.js
packages/web-components/package.json

https://3046-mem-date-hint-text--65a6e2ed2314f7b8f98609d8.chromatic.com
[CAIA has advised](https://dsva.slack.com/archives/C01K37HRUAH/p1721313563386869) that they are updating their guidelines to remove "Please" from hint text and error messages. We will probably want to do a full review of components and guidelines to adjust for that but in the mean time, this PR will remove it from the hint text of va-memorable-date because a team is needing it now.
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3046
**before**
**after**
The [Spanish translation](https://github.com/department-of-veterans-affairs/component-library/blob/92aec15998a697ef9622278e0b033bb328ee890d/packages/core/src/i18n/translations/es.js#L31) already appear to be correct:

va-memorable-date: remove "Please" from hint text

---

packages/core/package.json

https://component-library-release-v43.01--65a6e2ed2314f7b8f98609d8.chromatic.com
---

Update core version for release - v43.01

---

packages/storybook/stories/va-back-to-top.stories.jsx
packages/storybook/stories/va-file-input-multiple-uswds.stories.jsx
packages/storybook/stories/va-file-input-uswds.stories.jsx
packages/storybook/stories/va-process-list-uswds.stories.jsx

https://storybook-example-improvements--65a6e2ed2314f7b8f98609d8.chromatic.com
While upgrading the `va-process-list` component to the USWDS version in vets-website, I noticed that the Storybook page was not displaying any of the child component properties. There were also a few other components missing some details that was making the technical docs seem incomplete.
I think there may have been a change with the way Storybook 6 displayed child component properties after we upgraded to Storybook 7. I'm manually adding them using the [argTypes setting](https://storybook.js.org/docs/7/api/arg-types) here but I think when we update to Storybook 8, we should instead use the [subcomponent setting](https://storybook.js.org/docs/writing-stories/stories-for-multiple-components#subcomponents) for …

Storybook example improvements

---

packages/web-components/package.json
packages/web-components/src/components/va-file-input-multiple/va-file-input-multiple.tsx
packages/web-components/src/components/va-file-input/va-file-input.tsx

https://file-input-sr-alerts--65a6e2ed2314f7b8f98609d8.chromatic.com
Closes [v3 File Input should have a success alert #2947](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2947)

va-file-input: update screen reader message when file is uploaded or removed

---

.github/workflows/chromatic.yml
packages/web-components/src/components/va-back-to-top/va-back-to-top.tsx

https://3005-chromatic-turbosnap--65a6e2ed2314f7b8f98609d8.chromatic.com
I noticed that the `onlyChanged` flag was commented out in the Chromatic workflow but the [Turbosnap docs](https://www.chromatic.com/docs/turbosnap/setup/#configure) say that this should be on.
In a test run, I can see now that there's a Turbosnap icon showing up so maybe this is a quick fix for other PRs? 🤞 
related https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3005

Chromatic Turbosnap: turn back on the onlyChanged flag

---

packages/web-components/src/components/va-breadcrumbs/test/va-breadcrumbs.e2e.ts
packages/web-components/src/components/va-breadcrumbs/va-breadcrumbs.tsx

https://2869-breadcrumb-lang-update--65a6e2ed2314f7b8f98609d8.chromatic.com
---
Relates to DST [2869](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2869)
N/A

va-breadcrumbs: Updating language support for breadcrumbs

---

packages/storybook/stories/va-text-input-uswds.stories.jsx

https://add-icon-and-suffix-story--65a6e2ed2314f7b8f98609d8.chromatic.com
---
Adding example that has both prefix icon and suffix text to show as an example on doc site.

va-text-input: add icon and suffix story

---

packages/css-library/package.json
packages/css-library/yarn.lock
packages/web-components/package.json
packages/web-components/src/components/va-button-icon/va-button-icon.scss
packages/web-components/src/components/va-button/test/va-button.e2e.ts
packages/web-components/src/components/va-button/va-button.scss
packages/web-components/src/components/va-button/va-button.tsx
yarn.lock

https://2612-uswds-upgrade--65a6e2ed2314f7b8f98609d8.chromatic.com
**USWDS v3.8.0 [release notes](https://github.com/uswds/uswds/releases/tag/v3.8.0)**
- Basic style support was added for [usa-icons in buttons](https://github.com/uswds/uswds/pull/5398/files). Before this was added, we were needing to add our own style to accommodate the positioning of icons in `va-button` which we can now remove. There is just a very slight adjustment to the button text which I think actually makes it better aligned.
- The [Chromatic diff](https://www.chromatic.com/build?appId=65a6e2ed2314f7b8f98609d8&number=1017) can be reviewed again if necessary.
- Follow-up ticket for adding indeterminate state to `va-checkbox` is here: 
- https://github.com/department-of-veterans-affairs/vets-design-system-documentati …

Update USWDS package to v3.8.1

---

packages/storybook/stories/styles/va-icon.scss
packages/web-components/src/components/va-button/va-button.scss

https://2628-secondary-hover--65a6e2ed2314f7b8f98609d8.chromatic.com
---
Closes [#2628](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2628)
|----|----|
| <img width="261" alt="secondary va-button hovered showing grey (transparent) background" src="https://github.com/user-attachments/assets/77829a68-b040-4d2f-aa1d-4b50316c93d4"> | <img width="312" alt="secondary va-button hovered showing white background" src="https://github.com/user-attachments/assets/678280ba-21d4-41cc-9db7-ef8e067ece17"> |

va-button | use white background on secondary hover

---

packages/web-components/src/components/va-breadcrumbs/va-breadcrumbs.scss

https://2970-breadcrumb-padding-fix--65a6e2ed2314f7b8f98609d8.chromatic.com
---
This PR fixes the breadcrumb padding on mobile view.
Closes 2970

va-breadcrumb: mobile view padding fix

---

packages/storybook/stories/va-file-input-uswds.stories.jsx

https://3080-file-input-title-case--65a6e2ed2314f7b8f98609d8.chromatic.com
Replace 'Label Header' story title with 'Header Label' to avoid using title case and to be consistent with the title in the storybook example.
Closes [3080](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3080)
- [ x] Changes have been tested …

va-file-input | story: replace 'Label Header' with 'Header label'

---

packages/core/package.json
packages/web-components/package.json

version bump for web-components and core for 8/8/24 release.
Bumped major on both due to v1 code removals.

version bump 8/5/24

---

codeowner-scan.sh

https://9999-codeowner-scanner-tool--65a6e2ed2314f7b8f98609d8.chromatic.com
---
Tool that takes a codeowner team name and spits out names of that team's members.

Tool for getting codeowner team member names

---

packages/storybook/stories/va-text-input-uswds.stories.jsx

https://va-text-input-safari-docs--65a6e2ed2314f7b8f98609d8.chromatic.com
---
This PR elaborates the storybook "autocomplete" option for `va-text-input` to explain to users the limitations with using this component with Safari autofill.
Closes [2688](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2668)

va-text-input: add autofill Safari documentation to storybook

---

packages/web-components/src/components/va-statement-of-truth/va-statement-of-truth.tsx
packages/web-components/src/components/va-text-input/va-text-input.tsx

https://3065-statement-of-truth--65a6e2ed2314f7b8f98609d8.chromatic.com
This update will make sure that the `error` prop is being reflected on to the `va-text-input` markup element in the DOM so that error styling will apply to it. It also cleans up the previous solution that is no longer necessary because of that update. 
This will fix error styling inconsistencies reported in the issue below.
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3065

va-statement-of-truth: reflect error prop in va-text-input for styling

---

packages/storybook/stories/va-back-to-top.stories.jsx
packages/web-components/src/components/va-back-to-top/va-back-to-top.css
packages/web-components/src/components/va-back-to-top/va-back-to-top.tsx

https://3162-back-to-top-sr-bug--65a6e2ed2314f7b8f98609d8.chromatic.com
Screen readers were still reading and focusing on the link even when it was hidden. This change to set the display to none when the link is not revealed fixes this issue.
Closes [3162](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3162)
- [x ] Component maintains 1:1 parity with design mocks
- [x ] Text is consistent with what's been provided in the mocks
- [x ] Component behaves as expected across breakpoints
- [x ] Designer has signed off on changes (if applicable. If not applicable provide reason why)
- [x ] Tab order and focus state work as expected
- [x ] Changes have been tested against screen readers (if applicable. If not applicable provide reason why)
- [x ] New …

va-back-to-top: set display none to link when it should not be visible

---

packages/storybook/stories/va-back-to-top.stories.jsx
packages/web-components/src/components.d.ts
packages/web-components/src/components/va-segmented-progress-bar/test/va-segmented-progress-bar.e2e.ts
packages/web-components/src/components/va-segmented-progress-bar/va-segmented-progress-bar.scss
packages/web-components/src/components/va-segmented-progress-bar/va-segmented-progress-bar.tsx

https://3024-seg-prog-bar-v1-removal--65a6e2ed2314f7b8f98609d8.chromatic.com
V1 code removal for va-segmented-progress-bar
Closes [3024](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3024)
- [x ] Component maintains 1:1 parity with design mocks
- [x ] Text is consistent with what's been provided in the mocks
- [x ] Component behaves as expected across breakpoints
- [x ] Accessibility expert has signed off on code changes (if applicable. If not applicable provide reason why)
- [x ] Designer has signed off on changes (if applicable. If not applicable provide reason why)
- [x ] Tab order and focus state work as expected
- [x ] Changes have been tested against screen readers (if applicable. If not applicable provide reason why)
- [x ] New components …

va-segmented-progress-bar: v1 variation code removal

---

packages/web-components/src/components.d.ts
packages/web-components/src/components/va-additional-info/test/va-additional-info.e2e.ts
packages/web-components/src/components/va-additional-info/va-additional-info.tsx

https://3011-additional-info-v1-removal--65a6e2ed2314f7b8f98609d8.chromatic.com
Removes v1 code for additional-info. There are no changes to the css file for this component as all classes still seem relevant to code for v3.
Closes [3011](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3011)
- [ x] Changes have been …

va-additional-info: v1 variation removal

---

packages/web-components/src/components.d.ts
packages/web-components/src/components/va-pagination/test/va-pagination.e2e.ts
packages/web-components/src/components/va-pagination/va-pagination.scss
packages/web-components/src/components/va-pagination/va-pagination.tsx

https://pagination-remove-v1--65a6e2ed2314f7b8f98609d8.chromatic.com
---
This PR removes v1 code from va-pagination.
Closes [3019](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3019)

va-pagination: remove v1 code

---

packages/web-components/src/components.d.ts
packages/web-components/src/components/va-summary-box/test/va-summary-box.e2e.ts
packages/web-components/src/components/va-summary-box/va-summary-box.scss
packages/web-components/src/components/va-summary-box/va-summary-box.tsx

https://3026-va-summary-box-v1-removal--65a6e2ed2314f7b8f98609d8.chromatic.com
va-summary-box v1 removal
Closes [3026](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3026)
- [ x] New components are covered by …

va-summary-box: v1 variation code removal

---

packages/web-components/src/components.d.ts
packages/web-components/src/components/va-process-list/test/va-process-list.e2e.ts
packages/web-components/src/components/va-process-list/va-process-list.scss
packages/web-components/src/components/va-process-list/va-process-list.tsx

https://3021-v1-process-list-removal--65a6e2ed2314f7b8f98609d8.chromatic.com
Process-list v1 code removal
Closes [3021](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3021)
- [ x] New components are covered by …

va-process-list: v1 variation removal

---

packages/web-components/src/components.d.ts
packages/web-components/src/components/va-file-input-multiple/test/va-file-input-multiple.e2e.ts
packages/web-components/src/components/va-file-input-multiple/va-file-input-multiple.tsx
packages/web-components/src/components/va-file-input/test/va-file-input.e2e.ts
packages/web-components/src/components/va-file-input/va-file-input.scss
packages/web-components/src/components/va-file-input/va-file-input.tsx

https://3017-file-input-v1-removal--65a6e2ed2314f7b8f98609d8.chromatic.com
- Remove v1 code from va-file-input
- Update va-file-input-multiple to remove uswds attributes
Closes [3017](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3017)
- [ x] Changes have been tested against screen readers (if applicable. If not …

va-file-input/va-file-input-multiple: v1 variation removal

---

packages/web-components/src/components.d.ts
packages/web-components/src/components/va-search-input/test/va-search-input.e2e.ts
packages/web-components/src/components/va-search-input/va-search-input.scss
packages/web-components/src/components/va-search-input/va-search-input.tsx

https://search-input-v1-removal--65a6e2ed2314f7b8f98609d8.chromatic.com
---
This PR removes v1 code from `va-search-input`
Closes [3023](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3023)

va-search-input: remove v1 code

---

packages/storybook/stories/va-text-input-uswds.stories.jsx
packages/web-components/src/components.d.ts
packages/web-components/src/components/va-text-input/test/va-text-input.e2e.ts
packages/web-components/src/components/va-text-input/va-text-input.tsx

https://suffix-icon-va-text-input--65a6e2ed2314f7b8f98609d8.chromatic.com
---
This PR adds support for an icon as a suffix for va-text-input.
Closes [3063](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3063)

va-text-input: add suffix icon support

---

packages/web-components/src/components/va-radio/va-radio.scss

https://mc-add-mixins-va-radio--65a6e2ed2314f7b8f98609d8.chromatic.com
This re-adds a couple of mixins to va-radio that caused a regression in production to to using the browser default stylesheet. 
[This slack thread](https://dsva.slack.com/archives/C01DBGX4P45/p1724445319663739) has more information and some screenshots on the regression

va-radio: re-add mixins

---

packages/storybook/stories/va-button-pair-uswds.stories.jsx
packages/web-components/src/components.d.ts
packages/web-components/src/components/va-button-pair/test/va-button-pair.e2e.ts
packages/web-components/src/components/va-button-pair/va-button-pair.tsx

https://va-button-pair-custom-text--65a6e2ed2314f7b8f98609d8.chromatic.com
---
This PR adds support for custom text for the buttons in va-button-pair.
Closes [3167](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3167)

va-button-pair: add support for custom button text

---

packages/web-components/src/components/va-accordion/va-accordion.tsx
packages/web-components/src/components/va-checkbox-group/va-checkbox-group.tsx
packages/web-components/src/components/va-checkbox/va-checkbox.tsx
packages/web-components/src/components/va-date/va-date.tsx
packages/web-components/src/components/va-file-input-multiple/va-file-input-multiple.tsx
packages/web-components/src/components/va-file-input/va-file-input.tsx
packages/web-components/src/components/va-memorable-date/va-memorable-date.tsx
packages/web-components/src/components/va-official-gov-banner/va-official-gov-banner.tsx
packages/web-components/src/components/va-on-this-page/va-on-this-page.tsx
packages/web-components/src/components/va-pagination/va-pagination.tsx
packages/web-components/src/components/va-radio/va-radio.tsx
packages/web-components/src/components/va-select/test/va-select.e2e.ts
packages/web-components/src/components/va-select/va-select.tsx
packages/web-components/src/components/va-text-input/va-text-input.tsx
packages/web-components/src/components/va-textarea/va-textarea.tsx
packages/web-components/src/index.ts
packages/web-components/tsconfig.bindings.json

https://i18n-web-comp--65a6e2ed2314f7b8f98609d8.chromatic.com
---
This PR updates /web-components so that the components always use a configured instance of i18n, even when web-components is installed in an application alone, outside of the rest of component-library (e.g. outside of core). For instance, now the dev server (yarn serve) includes translations. It also resolves an issue where some components that upon render invoke the configured instance of i18n would throw an error - e.g. va-official-gov-banner
**Note**: this PR changes the  `web-components` ts compiler by adding the "skipLibCheck" option
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/77587

web-components: adjust i18n config

---

packages/storybook/stories/va-radio-uswds.stories.jsx
packages/web-components/src/components.d.ts
packages/web-components/src/components/va-radio-option/va-radio-option.tsx
packages/web-components/src/components/va-radio/test/va-radio.e2e.ts
packages/web-components/src/components/va-radio/va-radio.tsx

https://radio-button-sr-description--65a6e2ed2314f7b8f98609d8.chromatic.com
Closes [va-radio description is not being read by screen reader #3059](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3059)
Adds `messageAriaDescribedby` to `va-radio` to be read by screen readers.

Add messageAriaDescribedby to va-radio

---

packages/core/package.json
packages/storybook/stories/va-link.stories.jsx
packages/web-components/package.json
packages/web-components/src/components/va-link/va-link.scss

https://mc-fix-header-styles--65a6e2ed2314f7b8f98609d8.chromatic.com
---
`font: inherit` needs to be re-added to va-link to ensure it inherits font-size when used inside a header. Removing this recently caused a regression on the homepage:
What it should be:
What it currently is:
[More context in this slack thread](https://dsva.slack.com/archives/C01DBGX4P45/p1724884067837049?thread_ts=1724445319.663739&cid=C01DBGX4P45)

va-link: re-add font inherit

---

packages/css-library/dist/stylesheets/modules/m-omb-info.css
packages/css-library/dist/stylesheets/modules/m-omb-info.css.map
packages/css-library/dist/stylesheets/shame.css
packages/css-library/dist/tokens/css/variables.css
packages/css-library/dist/tokens/scss/variables.scss
packages/css-library/src/stylesheets/modules/m-omb-info.scss
packages/css-library/src/stylesheets/shame.scss

https://1548-remove-padding--65a6e2ed2314f7b8f98609d8.chromatic.com
---
This PR removes any horizontal padding for `.progress-box` and `.omb-info--container` to better left-align content on the introduction page and within forms. For narrower (mobile) screens, this padding 
- https://github.com/department-of-veterans-affairs/VA.gov-team-forms/issues/1548 (ticket)
- https://github.com/department-of-veterans-affairs/vets-website/pull/31870 (vets-website)
- https://github.com/department-of-veterans-affairs/component-library/pull …

CSS Library: Remove progress-box padding

---

packages/storybook/stories/va-file-input-multiple-uswds.stories.jsx

https://file-input-multiple-text-update--65a6e2ed2314f7b8f98609d8.chromatic.com
Closes [Unable to use the slot in VAFileInputMultiple #3153](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3153)
Storybook text only update.
Was planning on a larger overhaul of this text, but the example provided worked for me in vets-website

Clean up text in va-file-input-multiple story

---

packages/storybook/stories/va-checkbox-group-uswds.stories.jsx
packages/web-components/src/components.d.ts
packages/web-components/src/components/va-checkbox-group/test/va-checkbox-group.e2e.ts
packages/web-components/src/components/va-checkbox-group/va-checkbox-group.tsx

https://2685-cbgroup-aria--65a6e2ed2314f7b8f98609d8.chromatic.com
Add a `message-aria-describedby` property to `va-checkbox-group`, test, and story
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2685
HTML showing rendered message-aria-describedby content
Tested with Voiceover

va-checkbox-group: add message-aria-describedby prop

---

packages/web-components/src/components/va-checkbox/va-checkbox.tsx
packages/web-components/src/components/va-radio-option/va-radio-option.tsx

https://3226-option-label--65a6e2ed2314f7b8f98609d8.chromatic.com
- `va-checkbox` label ID and `aria-describedby` are unnecessary (and redundant) because the checkbox description is nested in the label
- `va-radio-option` no longer has the label ID, so the `aria-describedby` isn't pointing to anything
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3225
va-radio before with `aria-describedby` on description
va-radio after with no `aria-describedby` on the description
va-checkbox after with no ID on the `label` or `aria-describedby` on the description

va-checkbox & va-radio-option: Remove option-label

---

packages/web-components/src/components/va-checkbox/test/va-checkbox.e2e.ts
packages/web-components/src/components/va-checkbox/va-checkbox.tsx

https://3226-cb-aria--65a6e2ed2314f7b8f98609d8.chromatic.com
When a description slot is added to the va-checkbox, a "description" ID is added to the input's aria-describedby, but there is no associated ID. I also noticed that the web component in vets-website _always_ renders a description slot, even if it ends up empty. To fix this, the selector for the description slot also checks if the slot is empty (`'[slot="description"]:not(:empty)'`); and check for multiple slots (since that's possible)
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3226
Before
Voice over before (missing description ID)
After: Voice over with div with description ID wrapping the slots

va-checkbox: Fix description slot

---

packages/web-components/src/components/va-accordion/va-accordion.e2e.ts
packages/web-components/src/components/va-accordion/va-accordion.tsx

https://2524-accordion-expand--65a6e2ed2314f7b8f98609d8.chromatic.com
---
This PR fixes a bug where if `va-accordion` has sections expanded on load (i.e. a `va-accordion-item` has `open="true"` attribute) then the button text in the upper right corner would say <code>Expand all +</code>, not `Collapse all -`.
Closes [2524](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2524)
Given this markup:
**Before**:
**After**:

va-accordion: check for open accordion items on load

---

packages/storybook/stories/va-select-uswds.stories.jsx
packages/web-components/src/components/va-select/test/va-select.e2e.ts
packages/web-components/src/components/va-select/va-select.scss
packages/web-components/src/components/va-select/va-select.tsx

https://issue-3286-va-select-optgroup--65a6e2ed2314f7b8f98609d8.chromatic.com
---
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3286

va-select: add support for optgroup markup 

---

packages/web-components/src/components/va-textarea/va-textarea.scss

https://2977-textarea-resizing-fix--65a6e2ed2314f7b8f98609d8.chromatic.com
---
Closes [#2977](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2977)
Before: 
After:

va-textarea: Fixing it so textarea components are resizable again

---

packages/css-library/dist/stylesheets/utilities.css
packages/css-library/dist/tokens/css/variables.css
packages/css-library/dist/tokens/scss/variables.scss
packages/css-library/package.json
packages/css-library/src/tokens/margin.scss

https://mc-margin-auto-fix--65a6e2ed2314f7b8f98609d8.chromatic.com
---
The 404 page on va.gov is mis-aligned, this is because margin-auto values in css-library were configured to use -1px instead of `auto`. This PR updates the map value for margin auto
<details><summary>Current settings in prod x--auto is set to -1px</summary>
</details>
<details><summary>With margins fixed in css-library</summary>
</details>

css-library: update margin auto value

---

packages/css-library/dist/stylesheets/utilities.css
packages/css-library/dist/tokens/css/variables.css
packages/css-library/dist/tokens/scss/variables.scss
packages/css-library/src/utilities/font.scss

https://font-family-utilities--65a6e2ed2314f7b8f98609d8.chromatic.com
It was reported that the `vads-u-font-family--sans` and `vads-u-font-family--serif` [font family utility](https://design.va.gov/foundation/utilities/font-family) classes weren't working. We discovered that the utility map for these classes had the incorrect base name. This PR will update that.
Issue discussed in this [Slack thread](https://dsva.slack.com/archives/C01DBGX4P45/p1728067148775889).

CSS Library: update font-family utility map base name

---

packages/core/package.json
packages/web-components/package.json
yarn.lock

https://mc-comp-lib-47.1.0--65a6e2ed2314f7b8f98609d8.chromatic.com
---
Updates version for core and web-components. css-library was updated on Friday [here](https://github.com/department-of-veterans-affairs/component-library/pull/1352/files#diff-1c40d3600debc345902064e33f34f49a99e1230a0a9ec56e6aa590bd93188d11)

update version for core and web-components

---

packages/web-components/src/components/va-modal/va-modal.scss

https://2492-modal-text-overflow--65a6e2ed2314f7b8f98609d8.chromatic.com
Text was overflowing the omb-info modal, after digging around it looks like the container of the modal (`:host .usa-modal__main`) was using padding without setting the box-sizing, which allowed for the content to flow off of the screen.
Closes [2492](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2492)
- [ x] Designer has signed off on changes (if applicable. If not applicable provide …

va-modal: set box-sizing to border-box to prevent text overflow

---

packages/storybook/stories/va-accordion-uswds.stories.jsx
packages/web-components/src/components/va-accordion/va-accordion-item.scss
packages/web-components/stencil.config.ts

https://dst3350-accordion-print--65a6e2ed2314f7b8f98609d8.chromatic.com
Closes [Bug: collapsed accordions is not printing out their content #3350](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3350)
Reorganizes CSS file so `print` rule isn't overwritten. Adds Print Accordion story to storybooks so we can automatically catch this issue if it happens again,

Open accordion when media is print

---

.github/workflows/chromatic.yml
README.md

https://chromatic-ui-diff--65a6e2ed2314f7b8f98609d8.chromatic.com
This PR toggled the `onlyChanged` setting in the [Chromatic workflow](https://github.com/department-of-veterans-affairs/component-library/blob/e84f6b581038fb0127514bead45185bbda82b6b1/.github/workflows/chromatic.yml#L35) so that it generated a new UI Test baseline. I'm hoping that this will resolve the issue where UI changes were not being flagged.
The full build run flagged a couple of changes that had not already been accepted yet here:  https://www.chromatic.com/build?appId=65a6e2ed2314f7b8f98609d8&number=1572

Toggle the onlyChanged Chromatic setting for a new UI baseline

---

packages/web-components/src/components/va-process-list/va-process-list-item.scss

https://1365-process-list-color-variable--65a6e2ed2314f7b8f98609d8.chromatic.com
Change `--uswds-system-color-gray-cool-70` color variable to `--vads-color-base-darker`
- [ x] New components are covered by e2e tests; updates to existing components are …

va-process-list: change color variable from usa to vads

---

packages/web-components/src/components/va-table/va-table-inner/va-table-inner.scss
packages/web-components/src/components/va-table/va-table-inner/va-table-inner.tsx

https://3327-va-table-screen-fix--65a6e2ed2314f7b8f98609d8.chromatic.com
---
This PR removes the css style which results in showing headers for non stacked tables for small screens.
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3327
Stacked table:

va-table: show table header for non-stacked & stacked small screen

---

packages/core/package.json
packages/css-library/package.json
packages/web-components/package.json
yarn.lock

https://release-2024-10-24--65a6e2ed2314f7b8f98609d8.chromatic.com
---

Bump version numbers for 47.2.0 release

---

packages/web-components/src/components/va-select/va-select.scss

https://3282-va-select-focus-styles--65a6e2ed2314f7b8f98609d8.chromatic.com
va-select currently has the default browser focus styles. This PR adds the focusable mixin so that the focus will be the va yellow focus style.
Closes [3282](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3282)
- [ x] New …

va-select: add import for focusable mixin

---

packages/web-components/src/components/va-modal/va-modal.scss

https://3355-modal-overflow-wrap--65a6e2ed2314f7b8f98609d8.chromatic.com
Modal content in the title and body were able to overflow the modal when there were no logical breaks, ie long words or urls. Setting `overflow-wrap:anywhere` will force wrapping in these situations.
As per the request in the ticket, this was not applied to the bottom buttons on the modal.
Closes [3355](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3355)
- [ x] Changes have been tested against screen readers (if applicable. If not applicable provide …

va-modal: set overflow-wrap:anywhere on modal content

---

packages/core/package.json
packages/css-library/package.json
packages/web-components/package.json
yarn.lock

https://mc-47.3.0--65a6e2ed2314f7b8f98609d8.chromatic.com
---

update package versions for release

---

packages/css-library/dist/tokens/css/variables.css
packages/css-library/dist/tokens/json/variables.json
packages/css-library/dist/tokens/scss/variables.scss
packages/css-library/tokens/line-lengths.json

https://3404-line-length-tokens--65a6e2ed2314f7b8f98609d8.chromatic.com
---
Closes [#3404](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3404)
CSS-Library only change.
N/A

css-library: Adding line-length tokens

---

packages/web-components/src/components/va-pagination/test/va-pagination.e2e.ts
packages/web-components/src/components/va-pagination/va-pagination.scss
packages/web-components/src/components/va-pagination/va-pagination.tsx

https://patch-tpierce-95248--65a6e2ed2314f7b8f98609d8.chromatic.com
---
This PR is a work in progress **WIP** so I can test with additional screen reader and browsers, and confirm the best way to test locally with vets-website codebase.
I discovered the `<va-pagination>` web component did not read out the ellipsis or the full Next | Previous link accessible labels in NVDA or VoiceOver while conducting an audit. I traced the root cause to `aria-label` not being supported on non-interactive elements like LI.
I propose moving …

Update `va-pagination` list item and next and previous links accessible labels for better screen reader consistency

---

packages/storybook/stories/va-telephone.stories.jsx
packages/web-components/src/components.d.ts
packages/web-components/src/components/va-telephone/test/va-telephone.e2e.ts
packages/web-components/src/components/va-telephone/test/va-telephone.spec.tsx
packages/web-components/src/components/va-telephone/va-telephone.tsx

https://3472-allow-non-us-numbers--65a6e2ed2314f7b8f98609d8.chromatic.com
---
Closes [#3472](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3472)

va-telephone: Allow non-US phone numbers

---

packages/core/package.json
packages/css-library/package.json
packages/web-components/package.json
yarn.lock

https://release-v48--65a6e2ed2314f7b8f98609d8.chromatic.com
---

Component library release v48.0.0

---

packages/core/package.json
packages/web-components/package.json

https://release-v4801--65a6e2ed2314f7b8f98609d8.chromatic.com
---

update core and web-component versions for release

---

packages/web-components/src/components/va-on-this-page/va-on-this-page.css

https://951-on-this-page-line-length--65a6e2ed2314f7b8f98609d8.chromatic.com
---
Closes [#951](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/951)
N/A

va-on-this-page: updating line-length for list items to use new token

---

README.md

https://patch-tpierce-docsVerdaccio--65a6e2ed2314f7b8f98609d8.chromatic.com
---
Adding a conversation about testing with Verdaccio into the README under `Contributing`. This stemmed from a Slack conversation with @jamigibbs earlier the week of November 4th. I included her instructions and a section on troubleshooting I encountered while testing a component fix.
---

DOCS: Update README `Contributing` entry with Verdaccio instructions

---

packages/storybook/.storybook/preview.js
packages/web-components/src/components/va-alert/test/va-alert.e2e.ts
packages/web-components/src/components/va-alert/va-alert.tsx

https://remove-alert-presentation-role--65a6e2ed2314f7b8f98609d8.chromatic.com
---
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3420
This was originally added in https://github.com/department-of-veterans-affairs/component-library/pull/280, but here I am reverting this change.
"Clickable" will be announced by NVDA if the element has a click handler or an ancestor element has a click handler. In the chain of parent elements and see if "click" is being handled by one of them, it will announce as clickable. 
While using presentation role is a workaround, it is common in JavaScript applications to have a click handler higher up the chain. Storybook needed `role="presentation"` added to its root element to get this fix to work in the past. …

Remove alert presentation role

---

packages/web-components/src/components/va-language-toggle/test/va-language-toggle.e2e.ts
packages/web-components/src/components/va-language-toggle/va-language-toggle.tsx

https://stencil-language-toggle-tests--65a6e2ed2314f7b8f98609d8.chromatic.com
This PR will resolve some Stencil test warnings for the va-language-toggle component.

va-language-toggle: resolve Stencil test warning and errors

---

packages/web-components/stencil.config.ts

https://stencil-lazy-load--65a6e2ed2314f7b8f98609d8.chromatic.com
---
Enable stencil flag to allow lazy loading in build chains such as vite.
See <https://stenciljs.com/docs/config-extras#enableimportinjection>
There's a nominal increase in bundle size for CJS and ESM targets, but IMO it's not significant enough to warrant concern.
<details>
<summary>Bundle size comparison</summary>
```
main
packages/web-components/dist $ du -sck *
124     assets
1088    cjs
3568    collection
1740    component-library
1332    components …
```

build: allow vite to lazy load stencil components

---

packages/core/package.json
packages/web-components/package.json
yarn.lock

https://mc-48.1.1--65a6e2ed2314f7b8f98609d8.chromatic.com
---
Updates versions of packages for release. 
CSS-Library wasn't updated because it was bumped in a prior pull request

48.1.1 update versions

---

packages/web-components/src/components/va-language-toggle/test/va-language-toggle.e2e.ts
packages/web-components/src/components/va-language-toggle/va-language-toggle.tsx

https://va-language-toggle-analytics-updates--65a6e2ed2314f7b8f98609d8.chromatic.com
Closes [Add va-language-toggle to ds-v3-playground for Analytics testing #3532](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3532)
Making updates based on [analytics team in slack](https://dsva.slack.com/archives/CKCRMLGAC/p1733945144549319?thread_ts=1731948507.349549&cid=CKCRMLGAC)
Added the link text to the event.
Disabled analytics on the `va-link` in `va-language-toggle` to prevent firing two events at once.

va-language-toggle: Add label text to event, remove va-link analytics

---

README.md

https://readme-contributions-storybook--65a6e2ed2314f7b8f98609d8.chromatic.com
While helping out a contributor from outside of DST, I noticed that there were a few things unclear and outdated in our Readme. Specifically around making contributions. Some things have changed too with creating a release so might as well tidy that up while I was there.

Update README with release changes and contribution clarifications

---

packages/web-components/src/components/va-alert-sign-in/va-alert-sign-in.scss

https://3611-sign-in-alert-a11y--65a6e2ed2314f7b8f98609d8.chromatic.com
---
Closes [#3611](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3611)
100% zoom:
130% zoom:

va-alert-sign-in: Modifying headline to use rems

---

packages/web-components/src/components/va-process-list/test/va-process-list-item.e2e.ts
packages/web-components/src/components/va-process-list/test/va-process-list.e2e.ts
packages/web-components/src/components/va-process-list/va-process-list-item.scss
packages/web-components/src/components/va-process-list/va-process-list-item.tsx

https://98739-proc-list-eyebrow-acc--65a6e2ed2314f7b8f98609d8.chromatic.com
This PR moves the status eyebrow text inside the header so that it doesn't get skipped by screen readers.
\* moving the eyebrow into the header caused the color of the eyebrow in the current step to be blue. I overrode this so that they are #3d4551
Closes [98739](https://github.com/department-of-veterans-affairs/va.gov-team/issues/98739)
- [ x] Changes have been tested against screen readers (if …

va-process-list-item: move status eyebrow into header so that it gets read by screen readers

---

packages/storybook/stories/va-table-uswds.stories.jsx
packages/web-components/src/components.d.ts
packages/web-components/src/components/va-table/test/va-table.e2e.ts
packages/web-components/src/components/va-table/va-table-inner/test/va-table-inner.e2e.ts
packages/web-components/src/components/va-table/va-table-inner/va-table-inner.tsx
packages/web-components/src/components/va-table/va-table.tsx

https://3448-va-table-striped--65a6e2ed2314f7b8f98609d8.chromatic.com
This adds the [USWDS striped](https://designsystem.digital.gov/components/table/#striped-table) variation to va-table.
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3448
**Basic bordered + striped table**
**Striped + Sorting + Border + Scrollable**

va-table: add striped variation

---

packages/web-components/src/components/va-file-input-multiple/test/va-file-input-multiple.e2e.ts
packages/web-components/src/components/va-file-input/va-file-input.tsx

https://file-input-mult-event-double-emit--65a6e2ed2314f7b8f98609d8.chromatic.com
Closes [va-file-input-multiple emits twice on file upload #3549](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3549)
A call of `handleFile` was added to the `render` function of `va-file-input` when read only was added. The `handleFile` emits `vaChange` which caused the second `vaMultipleChange` to fire in `va-file-input-multiple`. I added a parameter to conditionally emit change and set it to false for this call of `handleFile`.
Additionally this issue wasn't caught by tests because we only waited for the input change. Added `waitForChanges` to the page before checking how many times `vaMultipleChange` was emitted.

va-file-input-multiple: Fix multiple emits of vaMultipleChange

---

packages/css-library/dist/tokens/css/variables.css
packages/css-library/dist/tokens/scss/variables.scss
packages/css-library/package.json
yarn.lock

https://mc-img-rc-test--65a6e2ed2314f7b8f98609d8.chromatic.com
---
This PR adds the `img` directory to builds that get published to npm. A rc release was pushed to npm from this branch to address the needs of a lighthouse team in charge of maintaining developer.va.gov. [This thread](https://dsva.slack.com/archives/CBU0KDSB1/p1734483945839889) has more context. 
In general we should ship our own img directory to support teams that aren't strictly building products in vets-website or content-build.

CSS Library: add `img` folder to dist

---

packages/web-components/src/components.d.ts
packages/web-components/src/components/va-alert-expandable/va-alert-expandable.tsx
packages/web-components/src/components/va-alert-sign-in/va-alert-sign-in.tsx

https://va-alert-sign-in-storybook--65a6e2ed2314f7b8f98609d8.chromatic.com
This will fix the guidance links for va-alert-expandable and va-alert-sign-in. It will also display the maturity circle for va-alert-sign-in.
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3667

va-alert-expandable & va-alert-sign-in: fix Storybook link to guidance

---

packages/web-components/src/components/va-date/va-date.tsx

https://3569-va-date-aria-labels--65a6e2ed2314f7b8f98609d8.chromatic.com
The aria-labels for the month and day field in va-date were incorrect and more appropriate for input fields. In testing out updating the labels vs removing them it seems like these are unnecessary and may be adding confusion. This PR removes the aria-labels.
Closes [3569](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3569)
- [ x] Changes have been tested …

va-date: remove unnecessary aria labels for select

---

packages/web-components/src/components/va-alert-sign-in/va-alert-sign-in.tsx

https://va-alert-sign-in__no-unauth-form-start--65a6e2ed2314f7b8f98609d8.chromatic.com
---

va-alert-sign-in: Hides no-sign-in-link when not present

---

packages/storybook/stories/va-alert-sign-in.stories.jsx

https://db-add-mock-buttons-3673--65a6e2ed2314f7b8f98609d8.chromatic.com
---

Add mock buttons

---

packages/web-components/src/components/va-link/test/va-link.e2e.ts
packages/web-components/src/components/va-link/va-link.tsx

https://3606-va-link-aria-label--65a6e2ed2314f7b8f98609d8.chromatic.com
The `label` prop is used for the `aria-label` link attribute but not all va-link variations had the `aria-label` added to them as an option. This PR will make sure that all va-link variations are able to set it.
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3606
<details closed>
<summary>Link Variations - Voice Over Tests</summary>
</details>

va-link: add aria-label to all variations

---

packages/react-components/src/components/Telephone/contacts.js
packages/web-components/src/contacts.ts

https://adding-healthcare-telephone-number-constant--65a6e2ed2314f7b8f98609d8.chromatic.com
---
department-of-veterans-affairs/va.gov-team/issues/94773
Adding a phone number to the telephone component `contacts.js` and the telephone web component `contacts.ts` since we use it a lot so we can have consistent implementation. Did my best filling this out but let me know if I need to provide any additional information! 

va-telephone: add health resource center number to constants

---

packages/storybook/stories/va-file-input-multiple-uswds.stories.jsx
packages/web-components/src/components.d.ts
packages/web-components/src/components/va-file-input-multiple/test/va-file-input-multiple.e2e.ts
packages/web-components/src/components/va-file-input-multiple/va-file-input-multiple.tsx

https://3551-file-input-mult-cond-slot--65a6e2ed2314f7b8f98609d8.chromatic.com
Adds a property to allow for showing slot content only on specific file input fields.
Use case: An uploaded file requires a password to open the file. The UI should show an input field for that specific file to provide the password.
This solution adds a `slot-field-indexes` property that accepts a number array containing the indexes of the file input fields where slot content should be rendered.
Closes [3551](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3551)
- [ x] Accessibility expert has …

va-file-input-multiple: allow for slots to be conditionally rendered on file inputs

---

packages/storybook/stories/va-alert-sign-in.stories.jsx

https://alert-sign-in-story-time--65a6e2ed2314f7b8f98609d8.chromatic.com
The time-limit should be either 60 days or 1 year.
Slack convo: https://dsva.slack.com/archives/C07M02V2YBG/p1737753686183039

va-alert-sign-in: update story time-limit to 60 days

---

packages/web-components/src/components.d.ts
packages/web-components/src/components/va-select/test/va-select.e2e.ts
packages/web-components/src/components/va-select/va-select.tsx

https://98157-add-onblur-to-va-select--65a6e2ed2314f7b8f98609d8.chromatic.com
---
Closes [#98157](https://github.com/department-of-veterans-affairs/va.gov-team/issues/98157)
N/A - No visual changes

va-select: Adding 'vaSelectBlur' event

---

packages/web-components/src/components/va-alert/va-alert.scss

https://3704-fix-slim-alert-close-btn--65a6e2ed2314f7b8f98609d8.chromatic.com
---
Closes [#3704](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3704)
Slim alert on 1 line:
Slim alert on 2 lines:

va-alert: Fixing it so close button on slim alerts doesn't overflow

---

packages/web-components/src/components/va-telephone/test/va-telephone.e2e.ts
packages/web-components/src/components/va-telephone/va-telephone.tsx

https://3747-telephone-hidden--65a6e2ed2314f7b8f98609d8.chromatic.com
When `va-telephone` is set to `notClickable`, the span wrapping the phone number includes an `aria-hidden="true"` which makes screen readers ignore the phone number. 
See https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3747
N/A - video of problem in original ticket

va-telephone | Remove aria-hidden from notClickable phone

---

packages/web-components/src/components/va-process-list/va-process-list-item.scss
packages/web-components/src/components/va-radio-option/va-radio-option.scss

https://3773-fix-radio-style-bleed--65a6e2ed2314f7b8f98609d8.chromatic.com
---
Closes [#3773](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3773)

va-radio-option: Fixes to global style bleeds

---

packages/web-components/src/components/va-radio-option/va-radio-option.scss

https://9999-fix-radio-focus--65a6e2ed2314f7b8f98609d8.chromatic.com
---
Hotfix to restore focus styles to radio buttons.

va-radio-option: Hotfix to restore focus styles

---

README.md

I mis-matched the Verdaccio version numbers on first instructions, and it's been tripping me up every time I copy / paste during local testing.
https://docs-1copenut-update-verdaccio-instructions--65a6e2ed2314f7b8f98609d8.chromatic.com
---

Update README.md for `Verdaccio` testing instructions

---

packages/web-components/src/components/va-language-toggle/test/va-language-toggle.e2e.ts
packages/web-components/src/components/va-language-toggle/va-language-toggle.scss
packages/web-components/src/components/va-language-toggle/va-language-toggle.tsx

https://lang-toggle-accessibility--65a6e2ed2314f7b8f98609d8.chromatic.com
Closes [Language toggle accessibility updates #3564](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3564)

va-language-toggle: Address accessibility issues

---

packages/storybook/stories/va-button-pair-uswds.stories.jsx
packages/storybook/stories/va-button-uswds.stories.jsx
packages/web-components/src/components.d.ts
packages/web-components/src/components/va-button-pair/test/va-button-pair.e2e.ts
packages/web-components/src/components/va-button-pair/va-button-pair.tsx
packages/web-components/src/components/va-button/test/va-button.e2e.ts
packages/web-components/src/components/va-button/va-button.tsx

https://3724-button-continue--65a6e2ed2314f7b8f98609d8.chromatic.com
This will allow for a button text override when the `continue` variation is being used for `va-button` and `va-button-pair`. The default text will still be "Continue".
Notes from DSC meeting about opening up button component text: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2362#issuecomment-1901089276
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3724

va-button & va-button-pair: allow custom text for continue variation

---

packages/storybook/stories/va-banner.stories.jsx
packages/web-components/src/components.d.ts
packages/web-components/src/components/va-banner/test/va-banner.spec.ts
packages/web-components/src/components/va-banner/va-banner.tsx

https://vdsd-3738-dismissed-banner-id--65a6e2ed2314f7b8f98609d8.chromatic.com
---
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3738
Related  https://github.com/department-of-veterans-affairs/va.gov-cms/issues/20401
This adds an optional `dismissed-banner-id` property to the `va-banner` component. When set, this property will be stored in the user's Local Storage upon dismissing the banner. When not set, the `va-banner` will default to what it does today, utilizing the content of the banner to identify what has been dimissed.

va-banner: add dismissed-banner-id prop

---

packages/web-components/src/components.d.ts

https://generated-components-file--65a6e2ed2314f7b8f98609d8.chromatic.com
When I compiled the component-library locally, the generated component file showed a spelling update that was forgotten to get added to [the PR that created this prop](https://github.com/department-of-veterans-affairs/component-library/pull/1488).

Check in the generated components file

---

packages/web-components/src/components/va-link/va-link.tsx

Remove reference to icon in external link variation that had been [removed earlier](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3303).

Update external link description

---

packages/storybook/stories/va-alert-sign-in.stories.jsx
packages/web-components/src/components.d.ts
packages/web-components/src/components/va-alert-sign-in/AlertSignInVariants.ts
packages/web-components/src/components/va-alert-sign-in/test/va-alert-sign-in.e2e.ts
packages/web-components/src/components/va-alert-sign-in/va-alert-sign-in.tsx

https://sign-in-alert-no-prefill--65a6e2ed2314f7b8f98609d8.chromatic.com
---
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3791
- **N/A** - only a text update.

Add sign in alert no prefill variation

---

packages/web-components/src/components/va-table/va-table-inner/va-table-inner.scss

https://3776-fix-stacked-full-width-tables--65a6e2ed2314f7b8f98609d8.chromatic.com
---
Closes [#3776](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3776)
After:

va-table: Enabling stacked tables to always be full-width

---

README.md

https://aedp-aw-update-readme-for-verdaccio-in-codespaces--65a6e2ed2314f7b8f98609d8.chromatic.com
Closes [<ticket>](https://github.com/department-of-veterans-affairs/tmf-auth-exp-design-patterns/issues/294)
After completing the above ticket, we condensed the setup docs into a section of the README file. There are no changes to the components in this PR, solely an update to the README docs.
Open to suggestions on this content, but thought it could be useful for others
_just a doc update_
_just docs update_
No UI changes, just readme

update readme with steps to use Verdaccio in a GitHub Codespace

---

packages/css-library/dist/stylesheets/modules/m-eyebrow.css
packages/css-library/dist/stylesheets/modules/m-eyebrow.css.map
packages/css-library/dist/tokens/css/variables.css
packages/css-library/dist/tokens/scss/variables.scss
packages/css-library/src/stylesheets/modules/m-eyebrow.scss
packages/storybook/.storybook/style.scss
packages/storybook/package.json
packages/storybook/stories/Eyebrow.stories.mdx
packages/storybook/stories/additional-docs.js
yarn.lock

https://2580-eyebrow-css-class--65a6e2ed2314f7b8f98609d8.chromatic.com
---
Closes [#2580](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2580)

CSS-Library: Addition of vads-c-eyebrow class

---

packages/web-components/src/components/va-language-toggle/va-language-toggle.scss

https://lang-toggle-adjust-size--65a6e2ed2314f7b8f98609d8.chromatic.com
Follow up to [Language toggle accessibility updates #3564](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3564)
Revert font size to baseline. Increase padding to make touch target larger

Adjust va-language-toggle font size and padding

---

packages/web-components/src/components/va-accordion/va-accordion.e2e.ts
packages/web-components/src/components/va-accordion/va-accordion.tsx

https://nested-accordion--65a6e2ed2314f7b8f98609d8.chromatic.com
Closes [Nested Va-Accordions can't expand/collapse on single-open #3876](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3876)
Issue is caused by the `itemToggledHandler` in `va-accordion` running multiple times per click because the nested `va-accordion-item` has two parent `va-accordion`s. This fix checks to see if the `va-accordion` is actually the parent of the `va-accordion-item` before running `itemToggledHandler`.
Note: I didn't want to add a nested `va-accordion` to storybook as I don't think we want to "officially" support nested accordions, so if you want to test this locally, here is the template for the story:
```tsx
const Template = args => (
<va-accordion {...args}> …
```

Prevent nested va-accordion-items from propagating up

---

packages/storybook/stories/va-file-input-uswds.stories.jsx

https://file-input-storybook-default--65a6e2ed2314f7b8f98609d8.chromatic.com
It looks like we accidentally removed the default args from the Default storybook example in a [previous PR](https://github.com/department-of-veterans-affairs/component-library/pull/1500/files) so this is just adding it back:

va-file-input: Add back default args for storybook example

---

packages/web-components/src/components/va-checkbox/va-checkbox.scss

https://checkbox-label-font-size--65a6e2ed2314f7b8f98609d8.chromatic.com
I noticed that the label font size was calculating to `16px` but we want it to be the normalized font size (1.06rem/16.96px) as verified in [Figma](https://www.figma.com/design/afurtw4iqQe6y4gXfNfkkk/VADS-Component-Library?node-id=457-13307&t=EyAokwpbBgsksjH7-0).
Closes - No ticket
**before**
**after**

va-checkbox: add normalized font size token to label

---

packages/storybook/stories/va-checkbox-uswds.stories.jsx
packages/web-components/src/components/va-checkbox/test/va-checkbox.e2e.ts
packages/web-components/src/components/va-checkbox/va-checkbox.tsx

https://checkbox-aria-checked--65a6e2ed2314f7b8f98609d8.chromatic.com
---
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3807
`aria-checked` was not being set on the HTML attribute despite evaluating to `false`. I added a condition to set this to `null` and that removes the attribute as expected when it is unchecked.

Checkbox aria checked

---

packages/storybook/stories/va-checkbox-group-uswds.stories.jsx
packages/storybook/stories/va-memorable-date-uswds.stories.jsx
packages/storybook/stories/va-radio-uswds.stories.jsx
packages/storybook/stories/va-select-uswds.stories.jsx
packages/storybook/stories/va-text-input-uswds.stories.jsx
packages/storybook/stories/va-textarea-uswds.stories.jsx

https://storybook-button-label--65a6e2ed2314f7b8f98609d8.chromatic.com
No ticket for this I just noticed a few places where we weren't following our own guideline examples for button labels (capitalize first letter): https://design.va.gov/components/button/#button-labels
**before**
**after**

Storybook: Capitalize first letter in focus button labels

---

packages/core/package.json
packages/web-components/package.json
yarn.lock

https://mc-release-branch--65a6e2ed2314f7b8f98609d8.chromatic.com
---
Updates version of web components and core. Leaves out css-library because a manual release was done yesterday for that package.

Version bump for release 3-12-2025

---

packages/core/package.json
packages/storybook/stories/va-checkbox-uswds.stories.jsx
packages/web-components/package.json
packages/web-components/src/components/va-checkbox/test/va-checkbox.e2e.ts
packages/web-components/src/components/va-checkbox/va-checkbox.tsx
packages/web-components/src/utils/utils.spec.ts
packages/web-components/src/utils/utils.ts

Reverts department-of-veterans-affairs/component-library#1515
@Mottie - I am reverting this work because it's breaking a ton of cypress tests in vets-website. You can checkout some of the failures in [this pull request](https://github.com/department-of-veterans-affairs/vets-website/pull/35207). 
I verified this to be the case by installing a dummy release in vets-website [with verdaccio](https://github.com/department-of-veterans-affairs/component-library?tab=readme-ov-file#local-testing-in-vets-website-with-verdaccio) and running a bunch of the tests that are failing in the above PR. They all passed.

Revert "va-checkbox | Fix interactive elements in description"

---

packages/storybook/stories/wc-helpers.jsx

https://847-storybook-action-link--65a6e2ed2314f7b8f98609d8.chromatic.com
We were still using the deprecated `vads-c-action-link--green` utility class in Storybook instead of the web component so this PR replaces it.
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/847

Storybook: replace deprecated action link class with web component

---

packages/web-components/src/components/va-official-gov-banner/va-official-gov-banner.tsx

- **style(web-components): format va-official-gov-banner component**
- **fix(web-components): swap official gov banner icons**
https://2941-fix-gov-banner--65a6e2ed2314f7b8f98609d8.chromatic.com
---
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2941

va-official-gov-banner: swap icons

---

packages/web-components/src/components.d.ts
packages/web-components/src/components/va-alert/test/va-alert.e2e.ts
packages/web-components/src/components/va-alert/va-alert.tsx

https://close-label--65a6e2ed2314f7b8f98609d8.chromatic.com
---
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3768
Updated the alert close button to say "Close {headline} notification" if no custom text is provided. If the custom text property is set (`<va-alert closeable="true" close-btn-aria-label="Close this notification">`), that will take precedence. So any places that already use that prop will not be affected.
- N/A - No visual change.

Use headline text for alert close button ARIA label

---

packages/web-components/src/components/va-link/test/va-link.e2e.ts
packages/web-components/src/components/va-link/va-link.scss
packages/web-components/src/components/va-link/va-link.tsx

https://106044-ext-link--65a6e2ed2314f7b8f98609d8.chromatic.com
---
- Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3699
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/106044
- https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3718 (hide "opens in a new tab" when printing)
| Before - duplicate "opens in a new tab" text |
|----|
| <img width="582" alt="Screenshot 2025-03-31 at 12 00 09 PM" …

va-link | Remove duplicate screen reader content

---

packages/web-components/src/components/va-date/test/va-date.e2e.ts
packages/web-components/src/components/va-date/va-date.tsx
packages/web-components/src/utils/date-utils.ts

https://3651-default-days--65a6e2ed2314f7b8f98609d8.chromatic.com
When no month is selected, the day select is empty:
- This PR shows a default of 31 days when no month is selected
- When a month is selected, it will show the appropriate number of days
- When February is selected, it will show 29 for leap years and 28 for all other years
- When February is selected and a value greater than the accepted days, the select shows "Select" option, but the original value is still in place.
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3651

va-date | Show default days with no month selected

---

packages/storybook/stories/va-telephone.stories.tsx
packages/web-components/src/components.d.ts
packages/web-components/src/components/va-telephone/test/va-telephone.e2e.ts
packages/web-components/src/components/va-telephone/test/va-telephone.spec.tsx
packages/web-components/src/components/va-telephone/va-telephone.tsx

https://2531-vanity-phone--65a6e2ed2314f7b8f98609d8.chromatic.com
---
Updating `va-telephone` to allow full vanity replacement. The GI Bill team needs to replace more than the last 4 characters of the phone number, but maintain the last number. The easiest way around this requirement was to allow full vanity replacement. 
> 888-GIBILL-1 (888-442-4551)
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2531

va-telephone vanity to allow full replacement

---

packages/storybook/stories/va-breadcrumbs-uswds.stories.tsx
packages/web-components/src/components.d.ts
packages/web-components/src/components/va-breadcrumbs/test/va-breadcrumbs.e2e.ts
packages/web-components/src/components/va-breadcrumbs/va-breadcrumbs.tsx

https://1903-last-breadcrumb--65a6e2ed2314f7b8f98609d8.chromatic.com
[Staging review feedback](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2117) asked that we make the last breadcrumb item (the current page) a link that navigates to the `#content` hash on the page. But the forms library needs this link to be more flexibility in order to navigate users to the introduction page.
This update will add a new prop `current-page-redirect` (boolean) that will use the provided href value for the last link instead of overriding it with `#content`.
Closes https://github.com/department-of-veterans-affairs/VA.gov-team-forms/issues/1903

va-breadcrumb: add prop to conditionally use #content or a custom href for the current page

---

packages/storybook/stories/va-service-list-item.stories.tsx
packages/web-components/src/components.d.ts
packages/web-components/src/components/va-link/va-link.tsx
packages/web-components/src/components/va-service-list-item/test/va-service-list-item.e2e.ts
packages/web-components/src/components/va-service-list-item/va-service-list-item.tsx

https://aedp-aw-342-update-va-service-link-op--65a6e2ed2314f7b8f98609d8.chromatic.com/
Closes https://github.com/department-of-veterans-affairs/tmf-auth-exp-design-patterns/issues/342
Adds the ability for the optionalLink of the `va-service-list-item` to use any of the props that are available on the `va-link` component. This was requested via a content update where they mentioned having guidance that matches the va-link as well.
> Format the optional link to express what it will do. For example, if the link is a [download link](https://dev-design.va.gov/3973/components/link/#download), include the standard download icon. If it takes users to an external site, display the standard "(opens in new tab)" text. See additional accessibility guidance in the …

va-service-list-item: support all va-link props via shared interface

---

packages/storybook/.storybook/style.scss
packages/storybook/stories/va-modal-uswds.stories.tsx
packages/storybook/stories/wc-helpers.tsx

https://771-expand-modal-story--65a6e2ed2314f7b8f98609d8.chromatic.com
When a modal is opened, the contents aren't completely visible within the storybook story. This PR adds a class to the wrapper to increase the height to `400px` - this makes all current modals completely visible within the storybook page.
- https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/771
The above ticket was meant for the documentation pages at design.va.gov, so I misunderstood the need; but this is still a good addition :D
|---|---|
| ![modal-before](https://github.com/user-attachments/assets/5c427321-21c7-4e0d-a3f4-bf5be60a6ba3) | ![modal](https://github.com/user-attachments/assets/cc66ed99-64fa-4bdf-9947-0de12f90f03b) |

Expand story when modal is open

---

packages/core/package.json
packages/css-library/package.json
packages/web-components/package.json
yarn.lock

https://50.2.0-release--65a6e2ed2314f7b8f98609d8.chromatic.com
---
Preps repo for next release

Bump repo semver for 50.2.0

---

packages/storybook/stories/va-file-input-multiple-uswds.stories.tsx
packages/storybook/stories/va-file-input-uswds.stories.tsx

https://va-file-input-add-platform-documentation--65a6e2ed2314f7b8f98609d8.chromatic.com
Adds link to "Accept Password Field" stories of `va-file-input` and `va-file-input-multiple`
Closes [Add link to platform documentation for displaying password field on va-file-input in storybook #3980](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3980)

va-file-input and va-file-input-multiple: Add link to platform documentation for encrypted PDFs

---

packages/web-components/src/components/va-alert/test/va-alert.e2e.ts
packages/web-components/src/components/va-alert/va-alert.tsx

https://longmd-105037-fix-va-alert-typeerror--65a6e2ed2314f7b8f98609d8.chromatic.com
---
After implementing Datadog logs on the Caregivers application, the a recurring log we notice is emitting from the va-alert web component. The error message is `TypeError: Cannot read properties of undefined (reading 'textContent')` This error is occurring because the component is attempting to find the headline `slot` when not all alerts have headlines.
This PR creates a shared method that attempts to fetch the headline slot for both the …

va-alert: fix TypeError for close button aria label

---

packages/core/package.json
packages/web-components/package.json

https://release-v50.2.1--65a6e2ed2314f7b8f98609d8.chromatic.com
---

update package versions for release v50.2.1

---

packages/web-components/src/components/va-modal/test/va-modal.e2e.ts
packages/web-components/src/components/va-modal/va-modal.tsx

https://longmd--108748-fix-va-modal-typeerror--65a6e2ed2314f7b8f98609d8.chromatic.com
---
After implementing Datadog logs on the multiple applications, there a consistent log emitting from the `va-modal` web component. The error messages are `TypeError: Cannot read properties of undefined (reading 'classList')` & `TypeError: undefined is not an object (evaluating 'e.classList')`. These errors occur on initial render where an attempt to apply focus to an internal element is made before the shadow DOM (or shadow DOMs of …

va-modal: Fix TypeError on render

---

setup.sh

https://add-react-bindings-command-dev-script--65a6e2ed2314f7b8f98609d8.chromatic.com
Sometimes we need the build to regenerate the react bindings so this will add it to the setup script that runs with `yarn run dev`
Reference full list of build steps here:
https://github.com/department-of-veterans-affairs/component-library?tab=readme-ov-file#running-build-via-storybook

Add react-bindings build step to script

---

packages/storybook/stories/va-modal-uswds.stories.tsx
packages/storybook/stories/wc-helpers.tsx

https://chromatic-modal-visual-regression--65a6e2ed2314f7b8f98609d8.chromatic.com/?path=/docs/uswds-va-modal--docs
We have not been able to track visual changes to va-modal in Storybook with Chromatic because it required a button to be clicked before the modal would display. 
This PR will set the modals `visual` prop to true but it also deals with some unwanted scrolling behavior in Storybook that is built into the component itself when the modals are set to open.
With the modals now defaulting to open, we have some baseline Chromatic snapshots to start diffing against. 🎉
No issue to reference but this is in response to a Slack conversation here: https://dsva.slack.com/archives/C01DBGX4P45/p1747081203050729
I also checked the documentation site locally and it appears to be working there …

Set va-modal visual to true by default in Storybook

---

packages/web-components/src/components/va-file-input/test/va-file-input.e2e.ts
packages/web-components/src/components/va-file-input/va-file-input.tsx

https://108718-va-file-input-dictation--65a6e2ed2314f7b8f98609d8.chromatic.com
It was reported that you could not use dictation to click on the file input and select a file. This PR adds an aria-label so that the field becomes actionable with dictation.
Closes [108718](https://github.com/department-of-veterans-affairs/va.gov-team/issues/108718)
- [ x] New components are covered by e2e tests; updates to existing components are covered by existing test suite
- [ x] Changes …

va-file-input: add aria-label to input for dictation

---

packages/web-components/src/components/va-combo-box/va-combo-box-library.js

https://4105-combo-box-bug--65a6e2ed2314f7b8f98609d8.chromatic.com
---
This PR fixes a bug in which after choosing an option and revisiting the options to choose another, only the first selected option is visible in the dropdown.
Closes [4105](https://github.com/orgs/department-of-veterans-affairs/projects/1643/views/5?sliceBy%5Bvalue%5D=Sprint+3&pane=issue&itemId=110264707&issue=department-of-veterans-affairs%7Cvets-design-system-documentation%7C4105)
Before: 
After:

va-combo-box: make all options persist in dropdown after selection

---

README.md

https://release-readme-steps--65a6e2ed2314f7b8f98609d8.chromatic.com
During our group release party, we noticed a few [release steps](https://github.com/department-of-veterans-affairs/component-library?tab=readme-ov-file#releasing) weren't accurate anymore or not very clear so this is just a few adjustments for the next time.
https://github.com/department-of-veterans-affairs/component-library/pull/1599/files?short_path=b335630#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

Update release steps

---

packages/web-components/src/components.d.ts
packages/web-components/src/components/va-statement-of-truth/test/va-statement-of-truth.e2e.ts
packages/web-components/src/components/va-statement-of-truth/va-statement-of-truth.tsx
packages/web-components/src/components/va-text-input/test/va-text-input.e2e.ts
packages/web-components/src/components/va-text-input/va-text-input.tsx

https://107935-sot-privacy--65a6e2ed2314f7b8f98609d8.chromatic.com
Adds `error-has-pii` property to `va-text-input` which is then used by the `va-statement-of-truth` component when rendering an error. The span containing the error would then have a `dd-privacy-hidden` class and a `data-dd-action-name` attribute applied to prevent PII exposure within Datadog Real User Monitoring sessions.
- Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/107935
- [Slack discussion about implementation](https://dsva.slack.com/archives/C01DBGX4P45/p1746631663473989?thread_ts=1746631613.935949&cid=C01DBGX4P45)
| | |
|----|---|
| Before | <img width="971" alt="before changes showing error span with no treatment" src="https://github.com/user-attachments/assets/efd5feb3-2a72-46bb-b691- …

va-text-input & va-statement-of-truth: add prop for adding Datadog privacy class on error message

---

packages/web-components/src/components/va-accordion/va-accordion.tsx

https://4010-va-accordion-expand-bug--65a6e2ed2314f7b8f98609d8.chromatic.com
This fixes an issue where a user needed to click an accordion item twice after using the "Expand all" button to collapse it.
The issue was caused by the logic expecting a "true" value for the "open" attribute. Since setAttribute only adds the attribute name to the DOM if the value is "true" the logic was failing. The fix checks for the value to be false first and then checks if the accordion-item has the attribute open.
Closes [4010](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/4010)
- [ x] …

va-accordion: logic update to fix 2 clicks to collapse bug

---

packages/storybook/stories/va-table-uswds.stories.tsx
packages/web-components/src/components.d.ts
packages/web-components/src/components/va-table/sort/utils.tsx
packages/web-components/src/components/va-table/va-table-inner/test/va-table-inner.e2e.ts
packages/web-components/src/components/va-table/va-table-inner/va-table-inner.tsx
packages/web-components/src/components/va-table/va-table.tsx

https://4056-table-data-sort-attribute--65a6e2ed2314f7b8f98609d8.chromatic.com
The `data-sort-value` attribute can be added to the cell `span` for sorting based on a raw value instead of a formatted cell value.
This is based on the [USWDS guidelines](https://designsystem.digital.gov/components/table/#using-the-table-component): 
> Provide raw values for cells with formatted number content. If you have formatted your cell content for display (such as using percent, currency, or comma formatting) or if your cell content is non-numeric but should be sorted in a numeric order (such as months, days of the week, or dates), provide a numeric-sortable value in a data-sort-value attribute on each table cell. 
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/ …

va-table: add data-sort-value attribute for raw number value sorting

---

packages/web-components/src/components/va-combo-box/test/va-combo-box.e2e.ts
packages/web-components/src/components/va-combo-box/va-combo-box.tsx

https://mhv-71475-combo-box-default-value-fix--65a6e2ed2314f7b8f98609d8.chromatic.com
---
Closes [MHV-71475](https://jira.devops.va.gov/browse/MHV-71475) - Combo Box - bug - fix default value not populating
We noticed a bug in the combo box after a recent update.  It was not being populated with the default value if one was provided.

va-combo-box: populate options when loading

---

packages/storybook/stories/va-alert-sign-in.stories.tsx
packages/web-components/src/components/va-alert-sign-in/test/va-alert-sign-in.e2e.ts
packages/web-components/src/components/va-alert-sign-in/va-alert-sign-in.tsx

https://3690-sign-in-apostrophes--65a6e2ed2314f7b8f98609d8.chromatic.com
Closes [#3960](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3960)
Replaces straight apostrophes (i.e. `'`) with curly apostrophes (i.e. `’`) in `va-alert-sign-in` to match style guide.
- Content change only
- Content change only _Not sure if this applies here?_
- Content change only _Not sure if this applies here?_
- Content change only
Old (mobile):
New (mobile):
Old (desktop):
New (desktop):

va-alert-sign-in: replace straight apostrophes with curly ones

---

packages/storybook/stories/va-link.stories.tsx
packages/web-components/src/components/va-link/test/va-link.e2e.ts
packages/web-components/src/components/va-link/va-link.scss
packages/web-components/src/components/va-link/va-link.tsx

https://4025-link-wrap--65a6e2ed2314f7b8f98609d8.chromatic.com
Fixed the wrapping of the "(opens in a new tab)" text that is included when the `external` property is included.
- https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/4025
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/107923
|---|---|
| <img width="577" alt="Image" src="https://github.com/user-attachments/assets/590f7d0a-0e2b-42e9-8dc1-a27c87e827d2" /> | <img width="575" alt="Screenshot 2025-06-02 at 4 00 41 PM" src="https://github.com/user-attachments/assets/813bc875-515c-46cc-8d56-f38077c81041" /> |

va-link | Fix external link text wrapping

---

packages/web-components/src/components/va-input-telephone/test/va-input-telephone.e2e.ts
packages/web-components/src/components/va-input-telephone/va-input-telephone.tsx
packages/web-components/src/utils/utils.spec.ts
packages/web-components/src/utils/utils.ts

https://va-input-tel-grammar--65a6e2ed2314f7b8f98609d8.chromatic.com
---
This PR improves the grammar of the error message when a phone number is missing such that the article before the country name is a/an as needed.
Before:
After:

va-input-telephone: improve grammar of error message

---

packages/web-components/src/components/va-combo-box/test/va-combo-box.e2e.ts
packages/web-components/src/components/va-combo-box/va-combo-box-library.js

https://4226-combo-box-fix-filters--65a6e2ed2314f7b8f98609d8.chromatic.com
**Restored previous filtering functionality to combo box.** The filter should now [match the previous filtering behavior](https://4105-combo-box-bug--65a6e2ed2314f7b8f98609d8.chromatic.com/) (PR #1602) in both `va-combo-box` and `va-input-telephone`.
- This functionality was originally created in https://github.com/department-of-veterans-affairs/component-library/pull/1478
- This functionality was removed in https://github.com/department-of-veterans-affairs/component-library/pull/1595/
In a future iteration, recommend incorporating the improved sorting of USWDS' combo box introduced in [USWDS v3.10.0](https://github.com/uswds/uswds/releases/tag/v3.10.0). However, there will need to be some discussion about how to …

va-combo-box: Restore filtering functionality

---

packages/storybook/stories/va-textarea-uswds.stories.tsx
packages/web-components/src/components/va-link-action/va-link-action.scss
packages/web-components/src/components/va-textarea/va-textarea.scss

https://4075-bold-hint-text--65a6e2ed2314f7b8f98609d8.chromatic.com
Updates `<va-textarea>` so that when a `hint` is set in combination with `label-header-level` value, the label text has a normal font-weight rather than bold.
Closes [#4075](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/4075)
Current version:
Incoming change:
**Approval Groups**
- Accessibility: [platform-design-system-a11y](https://github.com/orgs/department-of-veterans-affairs/teams/platform-design-sy …

`va-textarea`: Fix hint to ensure font-weight is normal

---

packages/web-components/src/components/va-table/test/va-table.e2e.ts
packages/web-components/src/components/va-table/va-table.tsx

https://4064-va-table-nested-span--65a6e2ed2314f7b8f98609d8.chromatic.com
The va-table getCellsInRow function was selecting all spans within a row element and the component was adding va-table-slot to them. This change is to only select the top level/children of the row instead of both children and further embedded spans.
Closes [4064](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/4064)
The table story was not updated to include an example with an embedded span as I don't know if that should be encouraged, manual verification is required.
A test has also been added
Add approval …

va-table: prevent table slot attributes from being added to nested spans

---

packages/web-components/src/components/va-button-icon/va-button-icon.scss
packages/web-components/src/components/va-button/va-button.scss

https://3086-file-input-button-focus--65a6e2ed2314f7b8f98609d8.chromatic.com
The button focus outline was getting covered up by sibling elements. This change updates the button to have a `position:relative` and a z-index on focus. The primary example of the overflow happening was in the file upload component on small screens where the buttons wrapped.
Closes [3086](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3086)
Before: 
After:
Testing can be done using the va-file-input component.
-  Add a file 
- Shrink the window so that the buttons wrap
- Bring focus to the Change file button
- The focus outline should be completely visible
See the QA Checklists section below for suggested approvals. Use your best judgment if additional reviews are …

va-button, va-button-icon: fix for focus outline getting covered up

---

packages/core/package.json
packages/css-library/package.json
packages/web-components/package.json
yarn.lock

https://51.4.0-release--65a6e2ed2314f7b8f98609d8.chromatic.com
This updates the library for release 
- Design: [platform-design-system-designer](https://github.com/orgs/department-of-veterans-affairs/teams/platform-design-system-designers)
Use the QA checklists below as guides, not rules. Not all …

51.4.0 release

---

packages/web-components/src/components/va-sidenav/test/va-sidenav-item.e2e.ts
packages/web-components/src/components/va-sidenav/test/va-sidenav.e2e.ts
packages/web-components/src/components/va-sidenav/va-sidenav.tsx

https://va-sidenav-current-page--65a6e2ed2314f7b8f98609d8.chromatic.com
This will update the `va-sidenav` component to better handle truthy values for `current-page` and if the prop is not set with a truthy value, the attribute will be removed (instead of set to "false"). Examples of truthy values:
- Explicit true: `current-page="true"`
- Empty string: `current-page=""`
- Just attribute (no value): `current-page`
- Different case: `current-page="TRUE"`
The `current-page` is considered "false" in the following scenarios but we are no longer explicitly setting "false" internally. This was causing issues with identifying the active page. Falsy scenarios are 
- Explicit false: `current-page="false"`
- No attribute: (attribute not present)
Closes …

va-sidenav: enhance current-page handling for truthy and false values 

---

packages/web-components/src/components/va-alert/test/va-alert.e2e.ts
packages/web-components/src/components/va-alert/va-alert.tsx
packages/web-components/src/components/va-banner/test/va-banner.e2e.ts
packages/web-components/src/components/va-banner/va-banner.tsx

https://3119-alert-header--65a6e2ed2314f7b8f98609d8.chromatic.com
The `va-alert` component has a variation "slim" that is intended to be used without a headline. But when a standard alert was being used without a headline and the `slim` prop wasn't also set, there was an unsightly gap at the top where the header should go. This PR will automatically set the `slim` prop if there's no `headline` slot content.
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3119
When the `headline` slot is not populated:
**Before**
**After**
- …

va-alert: add the slim prop if no headline is provided

---

packages/storybook/stories/va-button-segmented.stories.tsx
packages/web-components/src/components/va-button-segmented/test/va-button-segmented.e2e.ts
packages/web-components/src/components/va-button-segmented/va-button-segmented.scss
packages/web-components/src/components/va-button-segmented/va-button-segmented.tsx

https://4777-seg-button-2-or-3-bug--65a6e2ed2314f7b8f98609d8.chromatic.com
This PR updates the `<va-button-segmented>` component to fix a bug where the styles of the child `<ul>` element were not responsive when two or three buttons were used instead of four.
The updates make it so that: 
- On mobile resolutions, the buttons will each span an equal number of grid columns (where the number of columns equals the number of buttons), while the `<ul>` will continue to fill its parent container.
- On tablet and desktop resolutions, the buttons will have an automatic width, taking up only as much space as needed for their text and padding. The parent `<ul>` will also have an automatic width to accommodate the buttons.
I have also added two stories for <va-segmented-button>, showcasing each of …

va-button-segmented: Update styles for two/three buttons

---

packages/web-components/src/components/va-textarea/va-textarea.scss

https://4799-textarea-zoom-width--65a6e2ed2314f7b8f98609d8.chromatic.com
**Fixed the width of `va-textarea` at high zoom.** The `textarea` element is missing `box-sizing: border-box` from its styles. This rule will allow it to more predictably fit into its container. 
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/4799
1. Zoom into the component stories at 400% and confirm that the component does not require horizontal scrolling
2. Confirm no unintended visual regressions
3. Confirm code meets standards
- Engineering: …

va-textarea: Fix horizontal overflow at high zoom

---

packages/web-components/src/components/va-accordion/va-accordion.e2e.ts
packages/web-components/src/components/va-accordion/va-accordion.scss
packages/web-components/src/components/va-accordion/va-accordion.tsx

https://4531-expand-collapse-buttons--65a6e2ed2314f7b8f98609d8.chromatic.com
Separated the current "Expand/collapse all" button into two separate buttons. This has two main benefits:
1. It adds more direct control over the expanded and collapsed states of the component 
2. It provides a more accurate state readout to screen reader users
This approach was at least partially informed by the following articles:
- https://inclusive-components.design/toggle-button/
> As a rule of thumb, you should never change pressed state and label together. If the label changes, the button has already changed state in a sense, just not via explicit WAI-ARIA state management.”
- https://inclusive-components.design/collapsible-sections/
> It's tempting to implement 'expand/collapse all' as a single toggle …

va-accordion: Create separate buttons for "expand all" and "collapse all"

---

packages/storybook/stories/va-file-input-multiple-uswds.stories.tsx
packages/storybook/stories/va-file-input-uswds.stories.tsx
packages/storybook/stories/va-text-input-uswds.stories.tsx
packages/web-components/src/components.d.ts
packages/web-components/src/components/va-file-input/va-file-input.tsx
packages/web-components/src/components/va-text-input/test/va-text-input.e2e.ts
packages/web-components/src/components/va-text-input/va-text-input.tsx

https://4706-file-input-password--65a6e2ed2314f7b8f98609d8.chromatic.com
This resolves an issue flagged for `va-file-input` where the passwords for encrypted files were shown as plain text as opposed to being masked. Rather than using JS/CSS to mask the input value, I added a password variation for the `type` prop of `va-text-input` to simplify things and utilize the web standard as best practice.
File changes also include fixing some typos and cleaning up indentation in the story files for `va-file-input` and `va-file-input-multiple`.
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/4706
1. Navigate to "Accespts File Password" story for either [`<va-file-input>`](https://4706-file-input-password--65a6e2ed2314f7b8f98609d8.chromatic.com/?path= …

va-text-input: Add password type variation / va-file-input: Use new password variation to mask file password.
